### ISSUE TITLE
Display will not sleep

### ISSUE THREAD

**Issue by bobbyo12** [JohnCoates/Aerial#70] opened 2015-10-29 19:46 UTC
Hi, love the Aerial screensaver but I have noticed one issue.  I have my display set to sleep after 15 minutes but it will not do this when I run the Aerial screensaver.  I'm running El Cap on an iMac (21.5-inch, Mid 2011).  Any ideas on how I can get my display to sleep while running Aerial?

**Comment by mwifio** [comment] 2015-10-29 20:11
Same problem with a 27" Mid 2011 on 10.11.1 (15B42)

**Comment by briantully** [comment] 2015-10-29 20:43
Same issue here. Display is set to sleep after 30 minutes on a MacBook Pro running 10.10.5. Woke up in the middle of the night last night and saw my home office was lit up from the glow of the screensaver, despite the computer not being used for several hours. I suspect the screensaver requires network access and therefore the display never sleeps?

**Comment by alistairmcmillan** [comment] 2015-10-29 21:09
Duplicate of #23

**Comment by JohnCoates** [comment] 2015-10-30 10:00
Thanks @alistairmcmillan for linking the original issue. I'm trying to fix this, but the solution I've found is quite complicated and will take a bit to implement.

**Closed by JohnCoates** 2015-10-30 10:00 UTC
Labels: duplicate
