### ISSUE TITLE
Cannot use Aerial Screensaver with OSX 10.14 Beta 4

### ISSUE THREAD

**Issue by tpmacleod** [JohnCoates/Aerial#480] opened 2018-07-22 18:37 UTC
Aerial screensaver will not work with OSX 10.14 Beta 4. I believe it stopped working with the update. I do understand these are betas but I enjoy the project so much I was just looking to get it working.

Tim

**Comment by warrentheranga** [comment] 2018-07-22 23:50
Duplicate of https://github.com/JohnCoates/Aerial/issues/464

**Comment by alistairmcmillan** [comment] 2018-07-30 10:09
Closing as duplicate of #464

**Closed by alistairmcmillan** 2018-07-30 10:09 UTC
