### ISSUE TITLE
Compatibility with macOS Mojave

### ISSUE THREAD

**Issue by andy9man** [JohnCoates/Aerial#481] opened 2018-07-24 05:18 UTC
Really appreciate the work you do, awesome screensaver.  Doesn't seem to work with Mojave, any plans on making an update?  And 4K?

**Comment by yurivangeffen** [comment] 2018-07-24 11:09
> You cannot use the Aerial screen saver with this version of MacOS. Please contact the vendor to get a newer version of the screen saver.
- Desktop & Screen Saver

**Comment by bdnk** [comment] 2018-07-24 14:56
Duplicate of #464

**Comment by alistairmcmillan** [comment] 2018-07-30 10:08
Closing as duplicate of #464

**Closed by alistairmcmillan** 2018-07-30 10:08 UTC
