### ISSUE TITLE
4K Videos

### ISSUE THREAD

**Issue by AVC29** [JohnCoates/Aerial#431] opened 2017-12-11 00:04 UTC
Hi there, I have a 5K iMac and would love for this screensaver to play the 4K versions of the files. Is this something that is coming? Thanks so much.

**Comment by leggsimon** [comment] 2017-12-11 10:02
https://github.com/JohnCoates/Aerial/issues/378

**Comment by ccharlton** [comment] 2017-12-15 21:09
Close ticket due to being a dupe.

**Comment by alistairmcmillan** [comment] 2017-12-27 16:56
Closing as duplicate of #378.

**Closed by alistairmcmillan** 2017-12-27 16:56 UTC
