### ISSUE TITLE
Feature Request: Automatic Day / Night Selection

### ISSUE THREAD

**Issue by jmcquillan** [JohnCoates/Aerial#116] opened 2015-11-01 19:17 UTC
There should be an option to only show only 'Day' videos during the day and 'Night' videos at night.

**Comment by DJay1** [comment] 2015-11-01 21:07
This was one of my first thoughts about this great screen saver. Would love to see this in a next update.

**Comment by alistairmcmillan** [comment] 2015-11-02 10:17
Duplicate of #11

**Closed** 2015-11-02 16:39 UTC
