### ISSUE TITLE
Add Apple Developer Certificate

### ISSUE THREAD

**Issue by timfallmk** [JohnCoates/Aerial#167] opened 2015-11-17 21:16 UTC
Add a signed Apple Developer Certificate so the file can be opened without Gatekeeper complaining. For free projects, there is a free developer certificate.

https://developer.apple.com/programs/how-it-works/

**Comment by alistairmcmillan** [comment] 2015-11-18 01:01
Are you certain there are free developer certificates? I was trying to figure this out the other day. I was sure I'd read that there was a free option now but everything I find on Apple's site says you need an Apple Developer Program membership.

"Apple Developer Program membership is required to request, download, and use signing certificates issued by Apple.'
https://developer.apple.com/support/certificates/

"Before you begin, enroll in the Apple Developer Program..."
https://developer.apple.com/library/mac/documentation/IDEs/Conceptual/AppDistributionGuide/DistributingApplicationsOutside/DistributingApplicationsOutside.html

**Comment by Markyt1977** [comment] 2015-11-18 19:17
mark tegeda
On Nov 17, 2015 2:16 PM, "Tim" <notifications@github.com> wrote:
>
> Add a signed Apple Developer Certificate so the file can be opened
without Gatekeeper complaining. For free projects, there is a free
developer certificate.

**Comment by timfallmk** [comment] 2015-11-19 18:46
@alistairmcmillan I'm sure there used to be one, let me check if that changed recently. If not, I have a paid account that can generate signing certificates if you'd like to go down that route.

**Comment by timfallmk** [comment] 2015-11-19 18:51
@alistairmcmillan Looks like the new consolidated accounts get rid of the free tier. Sorry about the false alarm :frowning: . I can still generate signing certificates if you want that.

**Comment by alistairmcmillan** [comment] 2016-01-28 22:27
Closing as duplicate of #10

**Closed by alistairmcmillan** 2016-01-28 22:27 UTC
Labels: duplicate, enhancement

**Comment by Appuploader** [comment] 2017-07-01 09:03
Share Appuploader tool only need to enter the iOS certificate name, password can quickly apply for iOS certificate. P12 and ..mobileprovision iOS certificate file

But also in the Windows system directly apply for iOS certificate

https://github.com/Appuploader/applicationloader
