### ISSUE TITLE
Aerial on High Sierra

### ISSUE THREAD

**Issue by mhyatt18** [JohnCoates/Aerial#383] opened 2017-09-21 00:19 UTC
I have Aerial running successfully on an iMac and a MBP 2015. However, it is not working on the new MBP with TouchBar. Do you intend to make this compatible with High Sierra. I love this app and am spoiled!

**Comment by alistairmcmillan** [comment] 2017-09-21 07:26
Duplicate of #381

**Closed by alistairmcmillan** 2017-09-21 07:26 UTC
Labels: duplicate

**Comment by alistairmcmillan** [comment] 2017-09-21 07:27
Duplicate of #377
