### ISSUE TITLE
Clock sometimes does not update on Aerial

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1234] opened 2022-03-22 19:56 UTC
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: Mac mini (M1, 2020)
- [ ] macOS version: 12.3 (21E230)
- [ ] Monitor setup: single monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

I am noticing that often the clock freezes on the screensaver. Since I sometimes glance at the monitor to keep me on time, this has almost made me late thinking I had plenty of time. 

If you need logs, etc. let me know.

**Comment by glouel** [comment] 2022-03-22 22:12
Hey @mbierman 

Just to be clear, the clock freezes but the video continues ? Bit of a weird one. Will think about it and get back to you. 

Log would be nice next time you catch it, note the stuck time and attach the log. Thanks !

**Comment by mbierman** [comment] 2022-03-24 17:36
@glouel sorry for the delay. I confirmed that it isn't just the clock but the screensaver as a whole that freezes.

Log attached. It froze last night sometime after 1am and before 7am this morning. 

[AerialLog.txt.zip](https://github.com/JohnCoates/Aerial/files/8344055/AerialLog.txt.zip)

**Comment by glouel** [comment] 2022-03-24 17:40
Hey @mbierman 

No problem, so that's what I feared, it's the elusive Mac not going to sleep bug that other people on M1 macs (only) seem to encounter, though not everyone : https://github.com/JohnCoates/Aerial/issues/1225

My best guess is it's a macOS bug. Aerial "freezing" is what it's supposed to do, it's just that the mac doesn't go to sleep at that point where it should.

**Comment by mbierman** [comment] 2022-03-30 19:44
Is it possible to try the new beta in homebrew?

**Comment by glouel** [comment] 2022-03-30 20:03
Sorry nope, either companion or manual install, I don't think homebrew has support for betas.

**Comment by mbierman** [comment] 2022-03-31 17:18
@glouel Beta 1 does not address the issue on my Mac. After about 30 minutes it froze again.

**Comment by glouel** [comment] 2022-03-31 17:19
Was the video + clock frozen ?

**Comment by mbierman** [comment] 2022-03-31 18:08
@glouel Correct.

**Comment by glouel** [comment] 2022-04-05 11:10
Closing this one as a duplicate of #1225, see new information in there about the external monitor information

**Closed by glouel** 2022-04-05 11:10 UTC
