### ISSUE TITLE
macOS Sierra?

### ISSUE THREAD

**Issue by dzakary** [JohnCoates/Aerial#287] opened 2016-12-27 03:34 UTC
I get errors that Aerial isn't compatible with Sierra.

**Comment by alistairmcmillan** [comment] 2016-12-27 03:40
It's a bug in OSX/macOS.

The screensaver itself should launch and run okay.

The bug should just affect the preview in System Preferences. If you select Aerial, close System Preferences, then re-open System Preferences, you should find that the preview works okay.

Closing as a duplicate of #269 .

**Closed by alistairmcmillan** 2016-12-27 03:40 UTC
