### ISSUE TITLE
Feature request: new aerial screensavers

### ISSUE THREAD

**Issue by joshlewis** [JohnCoates/Aerial#463] opened 2018-06-04 19:13 UTC
I hope you'll be doing whatever is necessary to support the new aerial screensavers! I love this screensaver so much!

**Comment by MarcelloNicoletti** [comment] 2018-06-04 19:27
Space would be very nice!

**Comment by jarrah31** [comment] 2018-06-04 20:17
I'd love the new screensavers too, but it looks like this app is no longer being maintained?

**Comment by chucker** [comment] 2018-06-04 20:24
The current JSON manifest doesn't appear to include them yet, so either they haven't actually shipped those videos yet, or the new tvOS release uses a new URL.

**Comment by WEZANGO** [comment] 2018-06-04 23:13
None of 3rd party screensavers seems to work with new Mojave, including this Aerial app.  
<img width="337" alt="screen shot 2018-06-05 at 00 13 25" src="https://user-images.githubusercontent.com/3215437/40946429-50a18d24-6855-11e8-8520-bf4798e247c9.png">

**Comment by remus-b** [comment] 2018-06-05 15:15
@WEZANGO it writes on the main page of the project about this issue. Try it, maybe it will work. Cheers!

**Comment by WEZANGO** [comment] 2018-06-05 18:37
@remus-b unfortunately no luck. Also tried to delete and reinstall it, but still not working.

**Comment by chucker** [comment] 2018-06-12 07:36
Can anyone confirm tvOS 12 will even fetch the new videos yet? They may not be live at this point.

**Comment by bluestarstudios** [comment] 2018-09-05 03:11
Any updates on this? Would love to see the new ones on here some day! :)

**Comment by nicoduj** [comment] 2018-09-19 17:32
I saw the new video yesterday on my ATV, but definitely the url seems to be different since we don't get them in the json files that are in use (neither the one with 4K videos).

**Comment by johndpope** [comment] 2018-09-20 01:39
http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers#30047FDA-3AE3-4E74-9575-3520AD77865B 
can someone painstakingly create a gist to download all the videos using youtube downloader?

should be
```shell
brew install youtubedl

youtubedl  http://youtube.com/link......
```

**Comment by johndpope** [comment] 2018-09-20 01:44
<img width="1007" alt="screen shot 2018-09-19 at 9 44 02 pm" src="https://user-images.githubusercontent.com/289994/45790894-27c0f800-bc55-11e8-8e13-23c7c746dadc.png">
https://sylvan.apple.com/Videos/comp_A114_C001_0305OT_v10_SDR_FINAL_22062018_SDR_2K_AVC.mov

**Comment by joshlewis** [comment] 2018-09-20 02:43
I think what we actually need is the new JSON url from Apple. This is the original one:

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

That one doesn't have the new stuff. That's the root of the issue. So what is the new one? Would any little birdies like to tell us? If someone here has an AppleTV and can run its traffic through a VPN you control, you could probably see where it's going to get the list of videos to play.

**Comment by nsayer** [comment] 2018-09-20 02:47
This guy has them: http://benjaminmayo.co.uk/watch-all-the-apple-tv-aerial-video-screensavers

**Comment by joshlewis** [comment] 2018-09-20 02:47
The page at benjaminmayo.co.uk is using this JSON feed:

http://benjaminmayo.co.uk/scripts/apple-tv-screensavers.json

But that one isn't provided by Apple, and thus might fall out-of-date with the real thing. I presume we won't get an update until we have the actual Apple feed's new URL.

So, hey @benjaminmayo, what's the new URL?

**Comment by benjaminmayo** [comment] 2018-09-20 10:19
The format changed somewhat; you need to extract the JSON out of here https://sylvan.apple.com/Aerials/resources.tar. The JSON includes the URLs to the videos and the time markers for the tvOS 12 captions as a dictionary, keyed by time. The values of this dictionary are keys which can be found in the strings plists.

**Comment by glouel** [comment] 2018-09-20 14:47
For those who would like to test it, I made a quick fork that parses the new files, it plays the 4K-SDR videos by default. Build here : 
https://github.com/glouel/Aerial/releases/download/v1.4a1/Aerial.saver.zip

**Comment by johnnyblair** [comment] 2018-09-20 15:19
Thanks seems to be working, with the exception of the "Done" button.

**Comment by glouel** [comment] 2018-09-20 18:52
Yes the Done button seems to be a Mojave issue, happened also with previous versions. I'll try to have a look tomorrow but not sure what happens there. See 
https://github.com/JohnCoates/Aerial/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement

**Comment by JonoHaysom** [comment] 2018-09-23 12:13
> I investigated the Done button a bit but couldn't find anything particular, I assume it's another bug linked to Swift screensavers in Mojave, I'll try submitting a radar next week with a small sample project.
> 
> In the meantime, pushed a new version with a few features :
> 
> * 1080p and 4K support (you can switch in cache panel)
> * optional video description displayed (bottom left of the screen at video start
> * tweaked the path selector's color for dark mode in cache panel (was barely readable)
> 
> Build here : https://github.com/glouel/Aerial/releases/download/1.4b5/Aerial.saver.zip

Awesome stuff! the new videos work perfectly for me. thanks for work you've put into this

**Comment by glouel** [comment] 2018-09-24 10:30
Hopefully we'll be able to merge changes when @JohnCoates names some extra mainteners. In the meantime, one last build, finally found the issue with the "Done" button not closing on Mojave. 

I ended up browsing all swift screensavers on github, found the answer on this project https://github.com/burnsra/SilhouetteSaver (which ironically doesn't work on Mojave) with an alternate way to dismiss the sheet 🎉

Build here : 
https://github.com/glouel/Aerial/releases/download/1.4b6/Aerial.saver.zip

**Comment by jarrah31** [comment] 2018-09-24 11:59
Thank you very much @glouel for the work you've put into this - the earth from space video looks amazing on my MacBook!

**Comment by nicoduj** [comment] 2018-09-24 18:07
great job @glouel !

**Comment by frenchfalcon** [comment] 2018-09-24 18:09
@glouel Thank you so much. I spent a day trying all possibilities to terminate the sheet and didn't think about this one.

**Comment by Smiffleblurf** [comment] 2018-09-25 00:16
@glouel Thank you so much! I was so excited to add these new stunning ISS screen savers after tvOS 12 released to this old app.

**Comment by rochev22** [comment] 2018-09-25 04:09
@glouel thanks for your update!!!

**Comment by jstr** [comment] 2018-09-25 07:01
@glouel when I try your latest release on Mojave I get a warning "You cannot use the Aerial screen saver on this version of macOS. Please contact the vendor to get a newer version of the screen saver." Any ideas?

**Comment by glouel** [comment] 2018-09-25 10:49
> @glouel when I try your latest release on Mojave I get a warning "You cannot use the Aerial screen saver on this version of macOS. Please contact the vendor to get a newer version of the screen saver." Any ideas?
> 
> Edit: Nevermind, tracked it down to #487

To be clear, does it work for you now ? It should work on the latest builds of Mojave.

**Comment by glouel** [comment] 2018-09-25 16:15
So I'm putting one more beta here. This one addresses a couple of things, and is mostly for those who have Macs older than Late 2015 (see 
https://github.com/JohnCoates/Aerial/issues/505 ). If you install it on top of a previous beta, please go into Cache and set your Video Format to the one you wish to use to avoid redownloading videos. I set the default to 1080p H264 (the most compatible one). There's a help button with more info on what to use. 

<img width="841" alt="capture d ecran 2018-09-25 a 18 00 42" src="https://user-images.githubusercontent.com/37544189/46027645-a81ca880-c0ee-11e8-801b-67721a7ec81c.png">

Build here : 
https://github.com/glouel/Aerial/releases/download/1.4b7/Aerial.saver.zip

**Comment by jridder** [comment] 2018-09-25 22:18
The Done button works in 1.4b7!!

**Comment by quavoce** [comment] 2018-09-26 10:20
@glouel  Feature request - would it be possible to optionally allow the video description to remain showing rather than fading off after a few seconds please? I often miss the start of the videos but would still like to know where each location is. 
Thanks!

**Comment by glouel** [comment] 2018-09-26 12:32
> @glouel Feature request - would it be possible to optionally allow the video description to remain showing rather than fading off after a few seconds please? I often miss the start of the videos but would still like to know where each location is.
> Thanks!

There you go : 

<img width="737" alt="capture d ecran 2018-09-26 a 14 29 08" src="https://user-images.githubusercontent.com/37544189/46079978-eb335600-c198-11e8-9318-9e6124e8fbe0.png">

https://github.com/glouel/Aerial/releases/download/1.4b8/Aerial.saver.zip

**Comment by quavoce** [comment] 2018-09-26 13:42
Superb!!! Thank you very much @glouel !!

Lots of work colleagues keep gawking at these amazing aerial videos on my laptop (especially the earth ones), and it's thanks to your efforts they work really well with no more bugs on my Mojave build. I really like the ability to display a different video on each screen too! It's all very distracting so really must get back to doing actual work. :)

**Comment by brainguynyc** [comment] 2018-09-26 14:44
Sorry but I don't have the "always" option next to "show descriptions" :-(

**Comment by glouel** [comment] 2018-09-26 14:49
Hehe thanks @quavoce  ;) I really enjoy those space videos so it was fun adding them back !

There are still a few things that needs to be addressed, hopefully we can put some roadmap and better track bugs after we get a new maintainer. 

Some random thoughts about my implementation :
- In order to add H264, there's one Honk Kong video that is now ignored. This particular video isn't available in H264 in the JSON, only in HEVC, and because of the internals of the video list, I had to remove it for everyone (can't have a video missing for one format).
- I have a branch that brings back tvOS11 4K screensavers. Sad thing is, and I should have checked before... they are nearly all in the tvOS12 JSON already 😅 There's one desert video (and I don't remember the other one) that aren't included in the tvOS12 JSON. Because it was a quick hack and it didn't bring much, I didn't push that branch. If the video list gets fixed (see above), we could also add back the tvOS10 videos (the originals). Those are 1080p H264 only though.
- I'm pretty sure that even on my Late 2015 iMac 5K (Intel Skylake with AMD GPU), AVKit uses Intel's iGPU fixed function hw decoding (aka QuickSync) for H264, as I saw this on the console : 
`GVA info: Successfully connected to the Intel plugin, offline Gen9 `
I assume it is also used for HEVC too in my case (although I didn't see any such message on console).  
- Some discrete AMD GPUs also have H.264 and HEVC decoding, but not all of them. In my case (M2XX, Tonga), that generation only has UVD 5.0 with H.264 hw decoding, but not HEVC. HEVC came with Polaris (the 400/500 series on laptops). 
- Knowing what gets used will probably be pretty important in order to track bugs/crashes in the future (see https://github.com/JohnCoates/Aerial/issues/468 which I couldn't reproduce after a few hours of playback on my very old Sandy Bridge 2011 Macbook Air). I don't know if we can know either what is available, or what is used through an API, or if we'll have to do guesswork. Some interesting cases would be the iMac Pro (no IGP, but modern AMD GPU with H.264/HEVC decoding, which I assume is used there) or the old Mac Pros (no IGP, probably only H.264 decoding ?). 
- I'm pretty sure we're streaming when we shouldn't, probably on the control panel. There were a few issues raised about that, I think some cleanup around that is needed. I also added a (hidden/non implemented) checkbox to disable all streaming.
- Full Offline mode should be easy to add, but will need some serious rejiggering of the manifestloader though. 
- A fade in/out for videos would be coo tool, someone had a patch but ran into some issues, mostly because in order to implement the fade out, you need accurate duration for the video. This is the kind of thing that may have been fixed in later versions of AVKit/MacOS and will need to be investigated more. 
- We talked with @esetnik about what would be needed for bringing back day/night, and show day/night videos depending on current time (a bit like the dynamic wallpapers on Mojave). That will probably come later though.

**Comment by glouel** [comment] 2018-09-26 14:51
> Sorry but I don't have the "always" option next to "show descriptions" :-(

It's in beta 8 : 
https://github.com/glouel/Aerial/releases/download/1.4b8/Aerial.saver.zip

**Comment by brainguynyc** [comment] 2018-09-26 14:59
> > Sorry but I don't have the "always" option next to "show descriptions" :-(
> 
> It's in beta 8 :
> https://github.com/glouel/Aerial/releases/download/1.4b8/Aerial.saver.zip

Reloaded and voila! Have the option now!

**Comment by standishogrady** [comment] 2018-09-26 21:45
Thanks for the updates, the new space aerials are great.

**Comment by max1mvs** [comment] 2018-09-27 06:47
Great job guys! And thank you so much for your work @glouel – on my Mac it works impeccably. Wow. So great a screensaver to have. I can't fathom why Apple hasn't made this standard on MacOS…

**Comment by vichudson1** [comment] 2018-09-27 12:49
I'm running the new 1.4b8 version and it looks great! Thanks Guys! I did have a thought. I'm a little concerned about enabling the location display to always as it fixes it into the lower corner all the time. It should be changed frequently enough to prevent any burn in I suppose, but to be safe and for aesthetic reasons has anyone considered styling the location display like the floating clock and having it drift around too?

**Comment by esetnik** [comment] 2018-09-27 13:10
@vichudson1 that's a really good point considering this is after all a "screen saver" and shouldn't by definition be causing any additional burn in or uneven wear.

**Comment by glouel** [comment] 2018-09-27 13:16
Ideally, there's a string bundle with the extra descriptions that are shown on the Apple TV. That's one thing I didn't put on my big post up there, it would be a "nice to have" to be able to display those (there's a timecode and a string to be displayed at specific times). I haven't looked into it yet.

Moving the description in the meantime sounds good to me. Maybe something "subtle" like moving from one corner to another every minute or so ?

Side note, starting with 10.13, we can detect if HEVC/H.264 hw acceleration is available, but it doesn't give any detail on the method used. Still better than nothing.

**Comment by glouel** [comment] 2018-09-28 13:12
Thanks to @JohnCoates I pushed the latest build in this repository, you can find it in the releases. Only difference with my own 1.4beta9 build is that this one is signed, should be easier for everyone 🎉

**Closed by glouel** 2018-09-28 13:12 UTC
Labels: enhancement

**Comment by glouel** [comment] 2018-09-29 13:11
If you have a minute check this issue for a test version with the extended descriptions for the space videos : 
https://github.com/JohnCoates/Aerial/issues/512
