### ISSUE TITLE
New Bug in OS X 10.14

### ISSUE THREAD

**Issue by joshers2005** [JohnCoates/Aerial#507] opened 2018-09-27 19:34 UTC
OS X 10.14 Mojave's System Preferences stalls whenever the screen saver options window for Aerial opens. This is because the "done" button does not operate. You can still change the options, minimize the window, and hide the System Preferences app, but the window itself will not close once opened. The only way go back to screen savers is by force quitting System Preferences. Once the System Preferences app has been reopened, the selected screen saver is the previous screen saver chosen before Aerial was selected.

![screen shot 2018-09-27 at 3 27 18 pm](https://user-images.githubusercontent.com/43653949/46170047-b8599280-c26a-11e8-997c-bba757b0e390.jpg)

## Known Issues

Before logging an issue please check if one of the problems you are experiencing is mentioned here. If the issue you are experiencing isn't covered here, then please delete this content and tell us about the problem you are experiencing or the feature you'd like to request.

### "You cannot use the Aerial screen saver with this version of OS X." message

If you get a message saying `You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver.` that is a known bug with macOS that was reported to Apple in April 2016 as [rdar://25569037](http://openradar.appspot.com/25569037). As of November 2017 the bug is still not fixed. To work around the bug:
* select the Aerial screensaver in System Preferences
* close System Preferences with Aerial selected
* reopen System Preferences and the preview should work now

### Mac won't sleep with Aerial as screensaver

If your Mac won't sleep while Aerial is the selected screensaver, then you probably have an older version of Aerial installed. Download the latest verson of Aerial here: https://github.com/JohnCoates/Aerial/releases/ Make sure to check both locations for the old version, it can be installed to `/Library/Screen Savers` and `/User/YOURUSERNAME/Library/Screen Savers`.

### Corrupted playback

If you are getting corrupted playback when the screensaver starts then that is a new bug in macOS High Sierra. It appears to be a problem with the Intel drivers in High Sierra. As a workaround tick the "Show with clock" option as that seems to eliminate the corruption for the moment. Discussed extensively here: https://github.com/JohnCoates/Aerial/issues/377

### No playback

If you are getting a crossed out play icon instead of the preview or the videos just never seem to load, please check that a firewall or proxy isn't blocking the screensavers access to the videos. Trying the following two URLs in a web browser might show if they are blocked. If you are on a Macbook you can also try caching the videos on another network to test whether it is your network provider that is blocking access.
http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov
http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov

**Comment by glouel** [comment] 2018-09-28 10:50
Duplicate of https://github.com/JohnCoates/Aerial/issues/494

See there for a beta with the fix https://github.com/JohnCoates/Aerial/issues/463#issuecomment-424697712

**Comment by glouel** [comment] 2018-09-28 13:20
https://github.com/JohnCoates/Aerial/releases/tag/v1.4beta9

**Closed by glouel** 2018-09-28 13:20 UTC
