### ISSUE TITLE
Screen freeze

### ISSUE THREAD

**Issue by tabreck** [JohnCoates/Aerial#321] opened 2017-02-12 22:29 UTC
Great screen saver. I've noticed that fairly frequently Arial will freeze after switching to a new video. It will run as normal but eventually the new video will not start. Just an image. It will no longer "fly" so to speak. After waking up the screen, and letting Arial start again, or, starting it manually, it runs fine but will eventually freeze again. It's not on any particular video. I'm using a late 2011 iMac 21" screen running Sierra. I have 16gb of storage. I have done restarts just to be sure there are no issues lurking. Any ideas?

**Comment by alistairmcmillan** [comment] 2017-02-12 22:43
It's a known issue. Closing as duplicate of #278.

**Closed by alistairmcmillan** 2017-02-12 22:43 UTC
