### ISSUE TITLE
Aerial screensaver starts off smooth but gets choppy after a few minutes

### ISSUE THREAD

**Issue by amcohen4** [JohnCoates/Aerial#428] opened 2017-11-30 17:53 UTC
MacOS 10.13.1 macmini 2012 16GB 2.3 GHz Intel Core i7 Intel HD Graphics 4000 1536 MB.
Aerial screensaver showing 2 different views on 2 monitors starts off with beautiful smooth motion, but after a few minutes, gets choppy/jerky. It's like a lag for a second. I have all views cached too.

**Comment by alistairmcmillan** [comment] 2017-12-02 01:42
@amcohen4 Does ticking the "Show with clock" option help?

**Comment by amcohen4** [comment] 2017-12-02 05:20
I always had set show with click to on.

**Comment by amcohen4** [comment] 2017-12-02 06:19
Here's some before and after videos

Starts out good:


Minutes later gets choppy:

**Comment by dubyasqrd** [comment] 2017-12-27 16:51
just noticing this same issue with the upgrade to MacOS 10.13.2...

**Comment by skiin4kicks** [comment] 2018-02-20 02:07
Having the same issue, playback starts smooth then becomes choppy after a few minutes. Currently on Mac OS High Sierra 10.13.3

**Comment by andreineculau** [comment] 2018-02-26 08:53
Interestingly (not) but for me ticking the `Show Clock` really smoothens everything.

**Comment by iomegadrive** [comment] 2018-03-19 20:15
Same experience here. 

1. Scaled display (1680x1050).
2. With "Show Clock" option disabled, there are top and bottom bars of the video and the middle portion of the video is zoomed in.
3. With "Show Clock" enabled, clock is the first thing to display and then the video appears as intended with no zoom or choppiness.

**Comment by larriebee** [comment] 2018-04-16 19:58
I'm not sure if this is the same issue you have are experiencing but this is what mine looks like about 3 seconds after the screensaver is active

![img_0919](https://user-images.githubusercontent.com/3204878/38831974-f16b92e0-41b8-11e8-8233-288cc1ffec05.JPG)

**Comment by skiin4kicks** [comment] 2018-04-16 22:26
No, I haven’t seen this yet although this looks more GPU related. Not sure

**Comment by funfried** [comment] 2018-04-19 09:44
@larriebee I had the same issue, try to turn on the clock in the screensaver settings (don't ask why, but it seems to help)

**Comment by mokwai** [comment] 2018-06-09 07:17
@larriebee: I had the same issue on MacBook (after a split-second of showing aerial - same scrambled picture) -> when I  ticked "Show with clock" - it works - no issues 
![image](https://user-images.githubusercontent.com/3527795/41188886-dee77c36-6c08-11e8-903d-77fc34012382.png)

MacOs 10.13.5

**Comment by fredrivett** [comment] 2018-08-03 10:37
Same issue here, and as @mokwai says, ticking `Show with clock` fixes it, but adds a damn ugly clock to the screensaver, which kinda ruins it. No commits on this repo since Jan, lets hope it gets resurrected.

**Comment by diegopamio** [comment] 2018-08-07 16:47
Indeed the `show with clock` fix it, but I agree there should be another solution as well.

**Comment by glouel** [comment] 2018-10-14 10:14
To those who still experience lag issues, can you give this build a try : 
https://github.com/glouel/Aerial/releases/download/1.4.1test4/Aerial.saver.zip

This should fix issues in 10.13 particularly (10.14 seemed ok in stable 1.4). Also note that iCloud Photos sync can launch while your screensaver runs, part of it is a file converting service (JPEG to HEIF I guess, probably videos too) which can make video playback massively lag.

**Comment by amcohen4** [comment] 2018-10-16 20:28
Thanks .. Looks great so far (Mohave, later 2012 mac mini, dual 1080p monitors).

**Comment by NightRaider73** [comment] 2018-10-20 21:28
@glouel 
This is fixed in 1.4.1.
 But if you are still having this problem try 1.4.2 beta1: 
https://github.com/JohnCoates/Aerial/releases/download/v1.4.2beta1/Aerial.saver.zip

**Closed** 2018-10-20 21:29 UTC

**Comment by dubyasqrd** [comment] 2018-10-25 14:11
Hello--

I'm still having issues with playback being choppy with or without the
clock. Running the latest version of Mojave on a Mac mini Server (Late
2012) with a Core i7 and Intel Graphics 4000/  Using 1.4.2. beta1.

Thank you - love having this available.

Wesley

**Comment by glouel** [comment] 2018-10-25 14:17
@dubyasqrd 
First, can you try latest version ? See here : 
https://github.com/glouel/Aerial/releases/download/v1.4.4test2/Aerial.saver.zip

A few issues have been fixed since that beta including that may have contributed to choppiness (especially if you streamed videos). 

Then, if it's still choppy, will need more details: 
- Is it always choppy from the start or just gets choppy at some point ?
- Are videos cached ? 
- Multimonitor ? If so which mode ?
- Are you using 1080p H264 as prefered video format ?

One other factor, iCloud Photo Syncing can start when the screensaver is on and slow down massively video playback, that's described in the troubleshooting section.

**Comment by TurboAsterix** [comment] 2019-11-08 14:43
I have exactly the same issue on a Mac Mini Late 2012 with 16 GB RAM and 500 GB Samsung 850 Evo SSD. This occurred both with Mojave and Catalina 10.15.1.

- Is it always choppy from the start or just gets choppy at some point ?
It get's choppy after **exactly** 5 min of playback.

- Are videos cached ?
Yes, H264 videos all cached. Cached or stream does not show any change. 

- Multimonitor ? If so which mode ?
Yes, play on All Display, Mirrored, Fill Screen.
Changing those settings does not have any effect on the choppy playback. It always gets stuttering after 5 min. Even disabling one of the displays and leaving it just black and playing the video only on the main display still produces the stuttering after exactly 5 min. 

- Are you using 1080p H264 as prefered video format ?
Yes

I tried increasing the process priority of the Vtdecoderxpcservice with renice, disabling Time Machine, Spotlight, killing iCloud Photo Analysis etc. All this does have no effect at the stuttering always again occurs after exactly 5 min. If it would be a system resource bottleneck, then definitely playing only the video on one display instead of two should have massively reduced the system load. I am not convinced that it is a CPU/GPU/disk/network resource issue. 

The Aerials trace file does not show anything useful, except that it started the Animation. 

Enabling the Mac OS based screensaver system clock (in Mac OS setting, not in Aerials settings) does not change anything. I had stuttering after a while too on a Macbook Pro 13 inch Mid 2012, here enabling the Mac OS based clock fix the issue.

The Mac Mini has a Core i5" (3210M) CPU with Intel HD Graphics 4000, then MacBook Pro as basically same CPU and same integrated Graphics. 

Other system standard screensavers like Arabesque show similar behaving.
Too me this looks overall like a strange Mac OS bug since later Mojave versions affecting the Mac Minis. 

Best regards,
TurboAsterix

**Comment by jesmcs** [comment] 2020-01-10 15:22
I am using a _MacBook Pro (15-inch, Mid 2010) 2.66 GHz Intel Core i7 8 GB 1067 MHz DDR3 Samsung SSD NVIDIA GeForce GT 330M 512 MB_ and _Intel HD Graphics 288 MB_ with _High Sierra._  I was experiencing problems with "Ariel" screensaver. I have it set to 1080p H246. The video would not play smoothly. It progressed by jumping several frames every few seconds. I tried changing setting on the screensaver parameters to no avail. I then looked at the CPU drivers that are running on my system. As you can see from above there are two; NVIDIA GeForce GT 330M 512 MB_ and _Intel HD Graphics 288 MB. It has been a few years since I added the NVIDIA driver so I checked to see which of the two was active. It turned out that both worked in turn to maximise CPU efficiency. This is controlled via the Energy Saver settings, 
<img width="509" alt="image" src="https://user-images.githubusercontent.com/59737588/72163221-54a19d00-33bb-11ea-9e81-210587636718.png">
I un-ticked the box that the red arrow points to (below) which activates only the high performance graphics driver. 
<img width="509" alt="Untickbox" src="https://user-images.githubusercontent.com/59737588/72164047-e65dda00-33bc-11ea-9f44-a109929a1da0.png">
After I did this, the screensaver ran smoothly.

**Comment by glouel** [comment] 2020-01-10 16:22
Hi @jesmcs !

> I am using a _MacBook Pro (15-inch, Mid 2010) 2.66 GHz Intel Core i7 8 GB 1067 MHz DDR3 Samsung SSD NVIDIA GeForce GT 330M 512 MB_ and _Intel HD Graphics 288 MB_ with _High Sierra._ I was experiencing problems with "Ariel" screensaver. I have it set to 1080p H246. The video would not play smoothly. It progressed by jumping several frames every few seconds. I tried changing setting on the screensaver parameters to no avail. 

So that's an Arrandale CPU with a Gen5 graphics (Ironlake). That one had basic H.264 acceleration, it wasn't fully decoded in hardware and possibly buggy if memory serves. First gen with Quick Sync was the next one (Sandy Bridge) : https://en.wikipedia.org/wiki/Intel_Graphics_Technology#Gen5

> I then looked at the CPU drivers that are running on my system. As you can see from above there are two; NVIDIA GeForce GT 330M 512 MB_ and _Intel HD Graphics 288 MB. It has been a few years since I added the NVIDIA driver so I checked to see which of the two was active. It turned out that both worked in turn to maximise CPU efficiency. This is controlled via the Energy Saver settings,
> <img alt="image" width="509" src="https://user-images.githubusercontent.com/59737588/72163221-54a19d00-33bb-11ea-9e81-210587636718.png">
> I un-ticked the box that the red arrow points to (below) which activates only the high performance graphics driver.
> <img alt="Untickbox" width="509" src="https://user-images.githubusercontent.com/59737588/72164047-e65dda00-33bc-11ea-9f44-a109929a1da0.png">
> After I did this, the screensaver ran smoothly.

Ok so, my best guess is that with the box unchecked, you were running video decoding on the Intel integrated graphics that has bare bone H.264 decoding which macOS may or may not use. 

I would suggest reenabling graphics switching and trying to open one of the cached videos in Quicktime. What you get with Aerial should be the same as what you get with Quicktime. You can open `Activity Monitor` then. 

On the Intel graphics, you will probably see a `VTDecoderXPCService` in `Activity Monitor` pegging your CPU and that's why it lags (lack of hardware decoding). By disabling the graphics switching (and forcing the GeForce 330 as always on), Quicktime/Aerial is using your GeForce's hardware decoding unit (NVDEC) to playback the video and that should result in a much lower CPU usage in `Activity Monitor`. 

I hope that makes sense ? Your solution is the correct one in any case, by disabling graphics switching you should get better performance for all video playbacks, including Aerial.
