### ISSUE TITLE
seems like it does not work with sierra

### ISSUE THREAD

**Issue by tolgaguver** [JohnCoates/Aerial#289] opened 2016-12-28 08:04 UTC
Hi, 

I'm using Sierra version 10.12.3 Beta. and when I select the aerial screensaver it says 

'You cannot use the Aerial screen saver with this version of macOS. please contact the vendor to get a newer version of the screen saver'

thanks,

**Comment by alistairmcmillan** [comment] 2016-12-28 08:06
It's a bug in OSX/macOS.

The screensaver itself should launch and run okay.

The bug should just affect the preview in System Preferences. If you select Aerial, close System Preferences, then re-open System Preferences, you should find that the preview works okay.

Closing as a duplicate of #269 .

**Closed by alistairmcmillan** 2016-12-28 08:06 UTC
