### ISSUE TITLE
Online Sources not respecting custom cache location

### ISSUE THREAD

**Issue by brian163** [JohnCoates/Aerial#1135] opened 2020-11-23 01:34 UTC
#### General troubleshooting tips

Before logging an issue please check that:
- [X ] You have the latest version installed [**2.1.5**] (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [X] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [X] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [X] Mac model: Mac Pro Tower
- [X ] macOS version: 10.14.6
- [X] Monitor setup: Two displays

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

For "Custom Sources/Community Videos", the movie files from Josh & Hal respected (properly utilized) the custom folder selection of "Cache/Manually pick the cache location" along with Aerial's own videos. 

However, when I purchased and installed the Magic Window Air Expansions as an Online Source, these videos download to my ~/Library/Application Support/Aerial folder in ./Cityscapes Air, ./Countryside Air, ./Naturescapes Air sub-folders respectively, instead of to my manually selected cache location.

Face value, I'd suggest all Custom Sources should utilize the manually selected cache location, even if the sub-folders need to be created there, unless it was documented otherwise. 

As it stands, is there a proper way for me to manually move the videos to my selected cache location? I'm assuming just copying them to the root of the cache file may mess things up. And I don't know if Aerial will even recognized movie files in sub-folders in the selected cache location?

Any suggestions for doing this properly would be appreciated. I know the the files from this particular collection are significantly smaller than some of the others that accompany Aerial. However, it's about 4GB and they have a Big Sur collection forthcoming. So with a free space constrained PCI card based SSD boot drive, I'd very much prefer to be able to store them on my external disk.

**Comment by brian163** [comment] 2020-11-23 02:27
I'm also wondering if this is effecting the "Cache/Make Time Machine ignore the cache" option. If this option is on, should you see the related cache path(s) included in the "Time Machine/Options.../Exclude these items from backups:" list? Or is this exception being written to a Time Machine config file somewhere else and they do not appear there? (I am aware that Time Machine has various "back end" config file(s) for things like default exclusions.)

Also, not looking to post one issue under another but I am seeing odd behavior with this TM ignore the cache option. For example, if I try to disable it, then click the Aerial close button, quit System Preferences and reload, the selection is magically enabled again. I can't see to get disabled to "stick".

**Comment by glouel** [comment] 2020-11-23 14:06
Hey there

> As it stands, is there a proper way for me to manually move the videos to my selected cache location? I'm assuming just copying them to the root of the cache file may mess things up. And I don't know if Aerial will even recognized movie files in sub-folders in the selected cache location?

Right now, nope. Since moving the cache is no longer supported on Big Sur and Catalina because of macOS restrictions, I didn't think of this particular use case. 

I did put back that option for older systems but it has a few rough edges, including this which I didn't think of. 

> I'm also wondering if this is effecting the "Cache/Make Time Machine ignore the cache" option. If this option is on, should you see the related cache path(s) included in the "Time Machine/Options.../Exclude these items from backups:" list? Or is this exception being written to a Time Machine config file somewhere else and they do not appear there? (I am aware that Time Machine has various "back end" config file(s) for things like default exclusions.)

So it doesn't show in the time machine UI list, no. However you can check whether it's excluded or not by running in terminal:

`tmutil isexcluded /your/path`

It goes like this and says Excluded if it is in front of the path you passed (example here on Big Sur with the container path) : 

```
glouel@iMac-de-Guillaume-2:~$ tmutil isexcluded "/Users/glouel/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/Cache"
[Excluded]    /System/Volumes/Data/Users/glouel/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/Cache
```

The way it works is that Aerial runs that command with the cache path, and that determines whether the checkbox is checked. If it's checked in the UI, it's excluded. 

> Also, not looking to post one issue under another but I am seeing odd behavior with this TM ignore the cache option. For example, if I try to disable it, then click the Aerial close button, quit System Preferences and reload, the selection is magically enabled again. I can't see to get disabled to "stick".

So it's possible that again there's an issue here with manually picked cache. A log of you trying to uncheck may tell me a bit more, because I double checked here and it works as intended, and the code "looks" correct even for a manually specified cache. 

One thing that can happen is you have excluded a path above it. Say you store in `/Users/Shared/Aerial`, use the TM exclusion in Aerial, that will exclude that exact path. But if you for some reason excluded `/Users/Shared/`, the UI will still say it's excluded because it is, even if Aerial didn't put the exclusion there, and Aerial won't be able to remove it. Does that make sense ? 

You may have some sort of issue if you say put the videos on a separate disk that's excluded from time machine. In that case the checkbox will stay checked. It's a bit weird but that's how time machine exclusions work in practice.

**Comment by brian163** [comment] 2022-01-23 01:06
I'm excited to note this is now possible (and works) with 3.x. After changing the path in settings, re-starting the control panel for the new path to be provisioned/recognized, I then copied (moved) -all- of my cached content to the new folders on my external disk (to avoid a complete re-download), and then did a refresh/download to update the individual sources. After I observed a new expansion pack installing to the new path I was confident it was working. So I quit everything, deleted the now duplicate content from  ~/Library/Applications Support/Aerial folder contents, and re-started.

I just recovered a good chunk of space from my SSD boot drive. Thanks @glouel !!!

**Closed** 2022-01-23 01:06 UTC

**Comment by brian163** [comment] 2022-01-23 01:16
I just wanted to add that while it sort of reads on the 3.0 feature overview that this is a change for Monterey, it also worked for me under Mojave. (I believe Monterey "broke" this feature originally, however, the additional improvement of it working for all online sources isn't just for Monterey.)
