### ISSUE TITLE
Screensaver not showing full screen 

### ISSUE THREAD

**Issue by super911** [JohnCoates/Aerial#871] opened 2019-10-13 21:33 UTC
Running macbook pro 2018 13" with Catalina and Aerial 1.6.2. Not running any external monitors.

Some videos do not run full screen and only appear in the lower left hand corner of the screen.. Sometimes the same video runs fine.. All videos selected are downloaded and in the cached folder.  Log and screenshot of issue attached. Is this a known issue? Thanks!

![aerial](https://user-images.githubusercontent.com/23323140/66722745-1f46dc80-edd7-11e9-84dc-bcf0f0b12278.jpg)
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3722500/AerialLog.txt)

**Comment by glouel** [comment] 2019-10-13 21:52
Hey @super911 

That's... wild ! Definitely haven't seen that bug yet. I'll have a look at your log tomorrow, but just to try and get a better idea, does Aerial start that way and keep playing that way ? Or does it switch from one video to another ? 

Thanks for the report in any case I'll get back to you.

**Comment by super911** [comment] 2019-10-13 22:01
" does Aerial start that way and keep playing that way ? Or does it switch from one video to another ?"

Yes its pretty crazy. Never had this issue with the same hardware. It appeared with Catalina and the new version of Aerial. It seems to start that way and will continue looping that same video without changing to another.

**Comment by glouel** [comment] 2019-10-14 11:31
@super911 

So I did check your log, I tried to parse through the last couple of days but I don't see anything obviously wrong there being reported. 

Aerial gets told by system how large it's view has to be, to give you an example :
> 2019-10-13 16:25:34 : avInit1 (0.0, 0.0, 1440.0, 900.0)

(so that's your screen size in "points")

And after a bit of monitor detection stuff you see this output: 

> 2019-10-13 16:25:34 : <AerialView: 0x7fdb2e80ab70> setting up player layer with bounds/frame: (0.0, 0.0, 1440.0, 900.0) / (0.0, 0.0, 1440.0, 900.0)

This is where I decide how large the view should be. I didn't find an instance where that size was wrong, so it's probably something else happening. 

I can see a few `(0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)` in your log too, but that's the tiny preview you see in that screen: 

![Capture d’écran 2019-10-14 à 13 01 44](https://user-images.githubusercontent.com/37544189/66746722-db111600-ee82-11e9-9f37-0bb474989fd8.jpg)

I'm going to throw some random stuff out there, please answer what you can: 

- Can you confirm your settings in Displays tab (something like : All displays, Independent, Fill Screen ?)

- Did you disable all the text features (so no text displaying at all ? I don't see a clock or a description on your screenshot) ?

- Eyeballing it, would you say the tiny thing you see on your screen when the bug happens is the same size as the one in the box (in syspref from screenshot above) on your system ? Or is it larger ?

- Do you happen to keep System Preferences open all the time ? 

- Do you sometimes connect an external monitor or never ? Do you use some sort of 3rd party software for your screen management if so ?

- Frequency of it happenning/not happening (roughly) ?

- https://support.apple.com/kb/SP775?locale=en_US you got this mac correct ? With Intel Iris Plus Graphics 655 ?

- Can you enable the clock in Aerial's Text tab (with show seconds, and pick Always show at the top of that window). Does that fix ? If that does not, does the clock show in tiny text on top of the tiny video, or normal sized in a corner ? 

- Can you enable the clock here : 
![Capture d’écran 2019-10-14 à 13 16 13](https://user-images.githubusercontent.com/37544189/66747487-faa93e00-ee84-11e9-90fd-88ccbf35fc17.jpg)
Checking the box I circled ? When you do that and the bug happens, is the clock showing somewhere on your whole screen, or just in the tiny video rectangle ?

- Last resort, can you note the exact time a bug happens and paste the log from that run (it starts with avInit1) ?

I know it's a lot but thanks for your help. If I had to make a rough guess, I could see maybe a video driver corruption issue if you disabled all text. There's been recurring bugs with the Intel driver if you just play a video with no text at all, although usually it just corrupts the whole screen. 

I supposedly have a workaround in place that works though (that's this line you see in logs `2019-10-13 16:26:09 : Using dot workaround for video driver corruption`) but maybe my workaround sometimes fails for some systems in Catalina ? This was a high sierra bug but it came back in Catalina beta so I reenabled that workaround for everyone now. 

Usually enabling one of the clocks fixed that bug by forcing something else than a video to be displayed (the workaround adds a faint dot in a corner to trick the driver).

Let me know what you can.

**Comment by super911** [comment] 2019-10-14 12:52
> * Can you confirm your settings in Displays tab (something like : All displays, Independent, Fill Screen ?)
Setting is: Play Aerials on All Displays, Independent, Fill Screen
> * Did you disable all the text features (so no text displaying at all ? I don't see a clock or a description on your screenshot) ?
Yes, all text features are disabled
> * Eyeballing it, would you say the tiny thing you see on your screen when the bug happens is the same size as the one in the box (in syspref from screenshot above) on your system ? Or is it larger ?
I would say the size when the bug happens is very close to the size in syspref, although the one on the display just might be a bit larger
> * Do you happen to keep System Preferences open all the time ?
no system preferences is closed when the issue occurs
> * Do you sometimes connect an external monitor or never ? Do you use some sort of 3rd party software for your screen management if so ?
I never connect a external monitor, no 3rd party software for screen management
> * Frequency of it happenning/not happening (roughly) ?
it happens roughly 50-60% of the time
> * https://support.apple.com/kb/SP775?locale=en_US you got this mac correct ? With Intel Iris Plus Graphics 655 ?
Yes that is correct model
> * Can you enable the clock in Aerial's Text tab (with show seconds, and pick Always show at the top of that window). Does that fix ? If that does not, does the clock show in tiny text on top of the tiny video, or normal sized in a corner ?
When I do this, the text of the saver including the clock appears more or less in the middle of the small thumbnail and the issue can still be reproduced.
> * Can you enable the clock here :
>   ![Capture d’écran 2019-10-14 à 13 16 13](https://user-images.githubusercontent.com/37544189/66747487-faa93e00-ee84-11e9-90fd-88ccbf35fc17.jpg)
>   Checking the box I circled ? When you do that and the bug happens, is the clock showing somewhere on your whole screen, or just in the tiny video rectangle ?
When I enable the clock using the "show with clock" option I CANNOT reproduce the issue, the screensaver seems to run fine.
> * Last resort, can you note the exact time a bug happens and paste the log from that run (it starts with avInit1) ?
> I do see the screen flicker just a bit (.25 seconds or so)  (red/yellow) just before the thumbnail size bug appears. When it plays normally I dont see it flicker if the screensaver plays normally.

In any case I reproduced the issue and it is the last play of the saver in the log at 7:44:42 or so
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3724484/AerialLog.txt)

> I know it's a lot but thanks for your help. If I had to make a rough guess, I could see maybe a video driver corruption issue if you disabled all text. There's been recurring bugs with the Intel driver if you just play a video with no text at all, although usually it just corrupts the whole screen.
> Thanks for the help, I will enable the system clock as that appears to be the only successful workaround for me at this time.  Let me know if you need any more info I'm happy to help.
> I supposedly have a workaround in place that works though (that's this line you see in logs `2019-10-13 16:26:09 : Using dot workaround for video driver corruption`) but maybe my workaround sometimes fails for some systems in Catalina ? This was a high sierra bug but it came back in Catalina beta so I reenabled that workaround for everyone now.
> Yes, I never had the issue with the same hardware and settings prior to Catalina.

> Usually enabling one of the clocks fixed that bug by forcing something else than a video to be displayed (the workaround adds a faint dot in a corner to trick the driver).
> 
> Let me know what you can.

**Comment by glouel** [comment] 2019-10-14 13:05
@super911 

> it happens roughly 50-60% of the time
> Yes that is correct model
> When I do this, the text of the saver including the clock appears more or less in the middle of the small thumbnail and the issue can still be reproduced.

Ok I guess that explains why my workaround doesn't work for you. Looks like a slightly different version of that old bug (enabling the system clock was the old workaround I used to suggest back in High Sierra).

> When I enable the clock using the "show with clock" option I CANNOT reproduce the issue, the screensaver seems to run fine.

Oh, Catalina... 

> I do see the screen flicker just a bit (.25 seconds or so) (red/yellow) just before the thumbnail size bug appears. When it plays normally I dont see it flicker if the screensaver plays normally.

Sounds definitely like a driver bug again. Even the video driver for my late iMac 2015 is frequently unstable with playing HDR videos (they slow down to a crawl sometimes, which is much better than the betas which would slow down the whole system for 2 minutes). 

Which reminds me, I didn't ask, you have HDR enabled ? If so, can you check if disabling HDR makes the bug unreproducible (without the clock too) ? 

> In any case I reproduced the issue and it is the last play of the saver in the log at 7:44:42 or so
> [AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3724484/AerialLog.txt)

Ok definitely confirms it "looks" fine from the log point of view.

> Thanks for the help, I will enable the system clock as that appears to be the only successful workaround for me at this time. Let me know if you need any more info I'm happy to help.

If you can, please check the HDR thing. Thanks for following up quickly !

**Comment by super911** [comment] 2019-10-14 13:10
I do NOT have HDR enabled,  settings are just 1080P HEVC, no HDR. Thanks

**Comment by glouel** [comment] 2019-10-14 13:15
Ok I guess it's a more general bug then ! Hopefully it may get fixed in the next Catalina point update. I suggest you try disabling the clock when one comes to see if they fixed it. 
Thanks !

**Comment by glouel** [comment] 2019-10-14 15:09
> After I updated to Catalina, I had the same problem with my macbook pro 2016 13" .

Hey @huangduo-CD, thanks for confirming. That's an Intel graphics laptop too which seems to confirm the driver thing. 

Enabling the (system) clock did fix for you too I assume ?

**Comment by huangduo-CD** [comment] 2019-10-14 15:31
Hey @glouel, thank for replying. After I activate it, it can be displayed in full screen, but the video is paused and not played.

**Comment by glouel** [comment] 2019-10-14 15:37
> Hey @glouel, thank for replying. After I activate it, it can be displayed in full screen, but the video is paused and not played.

Ok good first step ! 

Are your videos cached ? Videos being paused is usually because you are trying to stream videos. Please try to cache a few videos and try again. To do that, click the + button to download a particular video of your choice (it may take a while depending on your network connexion, some are huge). When done (there's a progress indicator), click the other thing I circled at the bottom, and select "Check only cached videos".

![Capture d’écran 2019-10-14 à 17 34 02](https://user-images.githubusercontent.com/37544189/66763997-3655ff00-eea9-11e9-9c8f-4c4742251b1a.jpg)

**Comment by huangduo-CD** [comment] 2019-10-14 15:53
@glouel  All fixed, even if I turn clock off. Thanks!

**Comment by jkoepcke** [comment] 2019-10-16 12:22
Can confirm this happens to me as well, 2018 MBP with Intel Graphics. Turning on the clock doesn't help. All videos are cached (4K HEVC HDR only). I can also confirm that it's not related to the video itself. The same video sometimes plays fullscreen, sometimes not.

**Comment by glouel** [comment] 2019-10-16 12:48
@jkoepcke did you enable the system clock or Aerial's one ? It looks like you need system's clock. This one in red : 

![Capture d’écran 2019-10-14 à 13 16 13](https://user-images.githubusercontent.com/37544189/66747487-faa93e00-ee84-11e9-90fd-88ccbf35fc17.jpg)

**Comment by jkoepcke** [comment] 2019-10-16 13:02
You are right, my bad - the system clock helps.

**Comment by super911** [comment] 2019-10-17 15:40
This looks to have been fixed for me with the latest Catalina update

**Comment by glouel** [comment] 2019-10-17 15:43
> This looks to have been fixed for me with the latest Catalina update

The latest Catalina beta you mean ? Awesome in any case 👍

**Comment by super911** [comment] 2019-10-17 15:45
It said there was a system update available yesterday and I installed it. I'm not sure how to check if it was a beta or not. It still says Catalina 10.15.  Yep happy I no longer need the system clock workaround. Thanks for the help

**Comment by glouel** [comment] 2019-10-17 19:13
Unless you are a developper and explicitly opted in in the beta program, not a beta ! There was a new beta tonight but your update came before so looks like it's a regular update (possibly a driver update only for some Macs, they tend to do that).

**Comment by dfevre** [comment] 2019-10-22 03:02
I have this issue too. Updated to Catalina and Aerial 1.6.2 on a MacBook Pro 2017. About every second time the video is small. Adding the clock doesn't help.

**Comment by glouel** [comment] 2019-10-22 07:12
@dfevre did you install the latest updates for Catalina ? There was one yesterday but last week's update seemed to have fixed it for most people : https://9to5mac.com/2019/10/21/apple-supplemental-update-macos-catalina/

The clock workaround requires the system clock to be used, not Aerial's clock. This one I circled in red : 
![Capture d’écran 2019-10-14 à 13 16 13](https://user-images.githubusercontent.com/37544189/66747487-faa93e00-ee84-11e9-90fd-88ccbf35fc17.jpg)

So far it worked for everyone. Can you check again if you have latest Catalina updates and that specific box checked ?

**Comment by super911** [comment] 2019-10-22 14:19
I can confirm the latest catalina did NOT fix my original issue. However, the system clock workaround continues to be the only option that works for me.

**Comment by dfevre** [comment] 2019-10-22 23:34
@glouel According to Software Update my system is up to date.
<img width="780" alt="Screen Shot 2019-10-23 at 10 28 41 am" src="https://user-images.githubusercontent.com/1924643/67343178-3bd5d800-f580-11e9-975e-43fc8b71fef5.png">
I turned on the clock using the option in your image above. It works some of the time but sometimes the video is small and in the bottom-left corner.

**Comment by glouel** [comment] 2019-10-23 08:49
> @glouel According to Software Update my system is up to date.

Ok !

> I turned on the clock using the option in your image above. It works some of the time but sometimes the video is small and in the bottom-left corner.

Hmm. Can you tell me a bit more about your MacBook Pro 2017 ? There are some models with two GPUs, an Intel and an AMD one. So far the bug/fix was specific to Intel only GPUd Macs. Could be it's a little more complex than that on some systems maybe if there's some switching involved.

**Comment by jkoepcke** [comment] 2019-10-23 12:08
Can confirm the described behaviour for me as well. System clock turned on, latest Catalina, 2018 MBP. It's much less than with the system clock off, but still happens from time to time.

**Comment by glouel** [comment] 2019-10-23 12:14
@jkoepcke was it this way prior to the update too ? Looked better but from time to time still fails ? Or did the latest update make it worse ?

I guess I thought the clock 100% fixed it but if it fixes it like 95% of the time, that's... even weirder. I'm not sure there's much I can do here on this one :(

**Comment by jkoepcke** [comment] 2019-10-23 12:21
Well I can't really tell if the updated changed anything, since my last message it happened only 2 times out of many, but both after the update. Without the clock it's happening like every third time.

So even though it's still an issue, it's very rare and not a big deal anymore.

**Comment by glouel** [comment] 2019-10-23 12:23
I see, thanks a lot for the explanation !

**Comment by HackettLai** [comment] 2019-10-25 06:53
2019 macbook pro 13inch, OS 10.15

It's happen on me as well

**Comment by dfevre** [comment] 2019-10-27 23:35
> Hmm. Can you tell me a bit more about your MacBook Pro 2017 ? There are some models with two GPUs, an Intel and an AMD one. So far the bug/fix was specific to Intel only GPUd Macs. Could be it's a little more complex than that on some systems maybe if there's some switching involved.

@glouel I've got Intel graphics in this one.
<img width="698" alt="Screen Shot 2019-10-28 at 10 33 52 am" src="https://user-images.githubusercontent.com/1924643/67643731-ab780880-f96e-11e9-8deb-e3ba586f6545.png">

**Comment by super911** [comment] 2019-10-29 21:10
I can confirm with 10.15.1 that the issue is still not fixed. Using the system clock is the only workaround that still works for me.

**Comment by glouel** [comment] 2019-10-29 21:16
> I can confirm with 10.15.1 that the issue is still not fixed. Using the system clock is the only workaround that still works for me.

Thanks for taking the time to let me know ! I'll fill a radar tomorrow, I've had medium luck with that to be fair but who knows !

**Comment by dfevre** [comment] 2019-11-04 04:13
> @dfevre thanks for the confirmation.
> 
> 10.15.1 was just released, hopefully someone who experienced the bug can let me know if they fixed it ?

I updated to 10.15.1 and can confirm that the problem still occurs periodically even with the clock turned on.

**Comment by glouel** [comment] 2019-11-04 11:13
To all, I (finally) filled a radar with Apple this morning about this bug. I will let all of you know if/when I hear back from them, hopefully they will have a look at it (I've had good luck when it comes to graphics bugs with radars, less so with screensaver API ones, so fingers crossed!).

**Comment by RSickenberg** [comment] 2019-12-04 13:39
The bug is still there for the Macbook Pro 16 inches with the Radeon Pro 5500M :-)

**Comment by glouel** [comment] 2019-12-04 13:43
> The bug is still there for the Macbook Pro 16 inches with the Radeon Pro 5500M :-)

Thanks for the heads up @RSickenberg , interesting that it happens on that model too with Radeon. I'm unsure if Apple still does some form of gpu switch on that model or if they just don't use the Intel one. 

Sadly though, I have no update to give on the radar I filled last month. I've updated it with your report though as this may be relevant for them.

**Comment by ravindrank** [comment] 2019-12-05 21:30
Hi,

First of all, Thanks for creating this screensaver and love it. 

I have the same issue. Went thru the thread and tried the workarounds. 
* Turning on clock consistently fixes the issue. 
* Without the clock enabled, happens alternately (eg. screensaver in small window.. next time works normally.. next small window so on so forth)
* Model is A1989 - MacBook Pro (13-inch, 2018, Four Thunderbolt 3 Ports) on 10.15.1
* I did have a monitor connected 2 weeks back but not connected right now.

Thanks and hope this helps you find the root cause.

**Comment by RRGG4** [comment] 2019-12-13 01:24
Bug still exists on my MacBook Pro 13" 2019 running macOS 10.15.2, Any closer to finding the cause of this?

**Comment by glouel** [comment] 2019-12-13 10:43
> First of all, Thanks for creating this screensaver and I love it.

Thanks @ravindrank  !

> Bug still exists on my MacBook Pro 13" 2019 running macOS 10.15.2, Any closer to finding the cause of this?

Hi @RRGG4, see below :

> I have the same issue. Went thru the thread and tried the workarounds.
> 
> * Turning on clock consistently fixes the issue.

So to both, this is the best fix I have for now yep. The bug is in the Intel graphics driver in Catalina, as I mentioned earlier, I filed a radar with Apple but they haven't answered it yet. I would suggest if any of you have a bit of time to launch Feedback Assistant on your mac and fill a radar too about the issue. It does help sometimes to have multiple reports of the same issue to get them to look at it. 

In the meantime, enable the system clock here : 

![Capture d’écran 2019-12-13 à 11 41 58](https://user-images.githubusercontent.com/37544189/70794302-a72c7100-1d9d-11ea-9cbf-b2a347f74110.jpg)

**Comment by RSickenberg** [comment] 2019-12-16 12:09
Hello, good news!
With my 16" Macbook Pro with the Radeon Pro 5500M and macOS 10.15.2 (19C57) I still haven't had the issue.

Best regards and have a great holiday's people :)

**Comment by glouel** [comment] 2019-12-16 12:17
> Hello, good news!
> With my 16" Macbook Pro with the Radeon Pro 5500M and macOS 10.15.2 (19C57) I still haven't had the issue.
> 
> Best regards and have a great holiday's people :)

Hi @RSickenberg !

Thanks for following up on this, you mean without enabling the system clock, right ?

I was wondering, are you primarily running on battery or plugged in ? As far as I understand (I don't have one), the 16" MBP does do switchable graphics between the Radeon and the Intel IGP depending on whether you are on battery or not (and this is something that can be disabled somewhere in the Pref Panel). 

If I understand this issue correctly, this should *only* happen if you are running on the IGP (so probably on battery only). So whether you hit the bug could definitely depend on whether you run on battery or not. If it's fixed for you with 10.5.2, on battery, without the clock enabled, then maybe they fixed it for that mac but not others yet ? 

Thanks in any case, and great holidays to you too !

**Comment by chienlim** [comment] 2019-12-19 04:12
I have the same problem and turning on "show with clock" workaround fixed it, but would like to have a fix for this issue. Thank you in advance.

**Comment by glouel** [comment] 2019-12-19 10:00
@super911 & all, would one of you try this build : https://github.com/glouel/Aerial/releases/download/v1.6.5beta2b/Aerial.saver.zip

It's a bit of a long shot, but I made a couple of changes to the workaround I had in place since High Sierra. I'm now adding a stronger dot on the screen (you can see it in the bottom left corner) before *and* after the video player gets added on screen. I have no idea if this will fix the issue or not for Intel graphics Macs, but that's my best effort for now. 

I still haven't heard from Apple on my radar on the issue, so that's all I can think of right now. 

Please understand also that this is based on a beta I released yesterday, you'll see an empty "Text" tab, settings are being migrated in the new "Info" tab. Some things are missing too ;) 

So please give it a shot, and let me know if it works or not.

**Comment by ravindrank** [comment] 2019-12-19 16:10
Thanks for this one. Just tried this version. Removed the clock setting and tried immediately using preview. Observed the following:
* First time seemed to worked
* On consequent tries, random back screen or small window on bottom left
* occasional frozen screen

After about 10 mins (typing this note so far) :
* Worked fine for 5 mins with 3 or 4 attempts
* On consequent 2 attempts, small window

Tried with System clock on:
* Clock shows on normal locations (random) with small window on bottom left (Ofcourse with extra clock ;) )

Going back to your previous build :)

**Comment by glouel** [comment] 2019-12-20 10:23
Hi @ravindrank and thanks for giving it a shot ! And sorry for my late reply. 

> Thanks @glouel for this one. Just tried this version. Removed the clock setting and tried immediately using preview. 

I'm scratching my head, let me ask a few questions to clarify : 

> * First time seemed to worked
> * On consequent tries, random back screen or small window on bottom left

Black screen ? Did you observe that before with a previous version ? I seem to remember you had a multi monitor setup, so is it happening on all screens at the same time or just some goes blank ?

> * occasional frozen screen

Frozen how ? Like the video loads and it freeze with the video not moving after a few seconds of playing ? 

> After about 10 mins (typing this note so far) :
> 
> * Worked fine for 5 mins with 3 or 4 attempts
> * On consequent 2 attempts, small window

So definitely not better :(

> Tried with System clock on:
> 
> * Clock shows on normal locations (random) with small window on bottom left (Ofcourse with extra clock ;) )

So wait, I managed to make it worse ?? That's in a twisted way some good news. Can you confirm I get this right, the System clock workaround DOES NOT work with that build ?

> Going back to your previous build :)

Any chance you remember which one that was for you ? My guess is 1.6.4 unless you installed a beta ?

**Comment by ravindrank** [comment] 2019-12-20 15:31
> Hi @ravindrank and thanks for giving it a shot ! And sorry for my late reply.

Thanks for all your efforts :) We all appreciate your hard work on this. Also its holiday season so don't try too hard :)
 
> > Thanks @glouel for this one. Just tried this version. Removed the clock setting and tried immediately using preview.
> 
> I'm scratching my head, let me ask a few questions to clarify :
> 
> > * First time seemed to worked
> > * On consequent tries, random back screen or small window on bottom left
> 
> Black screen ? Did you observe that before with a previous version ? I seem to remember you had a multi monitor setup, so is it happening on all screens at the same time or just some goes blank ?
> 

Never seen this on previous versions.. No extra monitors. Just the macbook screen.

> > * occasional frozen screen
> 
> Frozen how ? Like the video loads and it freeze with the video not moving after a few seconds of playing ?

This time it was like a wallpaper. Important thing is I use apple watch unlock which might be affecting this.


> > After about 10 mins (typing this note so far) :
> > 
> > * Worked fine for 5 mins with 3 or 4 attempts
> > * On consequent 2 attempts, small window
> 
> So definitely not better :(
> 
> > Tried with System clock on:
> > 
> > * Clock shows on normal locations (random) with small window on bottom left (Ofcourse with extra clock ;) )
> 
> So wait, I managed to make it worse ?? That's in a twisted way some good news. Can you confirm I get this right, the System clock workaround DOES NOT work with that build ?
> 

It works but not consistently. Very intermittent . I cannot get the same behaviour when I repeated. I retried because I thought maybe I should have close the settings and tried without the preview. 

> > Going back to your previous build :)
> 
> Any chance you remember which one that was for you ? My guess is 1.6.4 unless you installed a beta ?

Yes 1.6.4 . Please do let me know if you need any logs etc. I have this Macbook only for another 10 days :( I have a hackbook setup to test but probably that wont help you  much ;)

**Comment by glouel** [comment] 2019-12-20 15:41
> > Hi @ravindrank and thanks for giving it a shot ! And sorry for my late reply.
> 
> Thanks for all your efforts :) We all appreciate your hard work on this. Also its holiday season so don't try too hard :)

Hehe thanks !

> > Black screen ? Did you observe that before with a previous version ? I seem to remember you had a multi monitor setup, so is it happening on all screens at the same time or just some goes blank ?
> 
> Never seen this on previous versions.. No extra monitors. Just the macbook screen.
> 
> > > * occasional frozen screen
> > 
> > 
> > Frozen how ? Like the video loads and it freeze with the video not moving after a few seconds of playing ?
> 
> This time it was like a wallpaper. Important thing is I use apple watch unlock which might be affecting this.

About  those two, would you mind trying this build : https://github.com/JohnCoates/Aerial/releases/download/v1.6.5beta2/Aerial.saver.zip

It's the same that I gave you yesterday, minus my "fix" for this bug. Would help me narrow it down. If you see blank screen/freeze, please paste the log and note time when this happen, that would help ! 

> > > After about 10 mins (typing this note so far) :
> > > 
> > > * Worked fine for 5 mins with 3 or 4 attempts
> > > * On consequent 2 attempts, small window
> > 
> > 
> > So definitely not better :(
> > > Tried with System clock on:
> > > 
> > > * Clock shows on normal locations (random) with small window on bottom left (Ofcourse with extra clock ;) )
> > 
> > 
> > So wait, I managed to make it worse ?? That's in a twisted way some good news. Can you confirm I get this right, the System clock workaround DOES NOT work with that build ?
> 
> It works but not consistently. Very intermittent . I cannot get the same behaviour when I repeated. I retried because I thought maybe I should have close the settings and tried without the preview.

So it's slightly worse then if I get what you are saying, correct ? I may have another idea, I'll try to get another build up later today or tomorrow. 

It's possible that on those machines, the driver is sensitive on the order/timing of when layers are drawn. If what I did made it a bit worse, I'll try it the other way around, make a build with just video and no extra information just to see if that isolate the issue. Will get back to you ;)

> Yes 1.6.4 . Please do let me know if you need any logs etc. I have this Macbook only for another 10 days :( I have a hackbook setup to test but probably that wont help you much ;)

Thanks for the heads up, I'll see if I can find something in the meantime ! As for your hackbook, I bet it doesn't exhibit the bug ? Seems to be narrowed to a few gens of Intel GPUs that share the same driver (can't trigger the bug in my 2011 MBA for example).

**Comment by ravindrank** [comment] 2019-12-20 18:12
Hi Guillaume,

After I loaded this one just to be sure checked that the version was still 1.6.4 so I realized I needed to close settings and reopen. After that verified on the new version 1.6.5 beta2. Previous times I'm not sure if I checked for this much detail.

I started with the show Clock setting off. Got the blank screen once (missed the time sorry probably 11:03:00)[AerialLog.old2txt.txt](https://github.com/JohnCoates/Aerial/files/3989573/AerialLog.old2txt.txt)
) and but on repeated tries didnt get the blank screen. I suspect it is just that video download didnt kick in. I waited for 20 30 seconds.

I still got the windowed video frequently. 

After turning on the clock setting seems work consistently. 
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3989576/AerialLog.txt)

Overall, feels like a better build. Thanks. 

And yes, Hackbook doesnt have the issue, like you mentioned (Intel HD graphics 630 on i7 7700HQ Kaby Lake)

**Comment by glouel** [comment] 2019-12-20 18:34
> Hi Guillaume,
> 
> After I loaded this one just to be sure checked that the version was still 1.6.4 so I realized I needed to close settings and reopen. After that verified on the new version 1.6.5 beta2. Previous times I'm not sure if I checked for this much detail.

Yep, it's a bug in System Preferences if you don't close it before installing (that's why I say you should close syspref on main project page ;)), it loads the new version but "keeps" the old UI in memory, which makes for a terrible experience. 

BUT ! This is only an issue for System Preferences, as, I'm 99% sure, you get the new version when you run the screensaver. 

> I started with the show Clock setting off. Got the blank screen once (missed the time sorry probably 11:03:00)[AerialLog.old2txt.txt](https://github.com/JohnCoates/Aerial/files/3989573/AerialLog.old2txt.txt)
> ) and but on repeated tries didnt get the blank screen. I suspect it is just that video download didnt kick in. I waited for 20 30 seconds.

Ok if you are streaming, then that's normal I guess. Streaming may fail, Apple servers do not like streaming at all and might stop midway. I highly suggest you cache videos to avoid that but that definitely explains the frozen times. As for 11:03, I can't find any run at that time today in the log, I checked, you have a gap between 10:34 and 12:24. 

> I still got the windowed video frequently.

Ok that makes sense. 

> After turning on the clock setting seems work consistently.
> [AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3989576/AerialLog.txt)

That's better then ! I'll get back to you soonish with a build, many thanks !

> Overall, feels like a better build. Thanks.
> 
> And yes, Hackbook doesnt have the issue, like you mentioned (Intel HD graphics 630 on i7 7700HQ Kaby Lake)

👍

**Comment by glouel** [comment] 2019-12-20 19:41
@ravindrank when you get a sec, give https://github.com/glouel/Aerial/releases/download/v1.6.5beta2c/Aerial.saver.zip a chance !

With system clock disabled, basically same as the 1.6.5beta2 but with my "fix" in the other way. You won't see anything else but video on screen, that may help me understand what's happening should that one work. Thanks !

**Comment by glouel** [comment] 2019-12-27 17:23
So, I'm not sure what I did, but I now have managed to reproduce the bug here with the latest beta build too on my iMac. It looks like I changed something that triggered it. I tried to investigate but so far didn't see anything, I'll give it another go soon.

**Comment by glouel** [comment] 2019-12-30 12:32
This is driving me crazy, the exact build that let me reproduce the bug on Friday no longer does it for me on my iMac this morning 🙈 

Replying to myself about overriding the isPreview flag, I did test that on Friday and it's not the issue, not overriding didn't change a thing. 

But now that I know that it's our view that gets resized, I think this *may* be fixable, here's a build where I try to detect a bug situation and override the view size to what it was at startup. I can't test this sadly so if anyone here could test and report, that would be helpful. I did a quick check and it's possible to change the view size, whether that workaround the bug or not, I have no idea so please let me know : https://github.com/glouel/Aerial/releases/download/v1.6.5beta3b/Aerial.saver.zip

Please note that after install, you will need to set again your video preference (1080p 4K, HDR) as I changed stuff in that beta to make the UI simpler/easier to understand. 

Thanks!

**Comment by MadimetjaShika** [comment] 2020-01-01 18:42
Hi @glouel,

Firstly, thanks for your (and all other contributor's) work on this project.

In response to your request;
> But now that I know that it's our view that gets resized, I think this _may_ be fixable, here's a build where I try to detect a bug situation and override the view size to what it was at startup. I can't test this sadly so if anyone here could test and report, that would be helpful. I did a quick check and it's possible to change the view size, whether that workaround the bug or not, I have no idea so please let me know : https://github.com/glouel/Aerial/releases/download/v1.6.5beta3b/Aerial.saver.zip

I've installed ``v1.6.5beta3b``, and all seems to be good. I don't observe the small preview display issue mentioned on this thread. Note that this is my very first install of this project, i.e. I didn't have to uninstall or upgrade from a previous version.

**My test process:**

*  With "*Show with clock*" setting selected
	*  I allowed 7 videos to play without interruption, and all displayed at full screen. I did two separate isolated iterations, one on power and another on battery (pretty much full capacity at the time of testing).
*  With "*Show with clock*" setting de-selected
	*  	Same process as above, except I only did one iteration with power connected.

For all iterations, the videos played at fullscreen without any issues.

**My system info (not on osx beta program):**
<img width="586" alt="Screenshot 2020-01-01 at 19 30 40" src="https://user-images.githubusercontent.com/6643245/71644316-3d81f180-2ccf-11ea-9d85-2db44671c879.png">

**Additional Aerial config info:**

*  Video format at 1080p HDR
*  Disabled all other *info display* options except for "location"
*  Disabled video caching
*  All other config was left at the default from installation.

So yea seems like this issue may be resolved with ``v1.6.5beta3b``. I'll continue to observe this over time and let you know if at any point I come across the noted issue. 

PS - let me know if there's any additional config I missed in my tests which may cause the noted issue and I'll be happy to re-test.

**Comment by glouel** [comment] 2020-01-02 12:01
> Firstly, thanks for your (and all other contributor's) work on this project.

Hi @MadimetjaShika !

Thanks a lot for checking this out :
 
> * With "_Show with clock_" setting selected
>   
>   * I allowed 7 videos to play without interruption, and all displayed at full screen. I did two separate isolated iterations, one on power and another on battery (pretty much full capacity at the time of testing).

So, this one should always work, even with the old builds. 

> * With "_Show with clock_" setting de-selected
>   
>   * Same process as above, except I only did one iteration with power connected.

That's the one that failed sometimes ! So hopefully I got it fixed !

> **My system info (not on osx beta program, and slightly different to initial reported machine):**
> <img alt="Screenshot 2020-01-01 at 19 30 40" width="586" src="https://user-images.githubusercontent.com/6643245/71644316-3d81f180-2ccf-11ea-9d85-2db44671c879.png">

Awesome, this Mac *should* experience the original bug as far as I understand. 

> **Additional Aerial config info:**
> 
> * Video format at 1080p HDR
> * Disabled all other _info display_ options except for "location"
> * Disabled video caching
> * All other config was left at the default from installation.

Sounds good !

> So yea seems like this issue may be resolved with `v1.6.5beta3b`. I'll continue to observe this over time and let you know if at any point I come across the noted issue.
> 
> PS - let me know if there's any additional config I missed in my tests which may cause the noted issue and I'll be happy to re-test.

Again, many thanks for testing, if I may ask one more thing from you, would you be so kind to go into the Advanced tab in Aerial, make sure you check "Debug Mode" and "Log to disk".

Then, with the system clock unchecked, quickly launch Aerial a few times (5 or 6 should do, you can use a hot corner to quickly do it). Then open the log (you can open it using the "Show in Finder" button next to the two checkboxes I mentionned above) and search for a line that contains "*** Frame size bug". If you see that line, that would confirm that you hit the bug and the workaround worked !

Many thanks again for checking this out!

**Comment by ravindrank** [comment] 2020-01-02 13:50
Hi Guillaume,
Apologies I was out for several days and couldn't test this one. 
I was able to test 1.4.5beta3b build yesterday and glad to report that I didn't hit the issue :) No more small window. I tried without the clock setting as well as with the clock setting. I did turn on the 4K setting like you suggested. 

Unfortunately I wont have the Macbook anymore from today but hoping you are all set for the new release :) Thanks for all the work you do  and we appreciate all your efforts

**Comment by glouel** [comment] 2020-01-02 13:55
No worries @ravindrank, thanks for confirming that the workaround seems to work ! 

If you still have a few minutes with it and could check in the log if you see the "Frame size bug" line that I mentionned in the above post maybe, although the fact that you did hit the bug previoulsy and didn't with that build is probably enough confirmation !

**Comment by ravindrank** [comment] 2020-01-02 14:11
Last minute :) but I found one one entry though not sure how. Maybe once I saw a blank screen.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4016102/AerialLog.txt)

**Comment by glouel** [comment] 2020-01-02 14:21
> Last minute :) but I found one one entry though not sure how. Maybe once I saw a blank screen.
> [AerialLog.txt](https://github.com/JohnCoates/Aerial/files/4016102/AerialLog.txt)

When you see this line, it means the workaround code kicked in so on the contrary, it's all good ! Looking at your log :

```
2020-01-01 20:22:20.846 : *** Frame size bug, trying to override to 1440.0x900.0!
```

So that's when I detected that the frame was resized (I still have no idea why that happens but I think it's the Screensaver API at this point) and tried to size it back. 

```
2020-01-01 20:22:23.696 : <AerialView: 0x7fed5580b350> observeValue Optional("readyForDisplay") true (0.0, 0.0, 1440.0, 900.0)
2020-01-01 20:22:23.696 : start playback: (0.0, 0.0, 1440.0, 900.0) (0.0, 0.0, 1440.0, 900.0)
```

It did then started to stream a video and start it's playback at the correct size, so that looks all good to me ! Looks like you woke from the screensaver a few secs afterwards and went back into settings. 

So that looks pretty good, I'll release 1.6.5 with that fix then, thanks for the last minute check !

**Comment by glouel** [comment] 2020-01-29 20:13
Closing this with the release of 1.7.0 : https://github.com/JohnCoates/Aerial/releases/tag/v1.7.0

**Closed by glouel** 2020-01-29 20:13 UTC
Labels: Catalina, fix inside
