### ISSUE TITLE
HD Aerials

### ISSUE THREAD

**Issue by tomcag** [JohnCoates/Aerial#404] opened 2017-10-18 17:35 UTC
Hey John, 

I hope you're well. 
I just downloaded your aerials screensaver on my iMac 27". 

It's brill! Thanks so much for making it, I loved the screensavers on my Apple TV and now I can have them here too. 

The only thing which I think could be better is if they were HD or 2K?
My screen is a 2K 27" screen and so they look a bit low quality and could be sharper on here. 

Thank you!
All the best, 
Tom McCagherty

**Comment by AddoSolutions** [comment] 2017-10-20 01:55
Duplicate of #378.  Closing issue.  Haha, just kidding, I've always wanted to do that to someone. I cant close this issue, but someone will :)

**Comment by alistairmcmillan** [comment] 2017-10-22 23:29
As mentioned, duplicate of #378. John is working on it.

**Closed by alistairmcmillan** 2017-10-22 23:29 UTC
