### ISSUE TITLE
How to uninstall it on my mac !

### ISSUE THREAD

**Issue by jasony9982** [JohnCoates/Aerial#199] opened 2016-01-18 05:31 UTC
I have installed aerial earlier ,it was wonderful ,but now I  want to uninstall it !Delete directly in system preference setting can't work!  it seems that i install it for all users on my mac !

**Comment by alistairmcmillan** [comment] 2016-01-18 12:21
If you installed for all users then the actual screensaver file will be in `/Library/Screen\ Savers`. Just delete it from there.

If you enabled the cache feature the cached videos will be in `/Users/YOURUSERNAME/Library/Caches/Aerial`.

**Comment by alistairmcmillan** [comment] 2016-01-18 12:22
Duplicate of #187.

**Closed** 2016-01-18 13:08 UTC
