### ISSUE TITLE
Since 1.4.8+ keyboard input no longer stops the screensaver

### ISSUE THREAD

**Issue by luckman212** [JohnCoates/Aerial#768] opened 2019-05-07 13:09 UTC
- [x] Mac model: **mac mini 2018**
- [x] macOS version: **10.14.4**
- [x] Monitor setup: **2 external 23" displays**

#### Description of issue

Since ver 1.4.8 or so (maybe 1.4.9?) when I tap the keyboard to end the screensaver and get to the lockscreen, the mac just plays a beep/alert sound, but the video keeps playing. Only moving the mouse causes the video to stop playing.

I'm now on 1.4.10beta2 but the issue remains. I've been using Aerial for years, since 1.1 and never had this issue before.

Can't really think of anything that would cause this, but browsing through recent commits, https://github.com/JohnCoates/Aerial/commit/7786dc683bd3f2a5a7827a3c8e46400781ad2251 seems like the only thing even close to being related.

I've just enabled debug logging, so next time this happens I'll be sure to post a log.

**Comment by glouel** [comment] 2019-05-07 13:26
Hi @luckman212 

Does no key work, not even the space bar ? Can you try unchecking the "Right arrow skips video" option in main panel to see if it helps ? Thanks

**Comment by luckman212** [comment] 2019-05-07 13:42
Correct - when this bug occurs, no keys work. I have unchecked the "Allow Right arrow key to skip" box for now and will report back if that makes any difference.

**Comment by luckman212** [comment] 2019-05-07 14:37
Ok, so this just happened again, even with the Allow skip option enabled. I'm attaching the debug log here. I noticed this time that the "CTRL" key (that's how I usually wake up the display) has no effect, and does not cause the error/beep sound to play. However other standard keys such as spacebar, any letter keys, arrow keys etc do cause a beep sound. Moving the mouse also had no effect - the only way to stop the video playback and get back to the lockscreen was to CLICK the mouse.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3153140/AerialLog.txt)

**Comment by glouel** [comment] 2019-05-07 15:03
Ok thanks for the report, I'll have a look and let you know. Can you tell me which keyboard you have on your mac mini ? Are you by any chance using multiple keyboards (even if not at the same time ?) ?

**Comment by luckman212** [comment] 2019-05-07 15:08
Currently I'm using a Logitech G413 keyboard. I don't have multiple keyboards but I do have Karabiner-Elements installed, to disable the CapsLock key.

**Comment by glouel** [comment] 2019-05-07 16:15
So according to your log, Aerial doesn't receive the keydown events (there should be a "keyDown" somewhere), which is consistant with you hearing beeps when pressing non modifier keys (just like typing when you don't have focus). Karabiner-Elements probably intercepts events and that throws the logic. 

I may have missed an event forwarding, trying some stuff and will get back to you.

**Comment by luckman212** [comment] 2019-05-07 16:37
Thank you - anything else I can do to help debug just let me know

**Comment by glouel** [comment] 2019-05-07 16:52
Well, I just put up beta3 if you can give it a shot, there's a tentative fix for both your issues, although I'm very unsure about this one to be honest ! Let me know how it goes and we'll try to figure out what's next.

**Comment by luckman212** [comment] 2019-05-07 18:32
Great, happy to test - I will give this a go and report back

**Comment by luckman212** [comment] 2019-05-09 13:20
Just reporting in. Been running beta3 for a few days now and it hasn't fixed this for me (sadly). I also removed Karabiner-Elements temporarily for testing (did not help). I don't know what else to do to debug. Sometimes the keyboard works to bring up the login prompt and sometimes it doesn't. **Mouse clicks always work**!

I think this is related to the `/System/Library/CoreServices/loginwindow.app/Contents/MacOS/loginwindow` process having focus and thus eating keypresses. The reason I suspect this is: I've noticed that sometimes when the screen unlocks, the frontmost app does **_not_** have focus even though it appears from the menu bar that it should.

E.g. when I walk away, the frontmost app was Sublime Text and I was in the middle of editing a file. When I come back and unlock, even though Sublime is still the frontmost app, all keypresses result in a **_beep_** sound until I click the mouse in the Sublime window—this mimics the original bug I am seeing from within Aerial / `ScreenSaverEngine` sometimes. I can tell that this is happening because Karabiner includes a helpful app called EventViewer that displays the frontmost app in a floating window (see screenshot below).

![image](https://user-images.githubusercontent.com/1992842/57456097-af866180-723a-11e9-8310-5704d1e01c61.png)

In case it's at all helpful, I'm attaching a fresh log here.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3162310/AerialLog.txt)

**Comment by glouel** [comment] 2019-05-09 13:49
I was going to suggest maybe disabling Karabiner-elements, as I strongly suspected it could be linked to your issue. You mentioned disabling it, though. 

There may be something else specific to your setup that's causing this (I can't reproduce and nobody else complained about it yet so there's probably something pretty specific). The fact that you also have the issue with Sublime not getting focus back certainly isn't right either. Here I systematically get focus back on the previous window when coming out of screensaver. Are you using some third party login addon maybe ? Do you have some sort of extra "keyboard driver" installed ? I'll try to grab that EventViewer to give it a shot here and see what I get. 

In general, we don't control much as a screensaver, we are just a plugin for ScreenSaverEngine and don't control our lifecycle. Our view gets initialized by ScreenSaverEngine, and ScreenSaverEngine kills us when he wants to.

I do see many keyDown events that we intercept now (since 1.4.8) in your log, can you confirm that you kept enabled the right arrow key thing ? Our interception seems to work since the right arrow thing works for you, but it looks like when we forward the key event now (after intercepting), on your machine it goes to loginwindow and not ScreenSaverEngine. 

By not intercepting in previous versions, it looks like you didn't have the issue. A quick fix would have been to conditionally override the keyDown event but that's not possible. 

I'll keep investigating this, and try to see what EventViewer says here and report back to you. May I suggest you give a shot to ElectricSheep ? It also overrides the right arrow key (I haven't looked at their source code though to see how they do it) so maybe you'll get to see if you have the same issue or not ? Could be a good data point.  

https://electricsheep.org/mac/

**Comment by luckman212** [comment] 2019-05-09 21:30
Sure I will give ElectricSheep a try and see if the results are the same, and if they are I will work backwards on any 3rd party things that might be conflicting. I did remove Karabiner but then re-installed it after I continued having the issue. So I will try some more thorough testing.

**Comment by luckman212** [comment] 2019-05-10 05:42
Ok, I believe I've uncovered more info!

- I tried ElectricSheep as well as some other screensavers and observed that they triggered this bug too. So, good news - it does NOT seem to be an Aerial bug at all 🎉
- I completely uninstalled Karabiner-Elements, rebooted, double checked that the kext was not present via `kextstat | grep -v com.apple`, and then re-tested. The problem was still present - so does not seem to be related to KbE either
- I **_do_** think I've traced the source of this problem to the "screen lock" feature in System Preferences > Security & Privacy. I had mine enabled/set like this (which is not the default):
![image](https://user-images.githubusercontent.com/1992842/57504229-af7d7480-72c1-11e9-8780-dfe83b13db79.png)
- As a test, I created a brand new user account, downloaded Aerial 1.4.10b3 and tested on that (no modifications whatsoever) and was UNABLE to reproduce the issue
- I then enabled the auto-lock feature (no other changes made) and re-tested. I was then able to reproduce the bug. So it seems very likely to be related
- When the screensaver exits **and** the auto-lock feature is enabled (at least on my system) - the active aka focused app will be NULL (it actually _wasn't_ `loginwindow` as I previously thought—it's just that KbE's EventViewer app doesn't seem to report NULL values, whereas the Python script below does).

Please verify yourself if you have time, by saving this script and running it from a Terminal:
https://gist.github.com/luckman212/91cdd9a08e98a9f01214bdfde3057e85

Then enable the screen lock preference and activate your screensaver. See if when you exit, you have output similar to the below (and any keypresses result in beep sounds...)
![image](https://user-images.githubusercontent.com/1992842/57504219-a5f40c80-72c1-11e9-8870-117cb66b4a79.png)

**Comment by glouel** [comment] 2019-05-10 11:22
Hi @luckman212 

> Ok, I believe I've uncovered more info!
> 
> * I tried ElectricSheep as well as some other screensavers and observed that they triggered this bug too. So, good news - it does NOT seem to be an Aerial bug at all 🎉

Good news in a sense indeed, although I hope we can fix your issue. 

> * I completely uninstalled Karabiner-Elements, rebooted, double checked that the kext was not present via `kextstat | grep -v com.apple`, and then re-tested. The problem was still present - so does not seem to be related to KbE either

Ok good to clear that one up too!

> * I **_do_** think I've traced the source of this problem to the "screen lock" feature in System Preferences > Security & Privacy. I had mine enabled/set like this (which is not the default):
>   ![image](https://user-images.githubusercontent.com/1992842/57504229-af7d7480-72c1-11e9-8780-dfe83b13db79.png)
> * As a test, I created a brand new user account, downloaded Aerial 1.4.10b3 and tested on that (no modifications whatsoever) and was UNABLE to reproduce the issue
> * I then enabled the auto-lock feature (no other changes made) and re-tested. I was then able to reproduce the bug. So it seems very likely to be related
> * When the screensaver exits **and** the auto-lock feature is enabled (at least on my system) - the active aka focused app will be NULL (it actually _wasn't_ `loginwindow` as I previously thought—it's just that KbE's EventViewer app doesn't seem to report NULL values, whereas the Python script below does).
> 
> Please verify yourself if you have time, by saving this script and running it from a Terminal:
> https://gist.github.com/luckman212/91cdd9a08e98a9f01214bdfde3057e85
> 
> Then enable the screen lock preference and activate your screensaver. See if when you exit, you have output similar to the below (and any keypresses result in beep sounds...)
> ![image](https://user-images.githubusercontent.com/1992842/57504219-a5f40c80-72c1-11e9-8870-117cb66b4a79.png)

First, thanks for digging into this so deeply, hopefully we can get to the bottom of this. 

Soooooo...

FYI I had it at 5 minutes here (probably default ?) AND I have Apple Watch unlock enabled. So, first with my original setup:
<img width="1407" alt="Capture d’écran 2019-05-10 à 12 48 28" src="https://user-images.githubusercontent.com/37544189/57522157-3eba7480-7322-11e9-9763-a90b1c1d33a4.png">

No loginwindow.app (makes sense, below 5 mins), no no active app either. 

With insta-lock AND Apple Watch unlock:
<img width="1408" alt="Capture d’écran 2019-05-10 à 12 48 44" src="https://user-images.githubusercontent.com/37544189/57522370-cc965f80-7322-11e9-9b6a-2f236eb7157b.png">

As you can see I also have the no active app thing. And I can confirm that on exiting screensaver, iTerm2 (or any other app) didn't have focus. I switched to another app to be sure in subsequent test and every time, no focus. That's not particularly good and look like a (new?) system bug indeed. 

Yet, every single time, as I used space key, the login screen instantly popped and I was relogged (with no keyboard focus, but still relogged). I also did try disabling Apple Watch unlock but same result on 5 tries. 

As a side note, I do use Mojave's latest beta 10.14.5 (18F131a) which may (or may not) make a difference. But with that said, I tried on my painfully old 2011 Macbook Air under High Sierra and... 

![Capture d’écran 2019-05-10 à 13 11 29](https://user-images.githubusercontent.com/37544189/57523470-5c3d0d80-7325-11e9-862f-f6ac57c61fd5.png)

iTerm (or whatever) keeps focus, tried a few times, after loginwindow I always get focus back. So the no active app looks like a new Mojave bug, which is definitely worth a radar ! 

There's a tiny chance that this mayyyyy be a 10.14.4 bug that happens to be fixed in 10.14.5 beta, that could explain why I can't replicate but if so, I'm pretty sure someone else would have complained ? Or maybe it only happens with insta lock which noone else uses ? People make issues about way less usually and that's a pretty major one. 

This doesn't clear it all up sadly, sorry. Side question, do you have any logitech software installed by the way ?

**Comment by luckman212** [comment] 2019-05-10 12:04
Thanks for the detailed reply and for taking more time out to test on this! (No I don't have any Logitech software installed).

Glad you were able to reproduce my results, at least the NIL app focus on screensaver exit. I'll file a rdar for that and reference back here.

I'm going to try installing 10.14.5 beta just to see if by chance the original issue is just a 10.14.4 bug.

**Comment by luckman212** [comment] 2019-05-10 12:42
I installed 10.14.5beta5 (18F131a) and re-ran my tests. Interestingly, the VERY FIRST time I invoked Aerial (via hot-corner), upon trying to wake up the screen, I hit the original bug again 😞 (keypresses were just resulting in a "beep" but not causing the login prompt to appear).

So, I clicked the mouse and unlocked the screen. Then, I triggered the screensaver a second time, and this time the keypresses worked fine. I repeated a few more times, and it also worked. So I guess it's back to being inconsistent, or somewhat improved. I'll keep investigating.

Sadly, the "no active app" bug still seems present to me. It is always triggered when the screen is woken up AFTER the "require password after" timer has elapsed.

E.g. if you have it set to 1 minute, and then you trigger the screensaver and wait only 15 seconds, and then wake up the screen, your app will regain focus correctly.

However, if you instead wait e.g. 65 seconds, when you wake up the screen (after unlocking it) you will have the NIL focused app.

**Comment by glouel** [comment] 2019-05-10 12:46
@luckman212 hmm, well at least it's a tiny bit better now, it looks like this is really some new Mojave bug then. Hopefully the frequency will be pretty low now. I never managed in maybe 30 tries here. Maybe it now only happens once upon reboot (hoping). 

Definitely file a radar for both issues I think !

**Comment by luckman212** [comment] 2019-05-10 13:38
For now I filed bug [50661344](https://openradar.appspot.com/radar?id=5056554340450304) for the issue that leaves NULL focusedapp after resume (since that's the one I can reliably reproduce).

I'll keep testing on the other one to try to get better repro steps.

**Comment by luckman212** [comment] 2019-05-10 17:35
Just FYI- I am now running 1.4.99beta1

**Comment by glouel** [comment] 2019-05-10 17:36
Great, let me know if you have any issues with the new multi monitor stuff! Some pretty radical changes I've been working on all week ;)

**Comment by luckman212** [comment] 2019-05-10 17:39
So far no issues! 🙌

The new multi monitor modes are very cool, I really like the "spanned" mode - great effect.

**Comment by glouel** [comment] 2019-05-10 19:11
Thanks ! Took me a while to figure out how to properly detect the screens but got it in the end :)

**Comment by gregarios** [comment] 2019-05-11 02:54
Here is the problem I was having with the keyboard not switching scenes (with the arrow key) and my screensaver not stopping with any keystrokes, and the solution that fixed both:
https://apple.stackexchange.com/questions/332448/how-to-stop-screensaver-with-a-keyboard-button-press-rather-than-a-mouse-button

**Comment by glouel** [comment] 2019-05-11 08:48
> **Note:** Ok upon even further experimentation, I discovered that the arrow and the keyboard screensaver-off both work also if I have the _"Displays have separate spaces"_ turned on or off and the _"When switching to an application, switch to a space with open windows for the application"_ enabled as well.
> 
> So, _either_ of these settings will allow it to work correctly under MacOS Mojave:

@gregarios many many thanks for following up on this ! This is super useful feedback !

**Comment by luckman212** [comment] 2019-05-17 16:10
Just wanted to post an update since I've been banging away at this for a while. Some things I've learned:

1. This is _not_ an Aerial bug. It affects all screensavers, including the ones shipped with macOS.
2. The bug lies in macOS, and seems to have started with High Sierra (10.13).
3. Does not affect all systems, and even on the systems that are affected, it does not occur 100% of the time ScreenSaverEngine is invoked, making it very difficult to troubleshoot.
4. The bug does not seem to be in `/System/Library/CoreServices/ScreenSaverEngine.app` itself: I extracted a copy of this app from 10.12 and code-signed it so it would run on 10.14, and tried to invoke it manually—the same bug manifested itself (keypresses are eaten, do not stop the saver).
5. In [this thread on AskDifferent](https://apple.stackexchange.com/a/332452/100302), one user reported that changing these Mission Control settings was a workaround. However, I tested all of the combinations that were supposed to work, and in my case, they did NOT fix the issue. So I reverted back to my preferred settings (Displays have separate spaces: **un**checked).

In light of the above, feel free to close this and I'll post back with any updates I receive from Apple via the BugReporter, or if any future macOS releases fix the bug.

**Comment by glouel** [comment] 2019-05-17 16:17
hey @luckman212 

Thanks a lot for the followup, gregarios posted two combinations that work for him above just in case you want to give this a shot.

I'll be closing this then, pretty sad that it's a macos bug, bit disheartening to see so many little things starting to fail over time :(

**Closed by glouel** 2019-05-17 16:17 UTC
