### ISSUE TITLE
Energy Saver -> Turn display off after x minutes

### ISSUE THREAD

**Issue by 3tlam** [JohnCoates/Aerial#32] opened 2015-10-27 22:23 UTC
Hi!

I love your screensaver! Very very nice work :+1: 
Unfortunately my Mac is not able to shut down the monitor anymore.
Normally I can set some time in the System Preferences -> Energy Saver -> Turn display off after x minutes 

Would be awesome if you were able to fix this :D
But I am guessing you have heaps of new issues just today ;)

Thanks again for the awesome work!

**Comment by alistairmcmillan** [comment] 2015-10-28 00:20
Possibly related to issue #23 .

**Comment by joshlewis** [comment] 2015-10-30 05:41
I think this is a duplicate of #23, not just related.

**Comment by JohnCoates** [comment] 2015-10-30 10:02
Thanks @alistairmcmillan for linking the original issue. I'm working on fixing this, but the solution I've found is quite complicated and will take a bit to implement.

**Closed by JohnCoates** 2015-10-30 10:02 UTC
Labels: duplicate
