### ISSUE TITLE
Won't work with MacBook Pro with magic bar

### ISSUE THREAD

**Issue by ahpendo** [JohnCoates/Aerial#288] opened 2016-12-27 03:57 UTC
Says it needs a newer version

**Comment by alistairmcmillan** [comment] 2016-12-27 03:59
It's a bug in OSX/macOS.

The screensaver itself should launch and run okay.

The bug should just affect the preview in System Preferences. If you select Aerial, close System Preferences, then re-open System Preferences, you should find that the preview works okay.

Closing as a duplicate of #269 .

**Closed by alistairmcmillan** 2016-12-27 03:59 UTC

**Comment by ahpendo** [comment] 2016-12-27 04:20
Weird but it worked!!
ALVIN PERELMAN
ahpendo@perelmanaz.com
9270 East Thompson Peak Parkway, Unit #371
Scottsdale, AZ 85255
480-699-4880
Cell 480-280-6418
