### ISSUE TITLE
Set as desktop wallpaper

### ISSUE THREAD

**Issue by joshnh** [JohnCoates/Aerial#37] opened 2015-10-28 03:06 UTC
Love what you've done with this. My desktop wallpaper now looks incredible when I choose to run the following command in an open terminal window:

/System/Library/Frameworks/ScreenSaver.framework/Resources/ScreenSaverEngine.app/Contents/MacOS/ScreenSaverEngine -background

This isn't an issue, just a note. Thought it was worth mentioning for those that weren't aware of this neat little trick.

**Comment by agucova** [comment] 2015-10-28 03:08
I made a script with it and bundled it into an app, when I need to clear my mind, I just open the app.

**Comment by zongren** [comment] 2016-06-10 09:01
@agucova could you please share your script 😄

**Comment by alistairmcmillan** [comment] 2017-01-22 04:01
Closing as duplicate of #13

**Closed by alistairmcmillan** 2017-01-22 04:01 UTC

**Comment by MichaelDimmitt** [comment] 2017-05-12 17:56
@joshnh, @agucova, @zongren 
this application that I wrote uses a launch agent.
https://github.com/MichaelDimmitt/Aerial_Desktop

It never opens more than one instance of Aerial. It loads from sleep or from startup. It automatically selects Aerial as the screensaver but that can be changed rather easily. It is meant to be incredibly simple click to install/enable click to uninstall/disable.

Want to switch to a new video after its already running? click uninstall and install and your desktop background will be different.

Meant to be super user friendly for my friends who are not programmers.

Does exactly what you are looking for and if you do not want it on all the time you can click uninstall and install it whenever you want. My laptop MacBook Pro (13-inch, Mid 2012) can run for 6 hours without needing a charge. So it does not consume a lot of resources. Chrome usually more expensive. Regards, Michael Dimmitt.
