### ISSUE TITLE
Aerial not working without wifi

### ISSUE THREAD

**Issue by puchysv** [JohnCoates/Aerial#52] opened 2015-10-28 17:26 UTC
Whenever you disconnect wifi connection aerial does not longer works

**Comment by alistairmcmillan** [comment] 2015-10-28 17:51
Duplicate of #43

**Comment by puchysv** [comment] 2015-10-28 17:59
Sorry but I can't find the solution to the problem

**Comment by alistairmcmillan** [comment] 2015-10-28 19:20
The problem you're having is that the screensaver streams the videos from Apple's servers. It doesn't contain the videos itself. So if you disconnect from the internet then it can't reach the videos. Which is why people are asking John (the developer) to add an "offline" mode on that other issue. :)

**Comment by yourtion** [comment] 2015-10-30 02:15
@puchysv @alistairmcmillan 

I published a basic offline mode version. You can download and have a try. @jpshelley because the bad network and I work offline so the offline mode is needed.

https://github.com/yourtion/Aerial/releases/download/v1.3/Aerial.saver.zip

**Comment by alistairmcmillan** [comment] 2016-01-28 21:17
Closing as duplicate of #43

**Closed by alistairmcmillan** 2016-01-28 21:17 UTC
Labels: duplicate
