### ISSUE TITLE
Still Freezing After All These Years

### ISSUE THREAD

**Issue by the-saint** [JohnCoates/Aerial#811] opened 2019-06-13 05:18 UTC
Late 2015 iMac
Mojave 10.14.5
v. 1.5.0

Years later, still experiencing occasional freezing and black screen. Running videos off my HD, not streaming.

**Comment by glouel** [comment] 2019-06-13 08:48
@the-saint 

This is a bit vague... Maybe a log would be helpful if you want some help ?

**Comment by the-saint** [comment] 2019-06-14 13:19
It's snot actually vague. I specified the problem, how I'm getting the videos, the version of my iMac, the version of the OS, and the version of the screensaver. That's pretty detailed. I can't supply a log file at the moment because those options weren't turned on. I just enabled them. My Mac was on overnight and when I looked at tit this morning, I saw a still image of the Golden Gate Bridge instead of the video. The screensaver was frozen, not my iMac. I'll included a log file the next time the issue occurs.

**Comment by glouel** [comment] 2019-06-14 13:44
Are you running the screensaver the whole night or does your mac actually goes to sleep ? Not sure I exactly understand at which point you are seeing the frozen image. 

Also are you using 4K or not ? 4K will not be GPU accelerated on a 2015 iMac.

In general slowdowns come from some system service hogging the whole CPU. The only one I can recall recently is Photos. 

Quoting the troubleshooting page https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md : 

> High CPU usage/fan spinning all of a sudden: If you correctly configured the preferred video format according to your Mac and still experience high CPU usage/fan spinning all of a sudden, please look for the cause with Activity Monitor, you may see a com.apple.photos.ImageConversionService responsible for this CPU load. This is the iCloud Photos process, you can find more about what it does here and how to pause it.

AFAIK it does the syncing, conversion and the classification which can be pretty intense (part of these may be GPU accelerated on some Macs and may mess up GPU video acceleration). As mentioned, if you can reproduce, open Activity Monitor before running the screensaver, launch the screensaver and when it starts slowing down, wake it up and screenshot your Activity Monitor. A log should give a clue and more details about your exact configuration in any case.

**Comment by the-saint** [comment] 2019-06-14 14:14
> Are you running the screensaver the whole night or does your mac actually goes to sleep ?

I run my Mac overnight so it can perform automated backup routines. My Mac is set to never go to sleep.

> Also are you using 4K or not ? 4K will not be GPU accelerated on a 2015 iMac.

I am using 4K. Should I not be using 4K? There was no information about this when I made the selection.

> In general slowdowns come from some system service hogging the whole CPU. The only one I can recall recently is Photos.

I don't think this is the problem. My iMac is sitting idle Safari is usually open, as is iTunes, but they are doing nothing and no intensive processes are running. In any case, it's not a "slowdown." When I look at the screensaver in the morning, sometimes it's running, sometimes it's stopped. Occasionally, there will be a blank screen. When I move my mouse, the screensaver disappears as it's supposed to and my Mac works fine.

**Comment by glouel** [comment] 2019-06-14 14:48
> > Are you running the screensaver the whole night or does your mac actually goes to sleep ?
> 
> I run my Mac overnight so it can perform automated backup routines. My Mac is set to never go to sleep.

Ok. Understand that if a CPU intensive task pops up during that time, it may throw off the video playback, that's something to keep in mind. 

> > Also are you using 4K or not ? 4K will not be GPU accelerated on a 2015 iMac.
> 
> I am using 4K. Should I not be using 4K? There was no information about this when I made the selection.

You *can*, but it's a tradeoff on this particular generation of CPUs. There's a help bubble next to the video format picker that explains those in large details and tells you exactly what your mac supports. We also have more detailed information here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/HardwareDecoding.md

1080pH264 is the only one that's fully accelerated on this generation of iMacs. 

> > In general slowdowns come from some system service hogging the whole CPU. The only one I can recall recently is Photos.
> 
> I don't think this is the problem. My iMac is sitting idle Safari is usually open, as is iTunes, but they are doing nothing and no intensive processes are running. In any case, it's not a "slowdown." 

It's usually background services that does it, not your own apps. If one hogs the CPU, and you are using CPU decoding, it will start to stall the playback and may eventually fail for some reason. Intensive disk usage may cause this too, although less likely if on a SSD. Possibly more on a hard drive. 

> When I look at the screensaver in the morning, sometimes it's running, sometimes it's stopped. Occasionally, there will be a blank screen. When I move my mouse, the screensaver disappears as it's supposed to and my Mac works fine.

Understood. Log will probably give a clue. If you are always stuck at the end of a video (do you have a feel for this maybe ?), I think some background issue may be behind this. 

I've recently seen that Aerial can get stuck at the very end of a video *if* it wasn't able to playback correctly for a large portion of the expected duration of a video, it's an issue with HDR playback on this same iMac model and Catalina beta 1 (where system gets stuck for 2 minutes when attempting to play a HDR video).

**Comment by the-saint** [comment] 2019-06-14 15:21
I understand the difference between a running process and an app that’s using resources. I have Activity Monitor running 24/7 and I don’t usually see high CPU usage. Of course, I don’t know what’s going on at night when the SuperDuper backup runs. I can delete the 4K files and replace them with the lower-res files. Would I see a difference in image quality?

**Comment by glouel** [comment] 2019-06-14 15:35
I'm trying to be helpful here. I understand you are frustrated but this is a free project that I'm doing on my spare time. The only think I ask in exchange is that, when people report an issue, they consider this and *try* to be nice. 

There's a difference yes. It's mostly about resolution more than encoding quality. You can compare manually with those links to give you an idea:

1080p H264 : https://sylvan.apple.com/Videos/comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_2K_AVC.mov

4K HEVC : https://sylvan.apple.com/Aerials/2x/Videos/comp_DB_D011_C010_PSNK_DENOISE_v19_SDR_PS_20180914_SDR_4K_HEVC.mov

**Comment by the-saint** [comment] 2019-06-14 16:21
> I'm trying to be helpful here. I understand you are frustrated but this is a free project that I'm doing on my spare time. The only think I ask in exchange is that, when people report an issue, they consider this and try to be nice.

I’m not sure what this is about. I was explaining to something to you, not being snarky. I appreciate your help.

**Comment by the-saint** [comment] 2019-06-15 06:14
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3292786/AerialLog.txt)

I just noticed it was frozen when I walked into the room.

**Comment by glouel** [comment] 2019-06-15 08:25
> [AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3292786/AerialLog.txt)
> 
> I just noticed it was frozen when I walked into the room.

Great ! So I'm gonna roll back a bit, apparently the screensaver was kicked in by the system at 19h31:

```
2019-06-14 19:31:00 : avInit1 (0.0, 0.0, 2560.0, 1440.0)
2019-06-14 19:31:00 : <AerialView: 0x7ff4cce03020> AerialView setup init
```

Your cache is there, and local (which is nice, be aware that Catalina beta install would wipe this folder):
```
2019-06-14 19:31:00 : local cache exists
2019-06-14 19:31:00 : cache to be used : Optional("/Library/Caches/Aerial")
```

Then:
```
2019-06-14 19:31:00 : Could not determine duration, video is not cached in any format
```

This line pops at startup when Aerial check your local videos for their lengths in order to play the text animation. I'm seeing this 50 times, so that means you are missing 50 videos from cache (out of 73 Aerials as of today).

First video it plays:
```
2019-06-14 19:31:00 : <AerialView: 0x7ff4cce03020> playing video (OFFLINE MODE) : file:///Library/Caches/Aerial/comp_H004_C007_PS_v02_SDR_PS_20180925_SDR_4K_HEVC.mov
```

The file is cached, so it's playing offline. The next one isn't:
```
2019-06-14 19:35:01 : <AerialView: 0x7ff4cce03020> streaming video (not fully available offline) : https://sylvan.apple.com/Aerials/2x/Videos/comp_A009_C001_010181A_v09_SDR_PS_FINAL_20180725_SDR_4K_HEVC.mov
```

So Aerial goes fetching it online and streams it fine. 4 next videos streamed too, and fine, then a bit of a mix of cached/uncached:
```
2019-06-14 19:40:39 : <AerialView: 0x7ff4cce03020> streaming video (not fully available offline) : https://sylvan.apple.com/Aerials/2x/Videos/comp_GMT110_112NC_364D_1054_AURORA_ANTARTICA__COMP_FINAL_v34_PS_SDR_20181107_SDR_4K_HEVC.mov

2019-06-14 19:42:57 : <AerialView: 0x7ff4cce03020> streaming video (not fully available offline) : http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/b6-4.mov

2019-06-14 19:46:11 : <AerialView: 0x7ff4cce03020> streaming video (not fully available offline) : https://sylvan.apple.com/Aerials/2x/Videos/comp_N013_C004_PS_v01_SDR_PS_20180925_F1970F7193_SDR_4K_HEVC.mov

2019-06-14 19:49:07 : <AerialView: 0x7ff4cce03020> streaming video (not fully available offline) : https://sylvan.apple.com/Aerials/2x/Videos/comp_A108_C001_v09_SDR_FINAL_22062018_SDR_4K_HEVC.mov

2019-06-14 19:52:35 : <AerialView: 0x7ff4cce03020> playing video (OFFLINE MODE) : file:///Library/Caches/Aerial/b2-2.mov

2019-06-14 20:08:37 : <AerialView: 0x7ff4cce03020> playing video (OFFLINE MODE) : file:///Library/Caches/Aerial/comp_HK_B005_C011_PSNK_v16_SDR_PS_20180914_SDR_4K_HEVC.mov

2019-06-14 20:14:00 : <AerialView: 0x7ff4cce03020> playing video (OFFLINE MODE) : file:///Library/Caches/Aerial/comp_L007_C007_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov

2019-06-14 20:20:02 : <AerialView: 0x7ff4cce03020> playing video (OFFLINE MODE) : file:///Library/Caches/Aerial/comp_H004_C009_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov
```

Until the next fateful one : 
```
2019-06-14 20:24:03 : <AerialView: 0x7ff4cce03020> streaming video (not fully available offline) : https://sylvan.apple.com/Aerials/2x/Videos/comp_N008_C009_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov
```

Here playback stalled (that happens sometimes with Apple servers, it may not be on your end) and failed and Aerial was stuck: 
```
2019-06-14 20:24:20 : <AerialView: 0x7ff4cce03020> AVPlayerItemPlaybackStalledNotification name = AVPlayerItemPlaybackStalledNotification, object = Optional(<Aerial.AerialPlayerItem: 0x600000703160, asset = <AVURLAsset: 0x6000007018c0, URL = streaming://sylvan.apple.com/Aerials/2x/Videos/comp_N008_C009_PS_v01_SDR_PS_20180925_SDR_4K_HEVC.mov>>), userInfo = nil
```

So, looks like you are missing a lot of videos. Are you sure you cached them all ? If you are 100% sure, there are some "free space reclaiming" tools that are known to wipe your cache folders, which may explain why files are missing. See this in troubleshooting https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md :

> Videos keeps disappearing, Aerial may not restart once in a while: Aerial stores all its data in a Cache folder. This cache may get deleted by some third party software trying to free disk space. If you use such a "Cleaning" tool, we recommend you set a manual folder location in the Cache tab of Aerial. For example, you can create an Aerial folder in your User folder, and point to it. This will ensure Aerial files don't get deleted. 

If you are indeed using such a tool, what possibly happens is tool wipe your cache, Aerial creates cache again, start by streaming videos until it fills cache again (default settings) and should a stream fail, then you're stuck. Rince and repeat. 

The current state should should be apparent in the UI, you'll see a + next to the videos that are not currently cached. 

As a reminder, if you don't want to stream you have a few options:
- Cache all the videos (and maybe not in a Cache folder if you use some cache cleaning tool)
- Only select cached videos for playback (use the menu below the list)
- Go to Cache tab in UI and click "Never stream videos" (if you have *nothing* and don't allow streaming, Aerial will still stream, but only until you have one video, cached, then will reuse this one).

**Comment by the-saint** [comment] 2019-06-15 17:37
No clean apps This is strange, because I was under the impression I had downloaded all the checked screensavers (the ones I intended to play) but now I see a bunch of them aren't downloaded. I'm downloading them now.

**Comment by glouel** [comment] 2019-06-15 17:44
One thing to keep in mind is that from time to time, Apple releases new versions of their videos (upgrading old ones to 4K, or fixing colors, etc). When that happens, Aerial only uses the new files (many reasons, but they may not have the same length and not stick to the description track).

The last update was in january, but there was 3 if I remember correctly from september to december last year. 

I doubt this is your issue, because since then, Aerial ought to have cached those videos when streaming them. Unless you unchecked "Cache Aerials as they play" in that case, those streamed videos would not get cached. 

In any case, Aerial never deletes anything (unless you manually asked to, in the advanced panel).

**Comment by the-saint** [comment] 2019-06-16 17:12
The screensaver has been playing all night, with many of the files streaming. Would this seriously affect my internet data usage?

**Comment by glouel** [comment] 2019-06-16 19:54
Well, didn't you cache them ? I'm not sure I understand...

As for usage, some 4K videos are huge, yes, just have a look in your cache folder.

**Comment by the-saint** [comment] 2019-06-16 22:08
Well, the cause of the problem I was having is that many of the videos were streaming. So, the streaming videos were using up bandwidth. For the last few months, I’ve been over my ISP’s data allotment. We’ve been watching more streaming video on my Apple TV, but I was wondering if the screensaver could have caused the problem.

**Comment by glouel** [comment] 2019-06-16 22:56
I pointed you to how to disable streaming above, I would suggest you give that a try so aerial never streams again. But you mentioned earlier caching your missing videos so I don’t get why you were streaming again ?

**Comment by the-saint** [comment] 2019-06-16 23:12
I’m talking about the past few months, when the some of the videos were streaming, not the present, after I fixed the issue.

**Comment by glouel** [comment] 2019-06-16 23:16
When Aerial streams a video, it caches it on disk at the end (unless you manually disabled that). So at worst you only streamed each video once. 

But if you think this has been going on for months, it literally makes no sense as you should have filled up the cache much faster that this in a matter of a couple of days probably. That is, unless a 3rd party tool periodically wiped your cache which I mentioned above.

**Comment by the-saint** [comment] 2019-06-17 00:36
But the default setting is cache after playing set to off, so it wasn’t caching after streaming.

**Comment by glouel** [comment] 2019-06-17 08:28
No it's not...

In Preferences.swift
```
        defaultValues[.cacheAerials] = true
```

I'm closing this as you've fixed your issue.

**Closed by glouel** 2019-06-17 08:28 UTC
