### ISSUE TITLE
iMac won't sleep

### ISSUE THREAD

**Issue by rvconrad** [JohnCoates/Aerial#73] opened 2015-10-29 23:54 UTC
Since I installed your screen saver on my iMac running el capitan, mac will not sleep. Screensaver runs continuously

**Comment by alistairmcmillan** [comment] 2015-10-30 01:20
Duplicate of #23

**Comment by JohnCoates** [comment] 2015-10-30 10:00
Thanks alistairmcmillan for linking the original issue.

**Closed by JohnCoates** 2015-10-30 10:00 UTC
Labels: duplicate
