### ISSUE TITLE
Preferences Pane totally blank

### ISSUE THREAD

**Issue by Silmar-99** [JohnCoates/Aerial#1087] opened 2020-08-31 22:33 UTC
Hello,

I recently installed Aerial 2.0.4, I think, and everything was working fine.

Then I started looking into the Preferences and I opened the Cache menu. Suddenly, all the preferences disappeared, and it has been like that since.

Aerial companion installed, 2.0.5, 2.0.6, 2.0.7, but I still have the issue...

I un-installed Aerial, removed all files linked to it I could think about, re-installed it, even used "CleanMyMac X" to desinstall it, but the problem persist...

I, of course, rebooted my computer several times, since.

Also, when selecting Aerial, full closing the Preferences Pane, and re-opening it, "Flurry" is selected by default, and not Aerial.

I'm using the latest version of Mojave.

Any idea?

<img width="666" alt="Screen Shot 2020-08-31 at 17 24 42" src="https://user-images.githubusercontent.com/65128165/91774633-e3fbfa80-ebae-11ea-9255-9034179ef13d.png">

**Comment by glouel** [comment] 2020-08-31 22:51
Hey there, usually when things are like that, the panel crashed. This usually happen when there,s a really bad bug or some conflict with something else.

Can you launch console.app and look for a crash log maybe ?

**Comment by Silmar-99** [comment] 2020-08-31 23:21
Salut !

Something like [that...](https://www.dropbox.com/s/w9x1akqf9l6zceq/ScreenSaverEngine_2020-08-31-165800-1_Jeromes-iMac-R.crash?dl=0)

**Comment by glouel** [comment] 2020-09-01 10:31
A quick suggestion, please try : 

```
defaults write ~/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist hideFromTimeMachine 0
```

This may fix the issue.

**Comment by Silmar-99** [comment] 2020-09-01 10:58
Good morning Guillaume,

Following your instructions - and - removing the actual Preferences file fixed the issues (I didn't find this one before). Just removing access from TimeMachine didn't.

It worked twice as I was able to reproduce the bug and reset everything after that.

Clicking "Pick Folder" after checking the "Manually pick cache location" option, in the "Cache" option menu leads to the totally blank screen I showed before and it will stay like that until applying you method listed above.

**Comment by glouel** [comment] 2020-09-01 11:00
Awesome, thanks for troubleshooting this. I'll fix it tonight thanks !

**Comment by ruzickap** [comment] 2020-09-09 08:19
I do have a same issue on MacOS Catalina when selecting "Make Time Machine ignore the cache" in "Cache" preferences tab.

The commands (`defauts write ...`) above helped.

**Comment by glouel** [comment] 2020-09-13 17:31
I rewrote the whole Time Machine thing, instead of doing something stupid as I did (moving all the cache to Caches) I just add Aerial's cache to time machine's exclusion list (really should have done that from the beginning). 

You will need to enable that setting again for it to work, the checkbox is the same but the preference is reset (it's no longer really a preference, I literally ask time machine if our cache is excluded or not).

**Comment by ruzickap** [comment] 2020-09-14 15:35
I believe the issue was fixed in latest release `2.0.9`.

**Comment by glouel** [comment] 2020-09-14 17:14
Yep thanks for confirming @ruzickap and sorry for the issue in the first place!

**Closed by glouel** 2020-09-14 17:14 UTC

**Comment by squeeb** [comment] 2020-09-21 21:43
I think this bug needs to be reopened, I'm on version `2.0.9` installed via brew, and ran into exactly the same issue. 
I ticked the box to exclude from time machine and since then the preference pane remained blank. 
Uninstalling / reinstalling via homebrew or manually didn't help. 

Only fix was to run both those `defaults` commands above and reinstall using `brew cask reinstall aerial`

**Comment by glouel** [comment] 2020-09-22 08:48
> I think this bug needs to be reopened, I'm on version `2.0.9` installed via brew, and ran into exactly the same issue.
> I ticked the box to exclude from time machine and since then the preference pane remained blank.
> Uninstalling / reinstalling via homebrew or manually didn't help.

Did you also changed the cache directory and not just the Time Machine thing ? 

In 2.0.8, clicking Time Machine could definitely do this. But in 2.0.9 it should be harmless (completely different code/technique, I'm adding the exclusion via TMutil). Should you try again in 2.0.9 to just click that checkbox, it should be fine ? There's not even a preference to reset now in 2.0.9 for Time machine, it literally asks tmutil. 

But there's a lingering issue though with changing cache directory in 10.14 and below, and I could definitely see that being the cause of your crash.

**Comment by squeeb** [comment] 2020-09-22 09:15
Ah yes, 

I did change the cache directory to a separate mounted disk also. 

Apologies, I just recreated this behaviour too.

**Comment by glouel** [comment] 2020-09-22 09:16
> Ah yes,
> 
> I did change the cache directory to a separate mounted disk also.
> 
> Apologies, I just recreated this behaviour too.

Ok I definitely need to investigate that one, I'll try to dig a bit into it !

**Comment by Silmar-99** [comment] 2020-09-27 19:08
Good afternoon Guillaume,

The latest Security Update from Apple for Mojave totally crashed Aerial. Even with your suggestion above, deleting both Preference File I can find, the screen saver do not start anymore and the Configuration Panel crash systematically...

Any suggestion?

**Comment by glouel** [comment] 2020-09-27 19:22
Hey @Silmar-99 

Sadly I don't have any good one. It looks like that security update broke the ability to run Swift screen savers, it's not just Aerial. I gave more details here if you are curious : https://github.com/JohnCoates/Aerial/issues/1107#issuecomment-699004252

I've filled some radars with Apple (and encourage everyone to do so!) but there's not much I can do as the crash happens when the system tries to load a swift screensaver in an Objective-c to Swift library.
