### ISSUE TITLE
Bug report: Video shaking

### ISSUE THREAD

**Issue by iternety** [JohnCoates/Aerial#410] opened 2017-10-29 09:52 UTC
While the Aerial is playing the video, if I adjust the brightness by pressing F1 or F2, the video starts to shake immediately.

OS Version: 10.13
Device: MacBook Pro 15, Mid 2015

**Comment by alistairmcmillan** [comment] 2017-11-04 17:32
@iternety Can you try installing 10.13.1 and let us know if you still get the shaking?

**Comment by CupricWolf** [comment] 2017-11-04 21:26
macOS: 10.13.1 (17B48) Also mid 2015MBP. I still get shaking.

**Comment by Cavolo** [comment] 2017-11-05 10:47
10.13.2 Beta (17C60c) mid2017MBP, still shaking if run with intel display card

**Comment by alistairmcmillan** [comment] 2017-11-05 18:43
Seems to be a duplicate of #377 so closing as a duplicate.

**Comment by alistairmcmillan** [comment] 2017-11-05 18:44
@Cavolo @CupricWolf @iternety For the moment turn on the "Show with clock" option. That seems to fix the video glitches in High Sierra.

**Closed by alistairmcmillan** 2017-11-05 18:43 UTC
Labels: bug, duplicate
