### ISSUE TITLE
Accessibility Support Request: Info Page

### ISSUE THREAD

**Issue by ZV00** [JohnCoates/Aerial#981] opened 2020-05-02 18:31 UTC
Good afternoon, 

I wanted to request a slight accessibility tweak. Someone I am close with is red-green colorblind which makes me very aware of the issues of using red and green indicators, despite their constant use just about everywhere. 

As a result I wanted to request and recommend that the icons on the "Info" page be changed to better support those with colorblindness and make the app more accessible to them. 

<img width="780" alt="Screen Shot 2020-05-02 at 2 31 34 PM" src="https://user-images.githubusercontent.com/18543749/80872703-a2e7ee00-8c81-11ea-9ce8-ceadc4bfa166.png">

Potential options
- Use an open (unfilled) or closed (filled) circle to indicate on/off
- Use a different color scheme (green for on and some other color for off)
- Consider Enable/Disable indicators in the left hand list rather than inside each item
- Slide to right/left icons similar to a power switch

More information about adapting apps for colorblind individuals can be found easily, but one good article is: https://venngage.com/blog/color-blind-friendly-palette/

**Comment by glouel** [comment] 2020-05-04 13:35
Hi @ZV00 !

That sounds pretty reasonable. But I did model those on the Network settings in macOS System Preferences, which uses those exact system icons (which are bundled with macOS). I suppose you have issues with them too : 

![Capture d’écran 2020-05-04 à 15 16 54](https://user-images.githubusercontent.com/37544189/80969915-aa8eca80-8e1a-11ea-9384-d1d1beec79cc.jpg)
 
I'm wondering though, considering I'm using standard macOS icons, if the answer for  you is not in accessibility settings. There are actually colorblinds filters in macOS built in, I think I picked the right one in your case here : 

![Capture d’écran 2020-05-04 à 15 21 34](https://user-images.githubusercontent.com/37544189/80970280-3274d480-8e1b-11ea-820c-806770a979d0.jpg)

Should you enable it, it will also apply on Aerial's Info panel and the red will shift to purple which should be much easier to distinguish. 

So while I'm not against moving to something else, I'm a bit reluctant when I copied the supposedly best practices from macOS (although those are wildly varying and more inconsistent by the day) to stray away from them. 

Can you tell me if the macOS built in filters work for you ? And if not, why, so I get a better understanding.  

Regarding your suggestions:

> Use an open (unfilled) or closed (filled) circle to indicate on/off

Light/dark mode in macOS complicated this a lot, although that seems like the simplest solution

> Use a different color scheme (green for on and some other color for off)

I could see green against black/white (but same caveat as above).
 
> Consider Enable/Disable indicators in the left hand list rather than inside each item

Like a checkbox ? That's probably my least favorite because that's a lot of changes to code. 

> Slide to right/left icons similar to a power switch

That's too iOSy for me. I'm trying to keep it macOS like. 

All in all, the second one feels the best. The issue is dark/light mode and adding detection to switch the off icon if all of a sudden macOS switches from light to dark mode (if you enable the auto feature in settings). But please try the accessibility feature first.

**Comment by ZV00** [comment] 2020-05-04 14:40
Hey @glouel,

As this isn't specifically for me I can't speak to the accessibility settings working better, but I do recognize the conundrum that you have here. 

> So while I'm not against moving to something else, I'm a bit reluctant when I copied the supposedly best practices from macOS (although those are wildly varying and more inconsistent by the day) to stray away from them.

Your point here is 100% valid and makes me believe that you're probably doing the best possible here. 

I have one other thought that might be easy to code and also help do this after reading through your comments, however, I would totally understand if it's not worth the effort in your mind:

Could you simply re-organize the list on the left hand side and place a divider so that the top portion is "enabled" items and the bottom portion is "disabled" options? 
Even without the divider simply placing those that are enabled at the top might provide some differentiation without a need to change a significant amount of code? 
<img width="196" alt="Screen Shot 2020-05-04 at 10 39 57 AM" src="https://user-images.githubusercontent.com/18543749/80978093-9b485680-8df3-11ea-9a1e-8217d898465e.png">

**Comment by glouel** [comment] 2020-05-04 14:58
> Hey @glouel,
> 
> As this isn't specifically for me I can't speak to the accessibility settings working better, but I do recognize the conundrum that you have here.

I had read your post earlier on and thought about it but forgot it wasn't specifically about you, I had edited the post to reflect that but you probably missed my edit. 

I think the point still remains, can you try with that person to see if the feature I mentioned fixes it for them ? I think it's reasonable to expect someone with a need for this to use system's features when those are available. Mostly because while red/green I think may be the most common ones, there are many different colorblindnesses with different degrees so I kinda think macOS's filter, where you can manually dial the amount of color shift, is pretty good. And since it's pretty much everywhere in macOS (literally at the top left of every window) a global solution seems more appropriate. 

> I have one other thought that might be easy to code and also help do this after reading through your comments, however, I would totally understand if it's not worth the effort in your mind:
> 
> Could you simply re-organize the list on the left hand side and place a divider so that the top portion is "enabled" items and the bottom portion is "disabled" options?
> Even without the divider simply placing those that are enabled at the top might provide some differentiation without a need to change a significant amount of code?
> <img alt="Screen Shot 2020-05-04 at 10 39 57 AM" width="196" src="https://user-images.githubusercontent.com/18543749/80978093-9b485680-8df3-11ea-9a1e-8217d898465e.png">

This one is tricky because the order is meaningful, it's the order from top to bottom on screen. So say I have weather first but disable it, it goes to the pile at the bottom. What if I enable it again ? Does it go at the bottom of the green list ? There's a loss here in functionality compared to what we have currently.

One last thing, which version of macOS and which mac are you using ? I'm seing scroll bars on your first screenshot around Text settings, which definitely shouldn't be there.

**Comment by ZV00** [comment] 2020-05-07 23:41
> I think the point still remains, can you try with that person to see if the feature I mentioned fixes it for them ? I think it's reasonable to expect someone with a need for this to use system's features when those are available. Mostly because while red/green I think may be the most common ones, there are many different colorblindnesses with different degrees so I kinda think macOS's filter, where you can manually dial the amount of color shift, is pretty good. And since it's pretty much everywhere in macOS (literally at the top left of every window) a global solution seems more appropriate.

I am told that this doesn't seem to work great for them personally, but I cannot speak more broadly. 

> This one is tricky because the order is meaningful, it's the order from top to bottom on screen. So say I have weather first but disable it, it goes to the pile at the bottom. What if I enable it again ? Does it go at the bottom of the green list ? There's a loss here in functionality compared to what we have currently.

I didn't actually realize that the order was meaningful there... That's good to know for personal use, haha! I would expect that it would place the item at the bottom, any time it goes from disabled to enabled or visa versa, but that's just an assumption, I don't know what that actually looks like in terms of coding. 

> One last thing, which version of macOS and which mac are you using ? I'm seing scroll bars on your first screenshot around Text settings, which definitely shouldn't be there.

You are correct, the scroll bars appear over the text settings. I'm running 10.15.4 (19E287). See attached screenshots:

<img width="780" alt="Screen Shot 2020-05-07 at 7 38 39 PM" src="https://user-images.githubusercontent.com/18543749/81354851-a1ac2c00-909a-11ea-960e-3d58ae413512.png">
<img width="780" alt="Screen Shot 2020-05-07 at 7 38 22 PM" src="https://user-images.githubusercontent.com/18543749/81354852-a1ac2c00-909a-11ea-8888-305177dda3d5.png">

**Comment by glouel** [comment] 2020-05-25 14:16
@ZV00 I'll be closing this for the time being, 2.0.0 will bring some changes in how I handle that list which should alleviate the issue. The list will start empty, and you will be able to add new infos using + - buttons. This will be part of the ability to have multiple infos of the same type (mostly for things like message where it can be useful, or to configure different weather on different screens, etc). 

In the meantime, the scrollbar thing around text settings should be fixed in 1.9.0 !

**Closed by glouel** 2020-05-25 14:16 UTC
