### ISSUE TITLE
Strange rendering artifacts on Mac OS X High Sierra

### ISSUE THREAD

**Issue by gitchamp** [JohnCoates/Aerial#374] opened 2017-08-20 01:00 UTC
Is that a code update for compatibility with the public betas of Mac OS X High Sierra?

I get technicolor lines and bubbles when displaying the screensaver on the public betas (latest as of today).

**Comment by alistairmcmillan** [comment] 2017-09-05 23:23
Duplicate of #365

**Closed by alistairmcmillan** 2017-09-05 23:23 UTC
