### ISSUE TITLE
Aerial Screen saver

### ISSUE THREAD

**Issue by eddeemurfy** [JohnCoates/Aerial#396] opened 2017-10-05 10:48 UTC
Hi,

Ever since upgrading my software to High Sierra when the screen savers comes up there is a distorion on my screen like its an old school tv.

I think I'm going to delete the screen saver and add it again when its compatible with High Sierra

**Comment by alistairmcmillan** [comment] 2017-10-05 11:23
The screensaver is compatible with High Sierra. There seems to be a glitch in the High Sierra drivers for Intel chips on certain Macs.

Duplicate of #377. There is more discussion there.

**Closed by alistairmcmillan** 2017-10-05 11:23 UTC

**Comment by eddeemurfy** [comment] 2017-10-05 11:55
Okay thank you for the quick reply
