### ISSUE TITLE
"Offline" version for those with limited internet connectivity

### ISSUE THREAD

**Issue by damian-w** [JohnCoates/Aerial#46] opened 2015-10-28 14:08 UTC
Could there be any way to store the video files offline?

This project is absolutely stunning, but for an example here in Australia most of the population is limited to less than 300kb/s (which can't support streaming decent quality video).

Cheers!

**Comment by harule** [comment] 2015-10-28 14:31
YES, please add offline capability for people with slower connections, like me :P

**Comment by jpshelley** [comment] 2015-10-28 15:52
+1

**Comment by alistairmcmillan** [comment] 2015-10-28 17:49
Duplicate of #43

**Comment by yourtion** [comment] 2015-10-29 04:27
I already add a basic cache. You can try it on https://github.com/yourtion/Aerial .

Try to download this one https://github.com/yourtion/Aerial/releases/download/v1.2/Aerial.saver.zip

@damian-w @jpshelley @harule

**Comment by jpshelley** [comment] 2015-10-29 14:59
@yourtion I saw your PR, and I'd recommend following what @JohnCoates mentioned before I test it out.

**Comment by koengsen** [comment] 2015-10-29 15:40
:+1:

**Comment by dazorni** [comment] 2015-10-29 15:40
:+1:

**Comment by yourtion** [comment] 2015-10-30 02:11
I published a basic offline mode version. You can download and have a try. @jpshelley because the bad network and I work offline so the offline mode is needed.

https://github.com/yourtion/Aerial/releases/download/v1.3/Aerial.saver.zip

@koengsen @dazorni @damian-w @alistairmcmillan

**Comment by JohnCoates** [comment] 2015-10-30 03:24
I've added auto-caching as videos play https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta

I'll also be adding a button to cache everything at once

**Comment by jpshelley** [comment] 2015-10-30 15:17
Just tested out the new beta @JohnCoates. It is amazing. So much faster. Great work! :tada:

**Comment by koengsen** [comment] 2015-11-01 16:04
Thank you :) great stuff

**Comment by damian-w** [comment] 2015-11-05 09:32
Thank you kind sir!

**Comment by alistairmcmillan** [comment] 2016-01-28 21:38
Closing as duplicate of #43

**Closed by alistairmcmillan** 2016-01-28 21:38 UTC
Labels: duplicate
