### ISSUE TITLE
Screensaver not compatible with  macOs 10.12 Sierra

### ISSUE THREAD

**Issue by hintzsche** [JohnCoates/Aerial#292] opened 2016-12-28 17:01 UTC
Screensaver not compatible with macOs 10.12 Sierra

**Comment by alistairmcmillan** [comment] 2016-12-28 17:03
It's a bug in OSX/macOS.

The screensaver itself should launch and run okay.

The bug should just affect the preview in System Preferences. If you select Aerial, close System Preferences, then re-open System Preferences, you should find that the preview works okay.

Closing as a duplicate of #269 .

**Closed by alistairmcmillan** 2016-12-28 17:03 UTC
Labels: duplicate

**Comment by hintzsche** [comment] 2016-12-28 17:06
Thank you very much solved
