### ISSUE TITLE
High Sierra. 

### ISSUE THREAD

**Issue by asayf** [JohnCoates/Aerial#400] opened 2017-10-07 20:18 UTC
Hi, this doesn't work with MacOS High Sierra.

**Comment by alistairmcmillan** [comment] 2017-10-07 20:23
@asayf If you want someone assistance it really helps if you give more detail.

If you are getting corruption when the videos play, that's being discussed here #377 . It's a bug in the drivers for Intel chips in certain Mac laptops.

If you are getting an error message saying that the screen saver needs to be updated, then that's a long standing bug in macOS that's been there since Swift was released. Select the screensaver, close System Preferences, re-open it and it should play fine.

If you are just getting a blank screen then that's most likely a firewall/proxy issue. Try caching the videos or connecting through another network.

Aside from the above issues, the screensaver works fine in High Sierra.

**Comment by asayf** [comment] 2017-10-08 08:14
Hi @alistairmcmillan - yes, I'll give a little more context. As soon as I preview or 'hot corner' the screensaver, there's a glitch effect that appears after a second. I'm using a 2017 13" MacBook Pro with Touch ID.

**Comment by alistairmcmillan** [comment] 2017-10-08 20:40
@asayf Ah, thanks, that's the thing that's being discussed over in #377 .

Closing this as a duplicate of #377

**Closed by alistairmcmillan** 2017-10-08 20:40 UTC
