### ISSUE TITLE
Add ability to add third-party, "aerials"

### ISSUE THREAD

**Issue by jqnatividad** [JohnCoates/Aerial#139] opened 2015-11-04 19:09 UTC
For folks with drones, maybe they can submit PRs of own aerial videos here on GH, and then it gets exposed on the screensaver as selectable option when it calls home to gh-pages.

Only merged videos are made available to the screensaver.

**Comment by svozniuk** [comment] 2015-11-04 21:41
+1 for this.
being able to include something like this in a screensaver would be amazing
https://www.youtube.com/watch?v=6tmbeLTHC_0

**Comment by spangenberg-xx** [comment] 2015-11-04 23:12
YES! The ability to add in a list of Youtube video urls and randomize them would be amazing... There are some killer videos out there that would be great as screensavers.

**Comment by alistairmcmillan** [comment] 2015-11-04 23:18
Duplicate of #41

**Comment by spangenberg-xx** [comment] 2015-11-04 23:20
Ahh. Thank you Alistair MCmillan, but that doesn't have the option for Youtube videos...

so..... Not a duplicate.

**Comment by pritpalspall** [comment] 2015-11-05 09:54
i had the exact same thought last night with the sun youtube video

**Comment by mateusrevoredo** [comment] 2015-11-05 19:45
+1

**Comment by jqnatividad** [comment] 2015-12-14 20:38
Or just add the ability for the user to add custom videos using a simple interface.

Something similar to what Satellite Eyes does with custom basemaps
http://satelliteeyes.tomtaylor.co.uk/

**Comment by alistairmcmillan** [comment] 2016-01-28 21:29
Closing as duplicate of #41

**Closed by alistairmcmillan** 2016-01-28 21:29 UTC
Labels: duplicate
