### ISSUE TITLE
iMac won't sleep

### ISSUE THREAD

**Issue by CMDRN531** [JohnCoates/Aerial#38] opened 2015-10-28 03:11 UTC
Since installing the screensaver my computer will not shut down the display or sleep the HD. I have verified that all my power management settings are correct. I am running OS X El Capitan on a 2009 iMac 24". 
Thank you for porting this to Mac!

**Comment by BeardMan1** [comment] 2015-10-28 07:49
Same here. iMac Mid 2011, OS X 10.11.1 El Capitan.

**Comment by thibaudgg** [comment] 2015-10-28 07:50
Same issue on my MacBook Pro plugged to the Cinema Display. OS X 10.11.1 El Capitan.

**Comment by alistairmcmillan** [comment] 2015-10-28 08:24
Duplicate of #23

**Comment by JohnCoates** [comment] 2015-10-30 10:01
Thanks @alistairmcmillan for linking the original issue. I'm working on fixing this, but the solution I've found is quite complicated and will take a bit to implement.

**Closed by JohnCoates** 2015-10-30 10:01 UTC
