### ISSUE TITLE
vertical monitor is causing bad proportions

### ISSUE THREAD

**Issue by taylorferguson** [JohnCoates/Aerial#462] opened 2018-05-31 20:51 UTC

**Comment by Trotts** [comment] 2018-06-25 10:54
Also having this issue. When monitor is in vertical mode the screensaver plays in the middle of the screen with graphical issues on the sides of playback. 

MacBook Pro (13-inch, 2017)
Mac OS 10.13.5 (17F77)

**Comment by alistairmcmillan** [comment] 2018-07-31 12:53
Could either of you add a screenshot to show what you are experiencing?

**Comment by Trotts** [comment] 2018-08-03 09:28
Hi, 

Here is an image of what is experienced. This image shows no graphical glitching around the sides, however in more serious cases the image is stretched with extreme flickering and distortion around the edges rather than the black space.

![img_0829](https://user-images.githubusercontent.com/9531671/43635779-01c2607a-9708-11e8-8151-f38fdbecb78f.JPG)

**Comment by DanNordness** [comment] 2018-09-10 20:58
+1

**Comment by llahnoraa** [comment] 2018-10-11 19:35
That's strange. I am using iMac 5k and a vertical monitor (like the picture above my comment) and had no issue? I wondered if it had to do with the laptop?

**Comment by glouel** [comment] 2018-10-11 19:40
Since we are using System video playback with Aerial, many of these kinds of bugs may be linked to a specific version of MacOS. 

To those who still had issues, could you please recheck with version 1.4, and if you still see issues, give us which MacOS version you are using and any details that may help reproduce ?

**Comment by llahnoraa** [comment] 2018-10-11 19:47
I'm on 10.13.6 using iMac 5k and crappy Dell monitor (vertical). See picture attach and it worked as expected on latest 1.4. 

![img_0618](https://user-images.githubusercontent.com/732060/46829808-d21bcf00-cd6c-11e8-992a-8a3cd5728023.jpg)

**Comment by glouel** [comment] 2018-10-11 19:52
Thanks for your feedback and OS details, this will be helpful !

**Comment by glouel** [comment] 2018-10-16 17:39
Closing as fixed with the release of 1.4.1

**Closed by glouel** 2018-10-16 17:39 UTC
Labels: enhancement
