### ISSUE TITLE
Feature request:  Day / Date Option

### ISSUE THREAD

**Issue by amcclay** [JohnCoates/Aerial#954] opened 2020-03-23 03:27 UTC
Hi John,

First of all thank you so much for creating this screen saver.  It's come a long way since the first time I tried it!

This is going to be a life saver during the quarantine we have here in SF.

My one request which would be awesome is to add a date option.  The days are all blurring together while working from home, so it would be super helpful.

Basically like the Windows 10 lock screen.

Thanks!

#859 ### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment] 2020-03-23 12:31
Hi @amcclay (I'm the current maintainer) 

Adding an optional date should be pretty straightforward, on top of being a good idea ! I'll try to have a beta with it later today and will get back to you.

**Comment by glouel** [comment] 2020-03-23 16:26
@amcclay please give this beta a shot, you can configure the date in textual/compact mode and have the year or not (it should be localized too). 

![Capture d’écran 2020-03-23 à 15 47 23](https://user-images.githubusercontent.com/37544189/77338886-4660ed00-6d2b-11ea-8bb1-1191176cff12.jpg)

Beta here (close System Preferences before installing) : https://github.com/JohnCoates/Aerial/releases/download/v1.8.2beta4/Aerial.saver.zip

**Comment by amcclay** [comment] 2020-03-23 17:00
Hi Guillaume,

I can't thank you enough for A.) implementing this and B.) doing it within hours of me asking about it!  I've got it running on my Mac mini and it's absolutely perfect.  This will be my screen saver for the foreseeable future :)

On another note, do you have a PayPal account or some other means of donating to the project?

**Comment by glouel** [comment] 2020-03-23 17:04
@amcclay no problem, it truly was a good idea and it changed my mind a bit to work on Aerial today ;) 

It does look nice with your thin font by the way, which one is that ?

I do have a paypal link on the main repo page if you feel like it, no obligation, next to my name on the top section. I should make it more prominent but since we haven't transfered the repo it's not obvious. Take care !

**Comment by amcclay** [comment] 2020-03-23 17:12
Great.  Will be donating shortly.

The date font is HelveticaNeue-Thin 

Oh, if you do update it again anytime soon an, 'AM/PM' enable / disable option would make it so it could precisely replicate the windows 10 version :)

![Windows-10-Lockscreen-600x336](https://user-images.githubusercontent.com/15260379/77343403-da609380-6cee-11ea-88ce-676b4025ed33.jpg)

**Comment by glouel** [comment] 2020-03-23 17:37
> Great. Will be donating shortly.
> 
> The date font is HelveticaNeue-Thin

Thanks !

> Oh, if you do update it again anytime soon an, 'AM/PM' enable / disable option would make it so it could precisely replicate the windows 10 version :)
> 
> ![Windows-10-Lockscreen-600x336](https://user-images.githubusercontent.com/15260379/77343403-da609380-6cee-11ea-88ce-676b4025ed33.jpg)

So, right now, you should be getting the same format that you get in the top right corner of your Mac's menu bar. If you check my screenshot there's no AM/PM because of my locale (fr). You can change that easily though, if you go into MacOS's regional settings : 

<img width="892" alt="Capture d’écran 2020-03-23 à 18 32 48" src="https://user-images.githubusercontent.com/37544189/77345384-d2c3dd80-6d34-11ea-82f9-973bc307d2fe.png">

Check the box and you should get rid of AM/PM on both your menu and Aerial. 

Or did you want to keep the AM/PM time and but just remove the letters ? So for example 3PM, instead of 15:00, would show as 3:00 ? That seems weird but I'm no fan of the AM/PM thing to be honest, I'd be surprised if Microsoft does that ?

**Comment by amcclay** [comment] 2020-03-23 18:05
Hah. I had actually tried that first.  The Language / Region menu doesn't control the display of the actual 'AM / PM' text.  That is done in the 'Date & Time' panel - and unfortunately, it seems that turning off the display of AM/PM in date and time does not change it in Aerial. 

But yeah, basically I was hoping that rather than seeing 3:00 PM I could just see 3:00 (without a PM *or* AM) - Which is how the Windows lock screen shows it.

**Comment by glouel** [comment] 2020-03-23 18:13
I see, well that should be easy enough, I'll try to have a look tomorrow and let you know.

**Comment by glouel** [comment] 2020-03-23 19:03
I'm still a bit shocked that it's a thing (not showing AM/PM *and* not going 24h), it makes the whole AM/PM thing even more confusing to me ! But anyway, I made a quick build with the option to remove am/pm for you, I'm not releasing this as a beta but it will be in the next beta/release too, this one is just a test build for you : 

![Capture d’écran 2020-03-23 à 19 58 38](https://user-images.githubusercontent.com/37544189/77353375-2805ec00-6d41-11ea-981d-0bcc382289ae.jpg)

I'm not sure the checkbox text is really good and I'm open to ideas for improvements. But it should work, I did a quick check here: 

![Capture d’écran 2020-03-23 à 20 00 13](https://user-images.githubusercontent.com/37544189/77353415-36540800-6d41-11ea-9b9e-4e267e5c2697.jpg)

Build here : https://github.com/glouel/Aerial/releases/download/v1.8.2test5/Aerial.saver.zip

**Comment by amcclay** [comment] 2020-03-23 21:07
Thank you again!  Great work - Donation sent :) 

Oh, and this is *super* obsessive but for some reason the clock position seems further separated from the date then before (compared to previous screenshot - it sits higher). Maybe I'm imagining things :/ 
 
![Screen Shot 2020-03-23 at 1 56 05 PM](https://user-images.githubusercontent.com/15260379/77363192-7d290a00-6d0f-11ea-9907-c2800497ac7c.png)

**Comment by glouel** [comment] 2020-03-23 21:14
Thanks a lot !

Compared to your previous screenshot it looks like you made the fonts bigger, which generates a bit more spacing. I'm not 100% sure how I calculate the vertical margin, but I think it's proportional to the font sizes, I'll have another look tomorrow I tend to remember I made a few compromises around that.

**Comment by oxxie** [comment] 2020-03-24 17:07
Hi, sorry to chip in on this issue, but I'm afraid I've found a bug in the new Clock info: I'm on a 24h locale but the Clock is now displayed on 12h format and the 'Hide AM/PM (on 12hrs locals)' option is showing:

<img width="780" alt="image" src="https://user-images.githubusercontent.com/25564375/77455040-a6be6000-6df9-11ea-8469-30a3c48d1e41.png">
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/25564375/77455094-b8076c80-6df9-11ea-843d-5c9c0b3e2157.png">
<img width="780" alt="image" src="https://user-images.githubusercontent.com/25564375/77455142-c3f32e80-6df9-11ea-9510-cd442622121e.png">

Could it be that there's a mixup due to my particular setup: language=US, region=NL?

**Comment by glouel** [comment] 2020-03-24 17:22
@oxxie ha, yes, I changed a bit the Clock to get the AM/PM thing correct, but it looks like I may not have got it right for all setups, alas! 

Can you go into Advanced and tell me if you are using Preferred language, and what it says ? If you are on preferred, I think I'm picking that location (US) and because of that you get AM/PM. If you manually switch to, say, French, in advanced, you'll probably revert back to 24hr. Switching to English here will give you the US format too. 

A very simple workaround in the meantime would be for you to add English (UK) as your preferred regional setting, you'll keep english and get 24hr. I'll try to see if I can better detect edge cases such as yours automatically, and if not I'll add an option to force the clock to 24h.

**Comment by oxxie** [comment] 2020-03-24 17:40
Yes, you seem to be right: I am using the Preferred language option, which is en-US for me. Switching to nl-NL gives a 24h clock!

**Comment by glouel** [comment] 2020-03-24 17:43
Ok, please try English uk in the meantime if you want to have English and 24hr and I’ll try to get a fix tomorrow and get back to you !

**Comment by amcclay** [comment] 2020-03-24 19:50
Quick update on my end - I was indeed just using a different / bigger font and seeing different spacing as a result.  Thanks again :) 

Future feature request coming for possible local weather!

**Comment by glouel** [comment] 2020-03-24 19:55
> Quick update on my end - I was indeed just using a different / bigger font and seeing different spacing as a result. Thanks again :)

Great ! The spacing calculation is a bit weird as some is proportional to the font because it  seems to take into account space below the baseline, like even for number like 0123, it reserves spaces for things below (characters such as "pgq" etc which have a lower part). 
 
> Future feature request coming for possible local weather!

I don't know if there are free weather APIs out there that I could use for that (they seem to come and go) ? If you know any, why not.

**Comment by glouel** [comment] 2020-03-25 13:14
@oxxie : Can you try this build ? https://github.com/glouel/Aerial/releases/download/v1.8.3test1/Aerial.saver.zip

I reverted to the old "correct" way for the clock to get the locale. The reason I changed it is that localization is broken in Catalina for screensavers. To give you an example, with full french macOS (locale + region), my "correct" locale is reported as en_FR, so if I use that to display the date, it will show in english despite my locale (and the same for everyone else that do not use an english locale). So I kinda cheat by taking the first preferred language and use that. 

So I still do that for the date, but don't for the clock (where en_FR is equivalent to fr_FR), and that *should* be fine for everyone on every case, but I'm not 100% sure. Hopefully I got it right, please let me know.

**Comment by oxxie** [comment] 2020-03-25 16:02
Yes, it seems to do the trick, thanks! Only suggestion I have: remove the 'Hide AM/PM (on 12hr locals)' option for 24hrs locales.

**Comment by glouel** [comment] 2020-03-25 19:22
> Yes, it seems to do the trick, thanks! Only suggestion I have: remove the 'Hide AM/PM (on 12hr locals)' option for 24hrs locales.

Thanks for confirming ! And yep I should be able to check for a M in a test time string to see if we're in 24hrs locales or not (since the "normal" thing won't work). Will have a look that would be a decent improvement :)

**Comment by PatTheMav** [comment] 2020-03-27 15:29
@glouel I have another "bug" for you right here - my macOS is set to German (no other language installed) and 24hr clock, but for personal preference I set the screensaver to English, which seems to "enforce" the 12-hour clock format.

Only issue is I'd very much like to keep a 24-hour clock, but the English captions as well. Doesn't seem to work even with the test version you linked above.. 😕

**Comment by glouel** [comment] 2020-03-27 15:41
@PatTheMav I can confirm, switching will do that as I also need to switch the language of the date thing, so you don't get your location in english and your date spelled out in german...

I guess the only proper way to fix that would be an override in the Clock Info where you can set 12/24h, that would definitely fix it for pretty much every case I guess.

**Comment by PatTheMav** [comment] 2020-03-27 15:43
@glouel Yeah, there's a good reason why decades of developers have collectively thrown their hands in the air and said "fine, have a configurable switch then!".

Time, locals and timezones are the stuff of nightmares. 😄

**Comment by glouel** [comment] 2020-03-27 15:45
Especially when localization is broken in Catalina and I can't correctly detect anything anyway ! 

I'll try and add that switch and let you know ;)

**Comment by glouel** [comment] 2020-03-27 16:19
@PatTheMav  : https://github.com/glouel/Aerial/releases/download/v1.8.3test2/Aerial.saver.zip

**Comment by PatTheMav** [comment] 2020-03-27 16:21
@glouel Looks fine - English captions and 24-hour clock (so locale's clock format is automatically detected).

**Comment by glouel** [comment] 2020-04-09 18:20
> Future feature request coming for possible local weather!

@amcclay So back when you posted this I looked at a lot (way too many) of APIs that could work with a non-server, distributed open source package. Pretty much all the APIs out there have free tiers but none were compatible with Aerial (having limits I couldn't control). Yahoo has the only API that seemed compatible. I applied then, and just got approval so I'll try to implement their API in next version. You can track progress there as to keep things separated : https://github.com/JohnCoates/Aerial/issues/960#issue-597465705

**Comment by glouel** [comment] 2020-04-18 18:11
Closing this now with the release of 1.8.3beta1 with weathe, and also includes the various fixes from the test versions.

**Closed by glouel** 2020-04-18 18:11 UTC
Labels: enhancement, fix inside
