### ISSUE TITLE
Feature Request: Fade Transitions

### ISSUE THREAD

**Issue by jmcquillan** [JohnCoates/Aerial#117] opened 2015-11-01 19:18 UTC
To make the transition between videos smoother, a video should fade in when starting and fade out when ending.

**Comment by DJay1** [comment] 2015-11-01 21:07
LOL.. Also same Idea. :+1:  Would love to see this in a next update.

**Comment by alistairmcmillan** [comment] 2015-11-02 10:18
Duplicate of #40

**Closed** 2015-11-02 16:39 UTC
