### ISSUE TITLE
New screen savers - can you add support?

### ISSUE THREAD

**Issue by Niiix** [JohnCoates/Aerial#279] opened 2016-12-18 09:25 UTC
http://www.macrumors.com/2016/12/16/apple-tv-new-aerial-screen-savers/

Thanks!

**Comment by alistairmcmillan** [comment] 2016-12-18 09:45
John's screensaver should pick up the new aerial movies automatically. If they don't please check you're on the latest version and make sure the screen saver isn't being blocked by a firewall or proxy.

Duplicate of #276.

**Closed by alistairmcmillan** 2016-12-18 09:45 UTC
