### ISSUE TITLE
Screen Saver Options won't close

### ISSUE THREAD

**Issue by joshuapekera** [JohnCoates/Aerial#508] opened 2018-09-27 19:48 UTC
## Screen Saver Options won't close
Minor issue, but after opening the Screen Saver Options from System Preferences, the done button does not close the Options view. This causes the System Preferences app to hang and not close unless you use a force quit. This started happening after the latest Mojave OS update.

**Comment by glouel** [comment] 2018-09-28 10:49
Duplicate of https://github.com/JohnCoates/Aerial/issues/494

See there for a beta with the fix https://github.com/JohnCoates/Aerial/issues/463#issuecomment-424697712

**Comment by glouel** [comment] 2018-09-28 13:20
Fixed in 1.4b9 : https://github.com/JohnCoates/Aerial/releases/tag/v1.4beta9

**Closed by glouel** 2018-09-28 13:20 UTC
