### ISSUE TITLE
Would love the ability to choose screensaver to run at a certain time of day

### ISSUE THREAD

**Issue by darrinsden** [JohnCoates/Aerial#338] opened 2017-04-10 20:18 UTC
IE, to be able to choose sets of favorites
like only night time screensaver to be shown at night

**Comment by steve1412** [comment] 2017-04-16 00:34
Yeah same here. I think I've posted a thread regards to this before and someone else too. Don't think we've got an update on that just yet.

**Comment by alistairmcmillan** [comment] 2017-04-17 20:43
Duplicate of #11

**Closed by alistairmcmillan** 2017-04-17 20:43 UTC
Labels: duplicate
