### ISSUE TITLE
Feature request - Display video based on current time

### ISSUE THREAD

**Issue by grahamearley** [JohnCoates/Aerial#260] opened 2016-09-09 15:39 UTC
Would be cool if we could set a cutoff for day and night times and have the screensaver only display Night videos past a certain time and Day videos otherwise.

**Comment by mpbzh** [comment] 2016-09-16 16:20
Duplicate of #11

**Comment by alistairmcmillan** [comment] 2016-09-17 05:05
Closing as duplicate.

**Closed by alistairmcmillan** 2016-09-17 05:05 UTC
Labels: duplicate
