### ISSUE TITLE
After an hour or so, Ariel Screen Screen Saver goes black with the exception of overlays (such as video location, date, time, weather etc).

### ISSUE THREAD

**Issue by RGM1956** [JohnCoates/Aerial#1322] opened 2023-09-20 15:30 UTC
2021 24" 4-Port iMac
macOS 13.5.2 (22G91)
Aerial Companion 1.5.0b9
Aerial 3.2.6

After an hour or so, Ariel Screen Screen Saver screen goes black with the exception of overlays (such as video location, date, time, weather etc).  Nothing else displays.

**Comment by glouel** [comment] 2023-10-02 15:36
What settings do you have in Lock Screen in System Settings ?

**Comment by RGM1956** [comment] 2023-10-02 15:38
None of them were modified, default. However, it may be a moot point for the time being as I am now running macOS Sonoma. On Oct 2, 2023, at 8:36 AM, Guillaume Louel ***@***.***> wrote:﻿
What settings do you have in Lock Screen in System Settings ?

**Comment by glouel** [comment] 2023-10-02 15:44
Well, I'm pretty sure the default is to stop the screensaver and put your mac to sleep after one hour. It's up to macOS usually to kill the screensaver (we're just passive into this). However they keep breaking things and we've had to adda workaround for something like this in Sonoma, so it's possible that bug was backported somehow to 13.5.2.

Let me know if you have issues with Sonoma, Aerial force kills itself now under Sonoma to workaround stuff like this.

**Comment by davidpurnell** [comment] 2023-10-03 14:37
I'm seeing this same behavior on Sonoma...

**Comment by glouel** [comment] 2023-10-03 14:44
@davidpurnell would be great to get more details about your Lock Screen settings perhaps ? Also which version are you running ? 

@RGM1956 I just saw you are using 3.2.6, please update to latest version which I belive contains a fix for this.

**Comment by davidpurnell** [comment] 2023-10-03 14:56
> @davidpurnell would be great to get more details about your Lock Screen settings perhaps ? Also which version are you running ?

I'm running version 3.3.1 on Sonoma 14.0 (23A344)

Here's a screenshot of my Lock Screen settings. 

<img width="489" alt="Screenshot 2023-10-03 at 10 51 05 AM" src="https://github.com/JohnCoates/Aerial/assets/23176804/4dc41aff-82ea-46db-921e-932512734fa4">

I think this has only been happening for a couple of days now. Unlike OP, I actually don't see any overlays (I have clock and location enabled), I just get black screens (I have 3 monitors).

I haven't yet tried a reboot. Switching to another saver and then back to aerial has no effect.

**Comment by glouel** [comment] 2023-10-03 15:05
So you get black screens after 20 mins and your mac doesn't go to sleep ? Is this all the time or some of the time ? 

3.3.1 kills the screensaver to prevent that to happen and it seemed to work fine during the beta, but it seems that for some people their mac don't go to sleep for some reason. Does it just never goes to sleep ? Even after some more time ? 

Right now, macOS sends a system wide message saying the mac is going to sleep, so that's when Aerial kills itself (it used to be that macOS would do it prior to Sonoma but they broke that). I'm not sure why it then doesn't go to sleep as it should. 

There's a lot of weird bugs that we had to workaround during the beta, I'm not sure exactly what is happening here but I'll try to investigate. In general, comparing with "other" screensavers doesn't mean anything unless you try a 3rd party screen saver, as we are treated differently by Apple and this is the root cause of all issues. 

If you have a sec, can you try Electric Sheep for example, see if you have the same issue ?  https://electricsheep.org/#/download

It may help me narrow things down a bit. Thanks!

**Comment by davidpurnell** [comment] 2023-10-03 15:26
No problems with sleep. Machine sleeps at the 20 minute mark.  I get black screens when the saver kicks in after 5 minutes of inactivity but also if I manually start the saver (from a hot corner or when clicking "preview" in the Screen Saver settings)

I've also got xscreensaver installed and it exhibits the same behavior as Aerial.

**Comment by glouel** [comment] 2023-10-03 15:28
@davidpurnell ok thanks for the clarification, I think this is a separate issue from what op was having.

I'm still not super clear on when exactly you have the black screens though. Do they appear *immediately* when you start the screen saver ?? So like, Aerial (or xcreensaver) never starts ? Is this what you get ?? If so let's split this conversation in a separate issue.

**Comment by davidpurnell** [comment] 2023-10-03 15:51
yes, black screens happen immediately when I start the screensaver.

I'm assuming that the saver is actually running just not displaying anything but perhaps it's not even running and macOS is just blanking the screens and thus this might be a completely separate issue. 

Just finishing up a project with lots of open documents and such so I should be able to try a reboot soon.

**Closed** 2023-10-18 13:31 UTC
