### ISSUE TITLE
Not fullscreen on both monitors

### ISSUE THREAD

**Issue by adminjwilson** [JohnCoates/Aerial#484] opened 2018-08-01 17:49 UTC
On my MacBook Air 2017 running latest running macOS 10.13.6 when I am connected to an external monitor (at native 2560x1440) the screensaver is fullscreen on the external monitor but on the primary display (at native 1440x900) it is surrounded in black bars (horizontal and vertical). When I disconnect from the external display the screensaver fills the primary display.

**Comment by mcfattydk** [comment] 2018-08-02 12:51
Same here!

**Comment by JanKissing** [comment] 2018-08-08 18:35
Same problem!

**Comment by alistairmcmillan** [comment] 2018-08-21 10:09
Duplicate of #472

**Closed by alistairmcmillan** 2018-08-21 10:09 UTC
