### ISSUE TITLE
does't work on OS X 10.11.4 beta6 (15E61b)

### ISSUE THREAD

**Issue by loricheung** [JohnCoates/Aerial#219] opened 2016-03-13 14:02 UTC
there's no optional item for select in screen saver options

**Comment by alistairmcmillan** [comment] 2016-04-17 17:29
Hi @lorichueng could you give us more information on the problem you are seeing?

**Comment by leochenfc** [comment] 2016-07-14 08:01
Just cannot work. I am 10.11.4 beta6 , too.

**Comment by alistairmcmillan** [comment] 2016-07-14 08:16
@leochenfc What do you mean cannot work? Do you get an error that says "You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver."?

If so it's a bug in OS X. But it only affects the preview in System Preferences. The screensaver will actually work okay when it launches itself. If you see this error in System Preferences, select Aerial, close System Preferences and then reopen it. The preview will then work too.

You can read more here.
http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by leochenfc** [comment] 2016-07-14 08:25
I redownload the stable version and reinstall. It works fine! Thanks.

**Comment by alistairmcmillan** [comment] 2016-07-14 08:38
If it was just that error then you should really use the latest beta. The error isn't caused by a bug in the screensaver. It's a bug in OS X. And the latest beta of the screensaver offers a number of fixes and features.

**Comment by loricheung** [comment] 2016-07-15 01:50
sorry for long time with no reply.
maybe it's just the bug on OSX . Now , I upgrade it to 10.11.6 Beta , Aerial works fine

**Comment by alistairmcmillan** [comment] 2016-07-15 09:23
Glad to hear it's working for both of you. Closing.

**Closed by alistairmcmillan** 2016-07-15 09:23 UTC
