### ISSUE TITLE
Screensaver is cropped and glitches with the Clock Option Off OS 10.13.2

### ISSUE THREAD

**Issue by dirofphoto** [JohnCoates/Aerial#438] opened 2018-01-24 00:57 UTC

**Comment by dirofphoto** [comment] 2018-01-24 00:59
Screensaver is cropped and glitches with the Clock Option Off OS 10.13.2.  Seems to work with the clock on but is cropped at top and bottom with freeze fames behind and glitches inside the screen.

**Comment by jonnymywigga** [comment] 2018-01-26 11:26
I have the same problem on OS 10.13.3, It's  fine with the clock but without it looks like static from an old tv. 
![img_9168](https://user-images.githubusercontent.com/35837340/35437743-12839d38-0294-11e8-9816-ab51484e5905.JPG)

**Comment by catalandres** [comment] 2018-01-29 07:14
+1
Same problem. Enabling the clock fixes it.

**Comment by alistairmcmillan** [comment] 2018-01-29 10:38
Duplicate of #377

**Closed by alistairmcmillan** 2018-01-29 10:38 UTC
Labels: duplicate
