### ISSUE TITLE
Not working at all macOS High Sierra

### ISSUE THREAD

**Issue by mjacobs5** [JohnCoates/Aerial#416] opened 2017-11-09 23:32 UTC
The screensaver is not playing at all. Getting a black screen when the screensaver should be running

**Comment by alistairmcmillan** [comment] 2017-11-09 23:40
@mjacobs5 No preview is most likely a firewall/proxy issue. Make sure you aren't behind a firewall or proxy that could be blocking your access to Apple's servers or their CDN's servers. Make sure you don't have something on your Mac that is blocking access like Little Snitch for example.

If you are on a MacBook try connecting to a different network and caching the files.

You can also try opening the following links in a web browser to see if they are being blocked.

http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov

http://a1.v2.phobos.apple.com.edgesuite.net/us/r1000/000/Features/atv/AutumnResources/videos/comp_GL_G004_C010_v03_6Mbps.mov

Please let us know how you are getting on.

**Comment by mjacobs5** [comment] 2017-11-09 23:44
Links play fine. Not behind a firewall or proxy. Everything worked until I upgraded to the new macOS. only running Malwarebytes nothing else.

Mark

**Comment by alistairmcmillan** [comment] 2017-11-09 23:57
@mjacobs5 Is there anything in the `/Users/YOURUSERNAME/Library/Cache/Aerial` folder?

Is this list in the options populated with locations, day/night and numbers?

<img width="154" alt="screenshot 2017-11-09 23 55 48" src="https://user-images.githubusercontent.com/125896/32635797-b26fb138-c5a9-11e7-81ce-8e9a2119181e.png">

**Comment by mjacobs5** [comment] 2017-11-10 00:28
Yes all videos were downloaded and yes on options

**Comment by RudolphShin** [comment] 2017-11-10 02:40
I'm same problem
~/Library/Caches/Aerial Folder not exist.
Create folder. everything fine.

**Comment by alistairmcmillan** [comment] 2017-11-10 07:18
@mjacobs5 Try ticking the "Show with clock" option. Does it work then?

**Comment by mjacobs5** [comment] 2017-11-10 12:23
that worked

**Comment by gellert** [comment] 2017-11-10 15:29
"Show with clock" +1 !

**Comment by alistairmcmillan** [comment] 2017-11-11 18:32
Problem fixed for @mjacobs5. Closing. Duplicate of #377

**Closed by alistairmcmillan** 2017-11-11 18:32 UTC
