### ISSUE TITLE
Both original file and newest beta has video start and then immediately freeze on El Capitan OS X 10.11.6

### ISSUE THREAD

**Issue by SuperGitty** [JohnCoates/Aerial#249] opened 2016-07-31 10:02 UTC
(Both the original linked file and the new beta)

The screensaver still freezes, whether doing mirroring or separate videos for separate displays. It will start the video and then just freeze the video image. Sometimes the middle display will show the full video for some of the videos but never on either extended displays (which I have 2 other running).

Running:
iMac (27-inch, Mid 2011)
OS X El Capitan 10.11.6
3.1 GHz Intel Core i5
4 GB 1333 MHz DDR3 RAM
AMD Radeon HD 6970M 1024MB

**Comment by alistairmcmillan** [comment] 2016-08-02 14:16
Closing as duplicate of comments on #233.

**Closed by alistairmcmillan** 2016-08-02 14:16 UTC
