### ISSUE TITLE
Screensaver activates / overwrites keep awake rules

### ISSUE THREAD

**Issue by cocos2dbeginner** [JohnCoates/Aerial#1233] opened 2022-03-10 21:53 UTC
- [ ] Mac model: M1 Pro MacBookPro 16"
- [ ] macOS version: 12.2.1
- [ ] Monitor setup: LG 32UN650-W Monitor 32"

Currently the screensaver kicks in after maybe 10 minutes but I don't know why. I disabled the checkbox in Settings > Screensaver.

Desired state: Only activate the screensaver manually by using a hot corner. It should not activate itself after any given idle time.

Is there a specific setting I have to check here?

I'm using Amphetamine to keep my Mac awake as well, but it seems like that Aerial somehow overwrites it.

**Comment by glouel** [comment] 2022-03-11 18:55
Hey @cocos2dbeginner 

Just to clarify, it's macOS that starts your screensaver, Aerial doesn't start (nor stop) by itself. If you see Aerial starting up, then you should see any other screensaver starting up in the same conditions, the screensaver is just a plugin for a macOS system thing called ScreenSaverEngine.

I'm not sure I understand exactly what you are doing with Amphetamine as I'm not familiar with that utility. 

Can you double check your settings in System Preferences > Battery, what did you set in there for screen off ? You may need to push it all the way to the right, it's possible there's an interaction. 

If not I would suggest temporarily trying another screensaver, but I'm 99.99% sure the issue is not Aerial starting by itself, because it just can't do that on it's own. 

Sorry if that's not super helpful, but that's all I can think off right now. You also may want to try changing the duration where you disabled the checkbox, there are so many bugs around the screensaver system that maybe that checkbox doesn't work in that version of macOS ?

**Comment by glouel** [comment] 2022-08-16 17:23
Closing this, please reopen if you need more assistance

**Closed by glouel** 2022-08-16 17:23 UTC
