### ISSUE TITLE
Can not type in fields

### ISSUE THREAD

**Issue by thomasche** [JohnCoates/Aerial#606] opened 2018-10-30 10:57 UTC
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: MacBook Pro (Retina, 15-inch, Mid 2015)
- [x] macOS version: mac os High Sierra 10.13.6 (17G3020)
- [x] Monitor setup: no extra monitor

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Hi,
I can not type anything in the fields of Aerial's setting. For exemple here, I can not change the margins to corner:
<img width="780" alt="screen shot 2018-10-30 at 11 55 46" src="https://user-images.githubusercontent.com/18555577/47713521-c79d7880-dc3a-11e8-842d-7fa6907d22f3.png">

Here are the logs: 
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/2529282/AerialLog.txt)

Thanks in advance for your help.

**Comment by glouel** [comment] 2018-10-30 11:15
Hi @thomasche, this seems to happen for some (maybe all ? unsure) users of high sierra, I did notice it myself and asked around about it here : 
https://github.com/JohnCoates/Aerial/issues/586

I'll try to get some more feedback as I'm not sure it's a bug for everyone on 10.13.6 (it's definitely not happening on Mojave). For some reason it lookds like we don't have focus, which makes the textfields unusable (so margins, custom message, brightness time and custom coordinates off the top of my head).

I currently have no workaround for this but if you really want to fix something manually, you can edit the preferences .plist easily if you have Xcode to change those settings.

The plist can be found here : 

`~/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist`

The parameters should be pretty self explanatory, if you need more help with this workaround just ask ! I'll try to ask some of our other users on 10.13.6.

**Comment by glouel** [comment] 2018-10-31 19:14
As a workaround to this bug, starting with 1.4.5 beta 2, I provide an additional download, AerialConfig.app. This app is a standalone version of the Aerial configuration pane that you see in System Preferences. You can use this standalone App to configure Aerial instead of the System Preferences panel if you have issues with it. 

The file is AerialConfig.app.zip, you'll need to install the same version of the screensaver for things to work smootly. @thomasche can you get both files and give this a try please ?

https://github.com/JohnCoates/Aerial/releases/tag/v1.4.5beta2

**Comment by glouel** [comment] 2018-11-01 10:46
(I'm trying an alternative method that may remove the need for this, we'll see)

**Comment by SeanMSmith** [comment] 2018-11-01 22:01
Aerial 1.4.5 beta 3
mas OS High Sierra 10.13.6
iMac17,1 (Retina 5K, 27-inch, Late 2015)

The first time I tried to enter coordinates manually, I typed "-70" into the Latitude field, then (if I recall correctly), I changed focus (either by clicking somewhere else or by Command-Tabbing), and immediately System Preferences unexpectedly quit.

Thereafter, System Preferences unexpectedly quit every time I opened it and selected Aerial, until I deleted Aerial's preferences file.

I have not yet been able to reproduce this bug.

**Comment by glouel** [comment] 2018-11-01 22:14
Reproduced, nice catch ! I think that in some extreme case the dawn/dusk simply don't happen which led to the crash.

**Comment by glouel** [comment] 2018-11-01 22:30
@SeanMSmith beta 4 just for you : 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.5beta4/Aerial.saver.zip

Thanks for catching that one ! The tooltips are also there, but not the dark mode changes.

**Comment by dVIAN13** [comment] 2018-11-01 23:54
@glouel sorry to report something else.. didn't think it needed a new issue... in the screenshot below, you will see that when you are scrolling the main video list, if you hover the cursor over the scrollbar to click and drag, it's VERY close to the 4k tags... just a suggestion to move the tags, or increase box size to allow a little more room there... as it overlaps.. 😉 

<img width="667" alt="screen shot 2018-11-01 at 4 50 37 pm" src="https://user-images.githubusercontent.com/22992333/47886337-a4b7c380-ddf6-11e8-979f-812f9c53c652.png">

**Comment by glouel** [comment] 2018-11-02 00:04
Oh ! Yeah for click and drag, I calibrated that for just regular scrolling. I actually didn't know that the bar gets thicker, the things you miss despite using everyday !

I guess I can add/move a few pixels yep, looks like 3/4 points, I'll check that for next build thanks !

**Comment by dVIAN13** [comment] 2018-11-02 00:06
no prob.. just noticed it myself! good looking out!

**Comment by SeanMSmith** [comment] 2018-11-02 00:31
So after having trashed my Aerial prefs, Aerial 1.4.5 beta 4 does not recognize that I already have all the videos cached. (I see + marks next to all the video names in the Videos pane, and upon clicking "Download Now" in the Cache pane, Aerial is now happily download all 19.07 GB of videos again.)

**Comment by SeanMSmith** [comment] 2018-11-02 00:42
What happens when the user enters coordinates where Aerial is able to calculate sunrise or sunset near an equinox, and then becomes unable to as the current date approaches a solstice?

On a related note re extreme latitudes, this will probably not affect many users, but would it be possible to display another message than "Can't process your coordinates, please verify" when the user has entered valid coordinates but is too far north or south to calculate sunrise and sunset or dawn and dusk? (Something like "No sunrise and sunset at your latitude!" or "No dawn or dusk at your latitude!")

**Comment by glouel** [comment] 2018-11-02 00:55
> So after having trashed my Aerial prefs, Aerial 1.4.5 beta 4 does not recognize that I already have all the videos cached. (I see + marks next to all the video names in the Videos pane, and upon clicking "Download Now" in the Cache pane, Aerial is now happily download all 19.07 GB of videos again.)

Urgh, that's not good at all, really really sorry about that. Did you trash the videos too ??? Because, the preferences just have the path to the cache, so unless you did change the Aerial path earlier, it should pick up your videos at startup (it's completely independant from the pref, it checks if files are there or not fairly often). Can you check why the path is different maybe ? 

> On a related note re extreme latitudes, this will probably not affect many users, but would it be possible to display another error message than "Can't process your coordinates, please verify" when the user has entered valid coordinates but is too far north or south to calculate sunrise and sunset or dawn and dusk? (Something like "No sunrise or sunset at your latitude!" or "No dawn or dusk at your latitude!")

I definitely can do that, I do check precisely for the error for each, I just pasted the same text on all. 

> But then what happens when the user enters coordinates where Aerial is able to calculate sunrise or sunset near an equinox, and then becomes unable to as the current date approaches a solstice (either to Aerial's error checking, or to the text of this error message)?

If the calculation fails for some reason, then Aerial goes back to default mode not restraining to anything. I think it's sensible ?

**Comment by SeanMSmith** [comment] 2018-11-02 01:05
No, I hadn't trashed the videos, nor had I changed the cache path. (And when Aerial started downloading all the videos again, I checked Aerial's prefs to insure that it was still pointing to ~/Library/Caches/Aerial, and it was.) Aerial just didn't pick up the fact that all the videos were already there.

I've got plenty of bandwidth here and no data cap, so it's no big deal for me, but of course it might be for some other users.

> If the calculation fails for some reason, then Aerial goes back to default mode not restraining to anything. I think it's sensible ?

Yes, that seems reasonable.

**Comment by glouel** [comment] 2018-11-02 01:08
> No, I hadn't trashed the videos, nor had I changed the cache path. (And when Aerial started downloading all the videos again, I checked Aerial's prefs to insure that it was still pointing to ~/Library/Caches/Aerial, and it was.) Aerial just didn't pick up the fact that all the videos were already there.
> 
> I've got plenty of bandwidth here and no data cap, so it's no big deal for me, but of course it might be for some other users.

Can you look at the folder while it downloads ? I'm just puzzled at what can be happening, because I doubt it can overwrite over your existing files, it should probably fail... I don't get it. Even when you click download, it's going to check if the file is there, super weird.

**Comment by SeanMSmith** [comment] 2018-11-02 01:13
Doh! Now I understand what that happened. Trashing Aerial's prefs reset my preferred video format to 1080p H264; it was previously 4K HEVC. Aerial was downloading the lower-res versions.

Sorry for the false alarm.  :)

**Comment by glouel** [comment] 2018-11-02 01:17
Haaaa of course ! Well good to have that one solved, would have puzzled me for a while 😅

**Comment by glouel** [comment] 2018-11-03 13:33
Closing as fixed in 1.4.5

**Closed by glouel** 2018-11-03 13:33 UTC
Labels: bug, fix inside, high sierra
