### ISSUE TITLE
No Aerial plays when clicking Preview button

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#548] opened 2018-10-18 02:05 UTC
In Aerial 1.4.1 running under macOS 10.13.6, when I click the Preview button in the Screen Saver pane of System Preferences, the screen goes dark, but no video plays.

The video does play in the thumbnail of the Screen Saver pane, and also when activating the screen saver (e.g. by using a hot corner), just not when clicking the Preview button.

Previews of other screen savers play as expected when I click the Preview button, just not of Aerial.

This problem did not appear with Aerial 1.4 and is new to Aerial 1.4.1.

**Comment by glouel** [comment] 2018-10-18 08:56
I've seen a blank preview (before entering Aerial proper) a couple of times, that's probably linked to that. I'll have a look thanks ! Are you mirroring to multi monitors for the record ?

**Comment by SeanMSmith** [comment] 2018-10-18 09:28
No, I'm using just the built-in display on my iMac, and Aerial is set to play Aerials "Only on Main Display".

**Comment by glouel** [comment] 2018-10-18 09:37
Might be some changes I made for Main display only, maybe mirror (which was the default) always work. Thanks I'll have a look.

**Comment by glouel** [comment] 2018-10-18 16:07
I found why that happens, although quite crazily I can only reproduce it on my MBA on 10.13.6. For some reason, only on that machine it reuses the same AerialView than the mini preview for the large preview. But not on my iMac on Mojave. 

I'm trying to pull the threads on all this, bit of cleanup, I might break things 😱

**Comment by glouel** [comment] 2018-10-18 18:55
It's a bit of a mess but I think I got something somewhat sane now. Also with proper retina detection (it would probably be pixelated if retina was not main), better start sync, I did see a mess on my MBA if I let the preview play to the end, still need to track that, but otherwise should be better : 
https://github.com/glouel/Aerial/releases/download/v1.4.2test4/Aerial.saver.zip

**Comment by SeanMSmith** [comment] 2018-10-19 04:40
I confirm that Aerial 1.4.2 test 6 (I've not tested test 4 or 5) corrects this problem for me.

Thank you!

**Comment by glouel** [comment] 2018-10-19 10:03
Awesome thanks, I'll keep this open until I get 1.4.2 out.

**Comment by SeanMSmith** [comment] 2018-10-20 06:41
In 1.4.2 test 7, I'm now noticing that the full-screen preview plays the **_first_** time I click the Preview button, but not the second or subsequent times. (I don't know if this is a change in behavior from test 6, or if I just didn't test test 6 adequately.)

**Comment by glouel** [comment] 2018-10-20 10:16
Oh yes that's very possible I break that I'll have a look, thanks !

**Comment by glouel** [comment] 2018-10-21 10:05
> In 1.4.2 test 7, I'm now noticing that the full-screen preview plays the **_first_** time I click the Preview button, but not the second or subsequent times. (I don't know if this is a change in behavior from test 6, or if I just didn't test test 6 adequately.)

Just double checked it's fixed in b1

**Closed by glouel** 2018-10-21 10:05 UTC
Labels: bug, fix inside

**Comment by glouel** [comment] 2018-10-21 13:45
Addendum, this WASNT fully saved in b1. 

On some systems, if you have a "minipreview" in syspref and press "preview" (to get the fullscreen one), ScreenSaverEngine will reuse the same instance of Aerial than the one used for the minipreview (which we really don't want).

Because of this, in multi-monitor setup with mirroring mode only (!), it worked exactly once, but if you pressed preview again, Aerial  would try and reuse a player from the previous time you pressed the preview button, which would crash. 

This is truly fixed in upcoming b2.
