### ISSUE TITLE
Error displaying fullscreen videos on Mac Mini

### ISSUE THREAD

**Issue by TheElectroclassics** [JohnCoates/Aerial#485] opened 2018-08-10 14:12 UTC
I have problems with the Mac Mini, it's not displaying the screen saver in full resolution, it shows it scaled and the surroundings show as the border pixels.

**Comment by alistairmcmillan** [comment] 2018-08-13 14:02
@TheElectroclassics How many monitors are you running off of your Mac mini? And are any of them in vertical orientation?

**Comment by rpairo** [comment] 2018-08-14 15:12
I have the same problem

**Comment by rpairo** [comment] 2018-08-14 15:12
I have the same problem.

**Comment by rpairo** [comment] 2018-08-17 09:36
I have the same problem.

**Comment by alistairmcmillan** [comment] 2018-08-21 10:09
Duplicate of #472

**Closed by alistairmcmillan** 2018-08-21 10:09 UTC
