### ISSUE TITLE
All 4K videos for Aerial on my iMac Pro are blurred. Tried various resolutions and toggling clock on and off as suggested elsewhere but all look blurred still

### ISSUE THREAD

**Issue by mikeinlondon** [JohnCoates/Aerial#925] opened 2020-02-17 18:13 UTC
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model:
- [x] macOS version: 
- [x] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by mikeinlondon** [comment] 2020-02-17 18:14
iMac Pro
Catalina 10.15.3
Default monitor settings

**Comment by glouel** [comment] 2020-02-17 18:22
Hi @mikeinlondon 

Which version of Aerial are you running ? In general, this is weird. Can you maybe take a picture of the blurriness ? Note that there are a few videos that are not available in 4K (they lack the "4K" label next to the download. 

Note also that some videos are upscaled/not super sharp. So I would suggest you try playing one in Quicktime and compare, what you see in Quicktime should be what you see in Aerial. You can right-click/option-click a video to open in Quicktime : 

![Capture d’écran 2020-02-17 à 19 19 48](https://user-images.githubusercontent.com/37544189/74678245-bde6ae00-51ba-11ea-9a32-91331b20ac90.jpg)

**Comment by KelvinHS** [comment] 2020-02-18 05:49
iMac 2017
Catalina 10.15.3
Default monitor settings
Using downloaded 4K HDR

This seems to be related ...

In settings - choose Aerial screensaver - whole screen dims
 - recover by pressing any brightness key

When screensaver should time-in and start the videos, its blank / black screen

Preview button on settings did the same - preview button does nothing right at the moment

Summary:-
Screen saver video's not running & screen is dimming

I've tried messing with the Brightness Settings - no change

**Comment by glouel** [comment] 2020-02-18 12:30
> iMac 2017
> Catalina 10.15.3
> Default monitor settings
> Using downloaded 4K HDR
> 
> This seems to be related ...
> 
> In settings - choose Aerial screensaver - whole screen dims
> 
> * recover by pressing any brightness key
> 
> When screensaver should time-in and start the videos, its blank / black screen
> 
> Preview button on settings did the same - preview button does nothing right at the moment
> 
> Summary:-
> Screen saver video's not running & screen is dimming
> 
> I've tried messing with the Brightness Settings - no change

@KelvinHS not sure if this is related, but I'm pretty sure I think I know what can cause this. 

Can you go into Aerial's settings, and check this setting: 

![Capture d’écran 2020-02-18 à 13 28 35](https://user-images.githubusercontent.com/37544189/74736286-aeb33f00-5252-11ea-804a-30d0454595b8.jpg)

Make sure it's not on Power Saving, because that's literally what it does, pull down brightness to minimum if you are on low battery. 

That's still wrong for Aerial to do it at that moment for many reasons and I'll try to fix that, but first can you check that this is your issue ? Thanks and sorry about that bug !

**Comment by glouel** [comment] 2020-02-18 13:07
@KelvinHS I can confirm that it was that option indeed. If enabled here, I could reproduce your issue, I had 2 bad bugs in the battery detection (ironically it happened on macs with no batteries).

It will be fixed in the next build I'll put up later today, in the meantime just change the option I mention. My apologies again for that one, should have caught it earlier !

**Comment by KelvinHS** [comment] 2020-02-18 15:30
@glouel Indeed, I changed it to Keep Enabled, and we have Aerial in all it's beauty back again.
(Also iMac, without battery device.)

Really like your aerial @glouel , many thanks for the dedication

**Comment by glouel** [comment] 2020-02-18 17:15
@KelvinHS thanks a lot ! Here's 1.8.0 that fixes this issue and many others : https://github.com/JohnCoates/Aerial/releases/tag/v1.8.0

**Comment by mikeinlondon** [comment] 2020-02-18 17:35
Thanks!

On Tue, 18 Feb 2020 at 17:16, Guillaume Louel <notifications@github.com<mailto:notifications@github.com>> wrote:

@KelvinHS<https://github.com/KelvinHS> thanks a lot ! Here's 1.8.0 that fixes this issue and many others : https://github.com/JohnCoates/Aerial/releases/tag/v1.8.0

**Closed** 2020-03-18 11:39 UTC
