### ISSUE TITLE
Request, not like asking, like BEGGING FOR...

### ISSUE THREAD

**Issue by sharpguy101** [JohnCoates/Aerial#134] opened 2015-11-03 18:12 UTC
Can you please make this for the Amazon Fire TV? It could be side loaded.
Aerial is already on everything that I own (3 macs and 2 PCs) and that would be the cherry on the icing of the cake that is awesomeness. 
Seriously John, amazing work! So grateful for people like you in my tech life.

**Comment by alistairmcmillan** [comment] 2016-01-28 22:40
Closing as duplicate of #17

**Closed by alistairmcmillan** 2016-01-28 22:40 UTC
Labels: duplicate
