### ISSUE TITLE
Error states its not compatible with OSX

### ISSUE THREAD

**Issue by ODogg** [JohnCoates/Aerial#18] opened 2015-10-27 15:50 UTC
Error states its not compatible with OSX. I'm currently running el capitan 10.11.1.

Thanks for making this awesome project open source!

**Comment by ODogg** [comment] 2015-10-27 16:04
Here's a screenshot

<img width="412" alt="screen shot 2015-10-27 at 10 03 35 am" src="https://cloud.githubusercontent.com/assets/1015885/10764051/030b2f40-7c92-11e5-97d3-14fc6eac4a4c.png">

**Comment by macbookandrew** [comment] 2015-10-27 17:51
Try this suggestion: https://github.com/JohnCoates/Aerial/issues/4#issuecomment-151557047

**Comment by alistairmcmillan** [comment] 2016-01-28 22:20
Closing as duplicate of #4

**Closed by alistairmcmillan** 2016-01-28 22:20 UTC
Labels: duplicate
