### ISSUE TITLE
Aerial seems to ignore "Require password after screensaver" settings

### ISSUE THREAD

**Issue by cloder-r7** [JohnCoates/Aerial#53] opened 2015-10-28 17:40 UTC
I am running OS X El Capitan 10.11.1 on a Macbook Air. I have the configuration "Require password 5 seconds after sleep or screen saver begins" in the Security & Privacy control panel. However, when using Aerial, this setting does not seem to be honored - whenever I move the mouse to stop the screen saver, NO password is required.

**Comment by alistairmcmillan** [comment] 2015-10-28 17:50
Duplicate of #33

**Comment by JohnCoates** [comment] 2015-10-30 10:05
Thanks @alistairmcmillan for linking the original issue. I'm looking into this.

**Closed by JohnCoates** 2015-10-30 10:05 UTC
Labels: duplicate
