### ISSUE TITLE
Arial not working on Mac OS 10.14 Beta

### ISSUE THREAD

**Issue by Sebaszie1000** [JohnCoates/Aerial#486] opened 2018-08-21 17:19 UTC
Hi, 

Sadly, the arial saver has stopped working since I started using 10.14 Beta. It gives the message that it is not compatible with this version of Mac OS. I read through the know issues, but the work around (select it, close Sys. Pref., reopen Sys. Pref) does not work. Is there another work around that you know of? 

Thank you in advance, I really love these screensavers! 
<img width="1122" alt="screenshot 2018-08-21 at 19 08 05" src="https://user-images.githubusercontent.com/42584296/44417871-12ce4780-a577-11e8-865f-1251a74e3b8d.png">

**Comment by standishogrady** [comment] 2018-08-22 00:57
Are you on the latest macOS beta? It's working for me again.

**Comment by alistairmcmillan** [comment] 2018-08-22 12:32
Duplicate of #464

**Closed by alistairmcmillan** 2018-08-22 12:32 UTC
