### ISSUE TITLE
Feature request : Slowly turn the brightness of the display down after set time

### ISSUE THREAD

**Issue by IMPMAC** [JohnCoates/Aerial#164] opened 2015-11-17 00:09 UTC
Have an option to enable the display to slowly reduce the display brightness after a set amount of time to save power

**Comment by glouel** [comment] 2018-10-20 21:43
This is late but I have a prototype for this, will see how we can implement this now.

**Comment by glouel** [comment] 2018-10-24 19:52
Preliminary support for this in 
https://github.com/glouel/Aerial/releases/download/v1.4.4test2/Aerial.saver.zip

Right now, you can set a different brightness when Aerial runs. Brightness should be restored automatically when Aerial goes away.

**Comment by dVIAN13** [comment] 2018-10-24 20:53
@glouel this is awesome. I can confirm there are a few options not available. see screenshot. also, the asleep time does not display, and when I 'preview' the screensaver, the brightness adjusts, but then doesn't adjust back. would you like logs?

<img width="621" alt="screen shot 2018-10-24 at 1 50 21 pm" src="https://user-images.githubusercontent.com/22992333/47460724-fa0b2980-d793-11e8-850f-3ede822c5df1.png">

**Comment by glouel** [comment] 2018-10-24 21:03
So yep I temporarily disabled the other options, right now there's just the start from setting that works, I'm trying to detect when the mac is supposed to get to sleep and add a "fade" until then but not 100% there yet, will be for next version. 

Regarding preview not adjusting brightness back, &à'ç&)à(ç')à(ç is all I have to say about those previews that don't work the same way as regular screensavers ! Thanks for the heads up I'll fix that in next version :)

**Comment by dVIAN13** [comment] 2018-10-24 22:10
@glouel love it. your reply was priceless! thanks for your continued efforts on this.

**Comment by NightRaider73** [comment] 2018-10-24 23:56
So true I didn't see this sorry @glouel for the other comment:(

**Comment by glouel** [comment] 2018-10-25 16:32
@dVIAN13 should have fixed the very lovely preview mode :)

Added the fade option, it will fade from one to the other in X minutes (in 10 intermediate steps), and some cool preview for the brightness.

**Comment by dVIAN13** [comment] 2018-10-25 16:47
@glouel I like the preview! except the lowest value! hahaha. (black screen) I would think there may need to be a min value, like 1, instead of 0(zero) ? just my opinion, as to not freak someone out. even though it reverts after you release the slider... I'm fine with it either way..

can confirm 'preview' works correctly with values.. Thanks!

**Comment by glouel** [comment] 2018-10-25 16:50
Hehe :) I thought about setting a minimum but on my iMac 0 is not full black, you can definitely still see a bit. 

I think it's ok as as soon as you lift your mouse it goes back but yeah, maybe a minimum.

**Comment by glouel** [comment] 2018-10-26 16:01
I've added the night mode only and on battery only to this. It looks pretty stable (maybe not battery status detection though)

**Comment by dVIAN13** [comment] 2018-10-26 16:17
@glouel should I still be receiving errors when dragging the sliders? (see screenshots) this is on both internal only display, and when external displays are connected.

<img width="620" alt="screen shot 2018-10-26 at 9 16 17 am" src="https://user-images.githubusercontent.com/22992333/47579091-eed50c80-d8ff-11e8-86bc-cc42718a7993.png">

<img width="396" alt="screen shot 2018-10-26 at 9 16 28 am" src="https://user-images.githubusercontent.com/22992333/47579098-f1cffd00-d8ff-11e8-897e-e4a1714a114b.png">

**Comment by glouel** [comment] 2018-10-26 16:19
Oh that's interesting. Are you using a mouse or a trackpad ? Left clicking ? This was more of a warning for me, but kinda curious on how you generated it.

**Comment by dVIAN13** [comment] 2018-10-26 16:33
got it. thanks!

**Comment by SeanMSmith** [comment] 2018-10-27 00:04
Might I suggest coloring "this may crash, you are warned!" in **red**, so as to grab the user's attention?

**Comment by dVIAN13** [comment] 2018-10-27 00:09
is the goal to eventually not have it crash...? if that's only there because we're testing, would you remove it when it's merged with master?

**Comment by glouel** [comment] 2018-10-27 00:14
Yeah it was more of a precaution than anything, because I have to do "unsafe" things to get brightness, but it's actually very stable and should be no issue. I will remove it in 1.4.4 finale :) 

If something is really wrong it probably shouldn't be in (although I had some crashes in 1.4.3 😅), this was more of a beta tester message !

**Comment by glouel** [comment] 2018-10-27 12:55
(removed in next build)

**Comment by glouel** [comment] 2018-10-27 15:12
https://github.com/JohnCoates/Aerial/releases/download/v1.4.4beta3/Aerial.saver.zip

This will probably be the last beta before 1.4.4

**Comment by glouel** [comment] 2018-10-29 12:49
Implemented in 1.4.4

**Closed by glouel** 2018-10-29 12:49 UTC
Labels: enhancement

**Comment by dVIAN13** [comment] 2018-10-29 15:16
@glouel , just confirming that the warning message above still exists in 1.4.4 final(for me at least).

**Comment by glouel** [comment] 2018-10-29 15:23
Bah, I only removed in from the top one, not the bottom one 😅

Will be fixed in next version thanks :)

**Comment by dVIAN13** [comment] 2018-10-29 15:27
haha, no problem! glad to help.
