### ISSUE TITLE
Distorted screen

### ISSUE THREAD

**Issue by anish2008** [JohnCoates/Aerial#440] opened 2018-02-01 01:59 UTC
I installed the screen saver on my MacBook Pro 13" w/touch bar runninng High Sierra 10.13.3.

The screensaver starts for 1 split second and then the entire screen shows a distorted image. 
I tried uninstalling and reinstalling.

It works on my friends computer. He has a 15" pro. 

Then we tried putting my laptop into target disk mode and booted into it with his 15"....

The screensaver worked!

But it doesn't work on my computer.

So we tried putting my laptop in target disk mode and booted into another 13" pro, and still the distorted screen. 

It didn't work. 

We tried to install it fresh on another 13" pro and it didn't work. Same distorted screen. 

----

Does this not work on 13" pros?!
![img_1146](https://user-images.githubusercontent.com/36020323/35657271-7fa6e6c0-06b0-11e8-96d0-16d6ac91cd57.JPG)

**Comment by anish2008** [comment] 2018-02-01 01:59
Hoping to get some help.

**Comment by thomas-alrek** [comment] 2018-02-01 11:36
+1 I have the exact same issue on a MacBook Pro 15" TouchBar 2017 (Radeon 560) running High Sierra 10.13.3

**Comment by robertobrega** [comment] 2018-02-02 14:07
Same here. 13pro with touch bar.

**Comment by gibatronic** [comment] 2018-02-02 15:03
I have the same issue, tried both `1.2` and `1.2 Beta 5` releases, under `macOS 10.13.3` High Sierra, with the display running at its native resolution of `2560 x 1600`.

**Comment by ezoerner** [comment] 2018-02-02 20:05
+1 MacBook Pro (15-inch, 2017) macOS 10.13.2
display native res

**Comment by Patrik-svobodik** [comment] 2018-02-03 08:25
I have the same issue, I think it will be fixed but it just sucks at this point

**Comment by MrFuryian** [comment] 2018-02-03 20:20
Same issue here on mbp 13" 2017

Seems to be a single screen issue for me. When i attach a second screen to my mbp, there is no issue.

**Comment by wesnolte** [comment] 2018-02-04 16:48
Same issue for me. 2017 MBP without touchbar, OSX 10.13.3

**Comment by NikiStar** [comment] 2018-02-05 03:03
+1 MacBook Pro (15-inch, 2017) macOS 10.13.3
display native res

**Comment by NikiStar** [comment] 2018-02-05 10:02
I found a couple of things:
- I remember that I had no problems with Sierra. After I upgraded to High Sierra this is happening.
- If I use an external monitor(usb hub -> HDMI ) it works without a problem.
- If I choose the option "show with clock" it works just with the native display.

It smells like it's some kind of OS problem...

**Comment by jkeshet** [comment] 2018-02-06 09:32
Same issue for me. Flickering while using Aerial. Macbook Pro 15" 2017.

**Comment by madmanmax** [comment] 2018-02-07 07:41
Same here after on a MacBook Pro (15-inch, 2017) after upgrading to High Sierra 10.13.3

**Comment by nathanwebsterdotme** [comment] 2018-02-07 11:41
Same here.

**Comment by alistairmcmillan** [comment] 2018-02-07 14:05
Closing as duplicate of #377

**Closed by alistairmcmillan** 2018-02-07 14:05 UTC
