### ISSUE TITLE
Pausing videos

### ISSUE THREAD

**Issue by SebastianMllr** [JohnCoates/Aerial#332] opened 2017-03-15 20:50 UTC
Currently, I am experiencing a bug which causes the aerial videos to freeze. I am using a MacBook Pro 15" (2016 with Touch Bar). All videos are locally cached.  ##The problem is that in nearly 99% of the cases, the screensaver freezes when playing the video "Los Angeles - Three" (the video which is showing the beach and the Santa Monica Pier).

I would be very grateful, if you could solve this problem. Thanks in advance.

Sebastian

**Comment by thebadpete** [comment] 2017-03-16 06:08
In my case, it randomly freezes. At work I have a 3-display setup, and I set the screensaver to display different aerials on each monitor. Sometimes 1 or 2 out of the 3 screen freezes.

**Comment by cbseven** [comment] 2017-03-17 13:47
+1

I am seeing the same issue. Multiple (2) monitor situation --> only one of the videos pauses while the other is playing as normal. I have not encountered a situation where both videos are in a paused state. Nor have I noticed this type of pause behavior when running with a single monitor (though I admit that I don't run in single monitor mode very often).

**Comment by TijmenH** [comment] 2017-03-19 13:32
For me, the LA beach one always freezes right from the beginning. There is another one that always freezes (I think it's the LA highway one, or the airfield one, or both maybe..). I'm on a Macbook Pro 13" 2015. All other video's are playing fine. I also made sure I have all the video's cached, and I do.

**Comment by Syden10** [comment] 2017-03-19 23:00
It is a known bug, unfortunately unresolved yet, check here: https://github.com/JohnCoates/Aerial/issues/278

**Comment by sricochet** [comment] 2017-04-02 04:05
That bug happened to me, and my power went out unexpectedly. So it booted back up and the screen was set to 720p or 1366 x 768. Before it was 1080p. So I changed it back to 1080p by holding down the option key and clicking on Scaled and selecting 1080p, and now all the videos play as expected. So try setting the resolution to 720p or your screen's resolution, then switching back to whatever you had set it for to begin with, and I think maybe it'll work.

**Comment by alistairmcmillan** [comment] 2017-04-05 21:49
Closing as duplicate of #278

**Closed by alistairmcmillan** 2017-04-05 21:49 UTC
