### ISSUE TITLE
Appearance of "You cannot use the Aerial screen saver with this version of OS X."

### ISSUE THREAD

**Issue by lohonam** [JohnCoates/Aerial#478] opened 2018-07-18 03:06 UTC
### Appearance of "You cannot use the Aerial screen saver with this version of OS X." message

I have enjoyed the screensaver since its initial release until macOS Mojave 4th developer beta (18A336e). After updated to this beta, a message saying `You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver.` appears in screen saver preview and even when the screen saver was triggered. I have applied the workaround as described in known bug but it still does not work... I have tried to re-install the latest saver but not work...

**Comment by mikegazdag** [comment] 2018-07-18 20:46
Duplicate of https://github.com/JohnCoates/Aerial/issues/464

**Comment by controversial** [comment] 2018-07-21 17:20
@alistairmcmillan You published [a blog post](http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html) about this issue a few years ago for a previous version of macOS. Any thoughts?

**Comment by alistairmcmillan** [comment] 2018-07-30 10:10
Closing as duplicate of #464

**Closed by alistairmcmillan** 2018-07-30 10:10 UTC
