### ISSUE TITLE
This doesn't work on OS X 10.11.1 MBP 13 inch 2015

### ISSUE THREAD

**Issue by markaseddon** [JohnCoates/Aerial#12] opened 2015-10-27 13:46 UTC
The app installs and is displayed in Screen Saver preferences pane but will not execute.

**Comment by derekbjohnson** [comment] 2015-10-27 15:50
I experienced this issue and cloned the repo to check it out; however, once I built Aerial.saver in XCode 7.1 the screensaver began working.  After this, the preferences pane stopped working.

Summary:  Running Aerial.saver directly from GitHub, I can access the Preference Pane and set my options, but the video will not preview and the screensaver will not run.  After building from source, the preferences pane is inoperable, but the screensaver works.

I'll try to take a look at this tonight unless someone beats me to it.

**Comment by macbookandrew** [comment] 2015-10-27 17:50
Also try this suggestion: https://github.com/JohnCoates/Aerial/issues/4#issuecomment-151557047

**Comment by alistairmcmillan** [comment] 2016-01-28 22:20
Closing as duplicate of #4

**Closed by alistairmcmillan** 2016-01-28 22:20 UTC
Labels: duplicate
