### ISSUE TITLE
seems like it stops every few seconds

### ISSUE THREAD

**Issue by nimaipandit** [JohnCoates/Aerial#324] opened 2017-02-20 21:21 UTC
Perhaps this happens because it is changing to a different scene? 

My specs:
MacBook Pro OSX 10.11.6
HD: 1TB
Processor: 3 GHz Intel Core i7
Memory: 16 GB 1600 MHz DDR3
 

Thanks for your support.

**Comment by alistairmcmillan** [comment] 2017-02-21 10:29
Closing as duplicate of #278

**Closed by alistairmcmillan** 2017-02-21 10:29 UTC
