### ISSUE TITLE
Apple TV 4K Screen Savers?

### ISSUE THREAD

**Issue by MGoeppl** [JohnCoates/Aerial#418] opened 2017-11-12 22:50 UTC
Is it possible for you to implement the new  TV 4K Screensavers to Aerial?

**Comment by SammokKabasi** [comment] 2017-11-13 02:19
https://github.com/JohnCoates/Aerial/issues/378

**Comment by alistairmcmillan** [comment] 2017-11-13 12:28
Closing as duplicate of #378.

**Closed by alistairmcmillan** 2017-11-13 12:28 UTC
