### ISSUE TITLE
[Feature Request] Include 'Day/Night' feature.

### ISSUE THREAD

**Issue by jamesmstewart** [JohnCoates/Aerial#283] opened 2016-12-19 21:45 UTC
I suggets including a feature that would choose the screensaver depending on the time. So, after sunrise, it will choose screensaver that are shot during the day, at night, ones shot a night, at sunset, shot sunset, etc.

**Comment by alistairmcmillan** [comment] 2016-12-19 22:42
Closing as duplicate of #11

**Closed by alistairmcmillan** 2016-12-19 22:42 UTC
Labels: duplicate
