### ISSUE TITLE
Will not install on 10.13.5 - Error OSStatus error 99999

### ISSUE THREAD

**Issue by sdmactech** [JohnCoates/Aerial#469] opened 2018-06-10 18:57 UTC
Attempt to install on new 10.13.5 system - get "The operation couldn't be completed. (OSStatus error 99999.)"

**Comment by avioli** [comment] 2018-07-08 14:43
I installed it ok on same OS version from the download link.

**Comment by alistairmcmillan** [comment] 2018-07-31 12:45
@sdmactech Best guess this was probably caused by a file missing from the bundle lost during decompression of the ZIP file or the bundle being transferred from one drive to another. Best suggestion for a fix is to download a new copy.

**Closed by alistairmcmillan** 2018-07-31 12:45 UTC

**Comment by krknopp** [comment] 2018-08-02 13:25
I'm getting the same thing on one of my computers, but not the other one.  Happening on both this and Butterflight's configurator, but nothing else that I've seen.  My system is 10.13.6.
