### ISSUE TITLE
Energy Savings

### ISSUE THREAD

**Issue by gaadler** [JohnCoates/Aerial#47] opened 2015-10-28 15:28 UTC
Already mentioned in pervious issues.  Would like to have screen turn off as selected in energy savings settings. Otherwise no issues experienced in El Cap. Great work!

**Comment by alby128** [comment] 2015-10-28 15:59
Duplicate of #23

**Comment by alistairmcmillan** [comment] 2016-01-28 21:13
Closing as duplicate of #23

**Closed by alistairmcmillan** 2016-01-28 21:13 UTC
Labels: duplicate
