### ISSUE TITLE
Aerial

### ISSUE THREAD

**Issue by babanana** [JohnCoates/Aerial#150] opened 2015-11-07 22:24 UTC
I love the new screen savers, but I am unable to make them stop after a set time. When I use any other screen saver it disappears after 15 minutes, but I cannot find a way to do that with these specific ones. I've tried to change the Energy Saver preferences, but that doesn't work. Any ideas?

**Comment by tnViking** [comment] 2015-11-07 22:41
Which version of Aerial are you running?
And OS X version?

I just tried to put my screen to hibernate after 1min, and Aerial stops

**Comment by babanana** [comment] 2015-11-07 22:50
Thanks for responding. I have OS 10.11.1 and I can’t tell what version of Aerial. It doesn’t show up.

On Nov 7, 2015, at 4:41 PM, Ole-Martin Bratteng <notifications@github.com> wrote:

Which version of Aerial are you running?
And OS X version?

I just tried to put my screen to hibernate after 1min, and Aerial stops

**Comment by tnViking** [comment] 2015-11-07 22:54
Can you try to install [1.2 Beta 5](https://github.com/JohnCoates/Aerial/releases/download/v1.2beta5/Aerial.zip)

**Comment by babanana** [comment] 2015-11-07 22:55
Thanks again. I was just going to try that.
On Nov 7, 2015, at 4:54 PM, Ole-Martin Bratteng <notifications@github.com> wrote:

Can you try to install 1.2 Beta 5 <https://github.com/JohnCoates/Aerial/releases/download/v1.2beta5/Aerial.zip>

**Comment by alistairmcmillan** [comment] 2017-09-09 15:48
Duplicate of #23. Fixed in 1.2 release.

**Closed by alistairmcmillan** 2017-09-09 15:48 UTC
