### ISSUE TITLE
Weather overlay location not updating in Sonoma 14.0

### ISSUE THREAD

**Issue by stilwellweather** [JohnCoates/Aerial#1336] opened 2023-10-05 17:23 UTC
#### General troubleshooting tips

Before logging an issue please check that:
- [x] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [x] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [x] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [x] Mac model: 2022 M2 13" MBP
- [x] macOS version: 14.0
- [x] Monitor setup: built-in display only

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

Whenever I take my laptop to work, the location used for the weather overlay never updates.

I tried re-installing Aerial through Homebrew and the issue persisted.

I tried turning location services off and the program was still pulling a location for me - my home city.

After reviewing the log file (attached), it looks like Aerial is using cached location data rather than dynamically updating my location as it did under Ventura.
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/12821237/AerialLog.txt)

**Comment by glouel** [comment] 2023-10-05 17:44
Quick update, I think I can confirm that this is a new restriction. Usually allowing legacyScreenSaver to access your location was enough but for some reason it fails : 

```
2023-10-05 19:39:56.151 : Starting Location initialization
2023-10-05 19:39:56.151 : Location services disabled
2023-10-05 19:39:56.151 : Couldn't retrieve your location, using latest cached coordinates instead
```

I'll try to dig a bit but it's just one more of these annoying restrictions. As a workaround in the meantime, if you use Aerial Companion, because it's unrestricted (providing you allow it to use your location, obviously, that's in system settings), it should be able to look up your location fine and the screensaver will use that later on.

**Comment by stilwellweather** [comment] 2023-10-05 18:10
Can confirm Aerial Companion is able to access my location as I move around. Likely going to use that moving forward. Thanks for the tip!

**Comment by stilwellweather** [comment] 2023-10-07 15:11
Spoke too soon - I'm seeing the same issue in the Aerial Companion log as well. Did the exact same troubleshooting steps and it's still pulling my work address rather than my home address.

Probably going to turn the overlay off for the time being and turn it back on if/when there's a solution. Thank you for looking into this!
[AerialUnderCompanionLog.txt](https://github.com/JohnCoates/Aerial/files/12838093/AerialUnderCompanionLog.txt)

**Comment by glouel** [comment] 2023-10-07 15:12
I think because it caches your location, it will only look it up again if you quit/restart Companion. 

It's not great and I'll try to think of a workaround for this.

**Comment by glouel** [comment] 2023-10-09 16:49
@stilwellweather 

- please download https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.5.2/Aerial.Companion.zip 
- put it in your Applications folder and launch it, make sure it says 1.5.2 in the menu. 
- update to Aerial (screensaver) 3.3.4 when prompted

Afterwards location should work again. Please note though, weather is cached for 15 minutes between launches (this is to make sure we don't get kicked of the free weather forecast api). Let me know how it works for you.

**Comment by stilwellweather** [comment] 2023-10-09 17:04
Sure thing!

**Comment by stilwellweather** [comment] 2023-10-09 17:06
I'm remote today - I'll be able to report if the location automatically updates tomorrow. Thanks for jumping on this so quick!

**Comment by stilwellweather** [comment] 2023-10-10 20:12
Looks like it's updating like it did pre-Sonoma. I work where three different municipalities overlap and it looks like the overlay is moving between the municipalities (which is normal behavior) like before. I'd consider this resolved.

**Comment by glouel** [comment] 2023-10-10 20:47
Awesome, thanks for confirming ! there's a 15 mins delay between updates so it's possible if your commute is short you get the wrong location (and it was exactly the same before), but for 99.9% of the cases it should be fine ! 

Closing this, let me know if you still hit an issue, take care!

**Closed by glouel** 2023-10-10 20:47 UTC
