### ISSUE TITLE
Doesn't work with El Capitan

### ISSUE THREAD

**Issue by Ryukashy** [JohnCoates/Aerial#222] opened 2016-03-24 11:29 UTC
Hello! First of all, thank you very much for your work. I'd be awesome to have this screensaver. Unfortunately, the software is telling me that this screensaver cannot work with my OS X version, that is pretty strange, as long as I have El Capitan 10.11.4 (on an iMac mid-2010). Am I doing something wrong? I've already tried the Beta 5, but the problem is not solved.

Thank you very much

Bye

Lorenzo

**Comment by tjjohnsto** [comment] 2016-03-25 15:12
Confirmed. I get a Kernel Panic when the screensaver launches on 10.11.4 2015 Macbook Pro Retina. Disabling screensaver for now...

`Anonymous UUID:       BAEC9630-240B-4C94-BAF9-30C76695A508

Fri Mar 25 10:04:26 2016

*** Panic Report ***
panic(cpu 2 caller 0xffffff8005bce40a): Kernel trap at 0xffffff8005e46d2c, type 13=general protection, registers:
CR0: 0x000000008001003b, CR2: 0xffffff91f1540000, CR3: 0x0000000008ef5000, CR4: 0x00000000003627e0
RAX: 0xdeadbeefdeadbeef, RBX: 0xffffff8044d90748, RCX: 0xfffffffff03df11c, RDX: 0x0000000000000001
RSP: 0xffffff81efc2b8f0, RBP: 0xffffff81efc2b970, RSI: 0x0000000000000002, RDI: 0xffffff802446a920
R8:  0xffffff8024468000, R9:  0xffffff80450afa40, R10: 0x0000000000000000, R11: 0x000000ae08649182
R12: 0xffffff80450af420, R13: 0x0000000000000001, R14: 0xffffff80450afa40, R15: 0xffffff8044d90248
RFL: 0x0000000000010286, RIP: 0xffffff8005e46d2c, CS:  0x0000000000000008, SS:  0x0000000000000000
Fault CR2: 0xffffff91f1540000, Error code: 0x0000000000000000, Fault CPU: 0x2, PL: 0

Backtrace (CPU 2), Frame : Return Address
0xffffff81c4bc5df0 : 0xffffff8005adab12 
0xffffff81c4bc5e70 : 0xffffff8005bce40a 
0xffffff81c4bc6050 : 0xffffff8005bec273 
0xffffff81c4bc6070 : 0xffffff8005e46d2c 
0xffffff81efc2b970 : 0xffffff8005e43964 
0xffffff81efc2bd90 : 0xffffff8005e2fec7 
0xffffff81efc2bde0 : 0xffffff8005e31403 
0xffffff81efc2bf40 : 0xffffff8005d6623c 
0xffffff81efc2bfb0 : 0xffffff8005bc8e27 

BSD process name corresponding to current thread: kernel_task
Boot args: kext-dev-mode=1 rootless=0

Mac OS version:
15E65

Kernel version:
Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64
Kernel UUID: 4E7B4496-0B81-34E9-97AF-F316103B0839
Kernel slide:     0x0000000005800000
Kernel text base: 0xffffff8005a00000
__HIB  text base: 0xffffff8005900000
System model name: MacBookPro12,1 (Mac-E43C1C25D4880AD6)

System uptime in nanoseconds: 747465164485
last loaded kext at 43537612363: com.fortinet.fct.kext.fctapnke	1 (addr 0xffffff7f88880000, size 401408)
last unloaded kext at 182116921419: com.apple.driver.AppleIntelLpssI2C	2.0.60 (addr 0xffffff7f8801d000, size 40960)
loaded kexts:
com.fortinet.fct.kext.fctapnke	1
com.fortinet.fct.kext.avkern	1.0.1
org.virtualbox.kext.VBoxNetAdp	5.0.12
org.virtualbox.kext.VBoxNetFlt	5.0.12
org.virtualbox.kext.VBoxUSB	5.0.12
org.virtualbox.kext.VBoxDrv	5.0.12
com.sierrawireless.driver.SierraVSP	1.0.0
com.prolific.driver.PL2303	1.5.1
com.Logitech.Unifying.HID Driver	1.3.1
com.Logitech.Control Center.HID Driver	3.9.1
com.apple.driver.AppleMikeyHIDDriver	124
com.apple.filesystems.autofs	3.0
com.apple.driver.AGPM	110.21.18
com.apple.driver.ApplePlatformEnabler	2.6.0d0
com.apple.driver.X86PlatformShim	1.0.0
com.apple.driver.AppleOSXWatchdog	1
com.apple.driver.AppleHDA	274.7
com.apple.driver.AppleGraphicsDevicePolicy	3.7.7
com.apple.driver.AppleUpstreamUserClient	3.6.1
com.apple.driver.pmtelemetry	1
com.apple.iokit.IOUserEthernet	1.0.1
com.apple.iokit.IOBluetoothSerialManager	4.4.4f4
com.apple.Dont_Steal_Mac_OS_X	7.0.0
com.apple.driver.AppleHV	1
com.apple.driver.AppleIntelSlowAdaptiveClocking	4.0.0
com.apple.driver.AppleBacklight	170.8.9
com.apple.driver.AppleMCCSControl	1.2.13
com.apple.driver.AppleCameraInterface	5.46.0
com.apple.iokit.BroadcomBluetoothHostControllerUSBTransport	4.4.4f4
com.apple.driver.AudioAUUC	1.70
com.apple.driver.AppleSMCLMU	208
com.apple.driver.AppleLPC	3.1
com.apple.driver.AppleThunderboltIP	3.0.8
com.apple.driver.AppleIntelBDWGraphics	10.1.4
com.apple.driver.AppleIntelBDWGraphicsFramebuffer	10.1.4
com.apple.driver.AppleUSBCardReader	3.7.1
com.apple.AppleFSCompression.AppleFSCompressionTypeDataless	1.0.0d1
com.apple.AppleFSCompression.AppleFSCompressionTypeZlib	1.0.0
com.apple.BootCache	38
com.apple.iokit.IOAHCIBlockStorage	2.8.5
com.apple.driver.AppleAHCIPort	3.1.8
com.apple.driver.AppleTopCaseHIDEventDriver	86
com.apple.driver.AppleFWOHCI	5.5.2
com.apple.iokit.AppleBCM5701Ethernet	10.2.0
com.apple.driver.AirPort.Brcm4360	1040.1.1a6
com.apple.driver.AppleSmartBatteryManager	161.0.0
com.apple.driver.AppleRTC	2.0
com.apple.driver.AppleACPIButtons	4.0
com.apple.driver.AppleHPET	1.8
com.apple.driver.AppleSMBIOS	2.1
com.apple.driver.AppleACPIEC	4.0
com.apple.driver.AppleAPIC	1.7
com.apple.nke.applicationfirewall	163
com.apple.security.quarantine	3
com.apple.security.TMSafetyNet	8
com.apple.iokit.IOUSBUserClient	900.4.1
com.apple.kext.triggers	1.0
com.apple.driver.DspFuncLib	274.7
com.apple.kext.OSvKernDSPLib	525
com.apple.driver.X86PlatformPlugin	1.0.0
com.apple.driver.CoreCaptureResponder	1
com.apple.iokit.IOSlowAdaptiveClockingFamily	1.0.0
com.apple.driver.AppleGraphicsControl	3.12.6
com.apple.driver.AppleBacklightExpert	1.1.0
com.apple.driver.AppleSMBusController	1.0.14d1
com.apple.driver.AppleHDAController	274.7
com.apple.iokit.IOHDAFamily	274.7
com.apple.iokit.IOFireWireIP	2.2.6
com.apple.iokit.IOBluetoothHostControllerUSBTransport	4.4.4f4
com.apple.driver.AppleSMC	3.1.9
com.apple.driver.IOPlatformPluginFamily	6.0.0d7
com.apple.driver.AppleIntelLpssUARTCommon	2.0.60
com.apple.iokit.IOSurface	108.2.1
com.apple.iokit.IONDRVSupport	2.4.1
com.apple.AppleGraphicsDeviceControl	3.12.6
com.apple.iokit.IOAcceleratorFamily2	205.3
com.apple.iokit.IOGraphicsFamily	2.4.1
com.apple.driver.usb.cdc.ecm	5.0.0
com.apple.iokit.IOSerialFamily	11
com.apple.driver.AppleUSBAudio	303.3.1
com.apple.iokit.IOAudioFamily	204.3
com.apple.vecLib.kext	1.2.0
com.apple.driver.usb.AppleUSBHub	1.0.1
com.apple.iokit.IOSCSIBlockCommandsDevice	3.7.7
com.apple.iokit.IOUSBMassStorageDriver	1.0.0
com.apple.iokit.IOSCSIArchitectureModelFamily	3.7.7
com.apple.driver.AppleThunderboltDPInAdapter	4.1.3
com.apple.driver.AppleThunderboltDPOutAdapter	4.1.3
com.apple.driver.AppleThunderboltDPAdapterFamily	4.1.3
com.apple.driver.AppleThunderboltPCIUpAdapter	2.0.2
com.apple.driver.AppleThunderboltPCIDownAdapter	2.0.2
com.apple.driver.usb.IOUSBHostHIDDevice	1.0.1
com.apple.driver.IOBluetoothHIDDriver	4.4.4f4
com.apple.iokit.IOBluetoothFamily	4.4.4f4
com.apple.iokit.IOUSBHIDDriver	900.4.1
com.apple.driver.usb.cdc	5.0.0
com.apple.driver.usb.networking	5.0.0
com.apple.driver.usb.AppleUSBHostCompositeDevice	1.0.1
com.apple.driver.CoreStorage	517.20.1
com.apple.iokit.IOAHCIFamily	2.8.1
com.apple.driver.AppleHIDKeyboard	181
com.apple.driver.AppleMultitouchDriver	304.10.2
com.apple.driver.AppleHIDTransport	5
com.apple.driver.AppleHSSPIHIDDriver	43
com.apple.iokit.IOFireWireFamily	4.6.0
com.apple.iokit.IOEthernetAVBController	1.0.3b3
com.apple.driver.AppleThunderboltNHI	4.0.4
com.apple.iokit.IOThunderboltFamily	6.0.2
com.apple.iokit.IO80211Family	1110.26
com.apple.driver.mDNSOffloadUserClient	1.0.1b8
com.apple.iokit.IONetworkingFamily	3.2
com.apple.driver.corecapture	1.0.4
com.apple.driver.AppleHSSPISupport	43
com.apple.driver.AppleIntelLpssSpiController	2.0.60
com.apple.driver.AppleIntelLpssGspi	2.0.60
com.apple.driver.AppleIntelLpssDmac	2.0.60
com.apple.driver.usb.AppleUSBXHCIPCI	1.0.1
com.apple.driver.usb.AppleUSBXHCI	1.0.1
com.apple.iokit.IOUSBFamily	900.4.1
com.apple.iokit.IOUSBHostFamily	1.0.1
com.apple.driver.AppleUSBHostMergeProperties	1.0.1
com.apple.driver.AppleEFINVRAM	2.0
com.apple.driver.AppleEFIRuntime	2.0
com.apple.iokit.IOHIDFamily	2.0.0
com.apple.iokit.IOSMBusFamily	1.1
com.apple.security.sandbox	300.0
com.apple.kext.AppleMatch	1.0.0d1
com.apple.driver.AppleKeyStore	2
com.apple.driver.AppleMobileFileIntegrity	1.0.5
com.apple.driver.AppleCredentialManager	1.0
com.apple.driver.DiskImages	417.2
com.apple.iokit.IOStorageFamily	2.1
com.apple.iokit.IOReportFamily	31
com.apple.driver.AppleFDEKeyStore	28.30
com.apple.driver.AppleACPIPlatform	4.0
com.apple.iokit.IOPCIFamily	2.9
com.apple.iokit.IOACPIFamily	1.4
com.apple.kec.Libm	1
com.apple.kec.pthread	1
com.apple.kec.corecrypto	1.0
 `

**Comment by alistairmcmillan** [comment] 2016-03-26 12:18
I've been running the screensaver on two machines running 10.11.4 now since it was released. No issues.

@Ryukashy That message comes up now and again for people and just as mysteriously goes away itself. If you still get it I'd recommend making sure you have Beta 5 installed, making sure you've deleted all other versions (check `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers` as it can be installed in both) and rebooting just to be sure.

@tjjohnsto While it's not impossible, it's pretty unlikely that a screensaver could cause a kernel panic. From the information you've posted above, you have disabled the rootless feature in El Capitan and turned off KEXT signing. Do you mind if I ask why? Third-party KEXTs are much more likely to cause kernel panics than a screensaver.

**Comment by jonathanmorgan** [comment] 2016-03-26 12:28
beta 5 is just fine on my 10.11.4 machine, as well.

**Comment by iStuffs** [comment] 2016-04-02 07:48
Hello, I get a strange issue with your screen saver and 'iOS Saver'.
I get the error message then a quit system preferences and it work but the other screensaver can not be used. Here is a gif of the issue.
I've also contacted the iOS saver developper.

I run OS X 10.11.4 on a late 2015 27'' 5K iMac.
![screen recording 2016-04-02 at 09 35 am](https://cloud.githubusercontent.com/assets/7252820/14225114/549e980a-f8b7-11e5-9499-4ccbccb7cb25.gif)

**Comment by alistairmcmillan** [comment] 2016-04-02 11:10
@iStuffs I don't think the problem is with Aerial or iOS Saver. I've seen this when switching between other screensavers. I think it's a bug in System Preferences.

**Comment by iStuffs** [comment] 2016-04-02 13:54
@alistairmcmillan Yes, it looks like a System preferences bug. But all the 3rd party screensaver are not impacted. If we can see what is in commun between the screensaver involved, we can submit the bug to apple and it could be solved sooner and benefits the user experience of your screensaver.

**Comment by alistairmcmillan** [comment] 2016-04-03 12:31
Not my screensaver, it's John's screensaver. :)

But yeah. Would be useful to figure what is triggering this System Preferences bug and report it to Apple.

**Comment by JohnCoates** [comment] 2016-04-04 05:55
This bug has been perplexing me since launching Aerial. It might have to do with Swift? No idea.

**Comment by Chaser53** [comment] 2016-04-05 13:43
@JohnCoates @alistairmcmillan I'd have to agree with it being a bug with System Preferences. Maybe it doesn't play well with the Swift libraries, but I am not 100% sure on that. I've been trying to replicate the issue for iOS Screen Saver on my machine to no avail. Hopefully Apple patches the problem or another solution is found so I can release an update.

**Comment by Ryukashy** [comment] 2016-04-05 15:22
Dear Alistair,
    thank you for your help. Now the screensaver is working, probably
you're right. It's just a temporary issue. Thank you again.

2016-03-26 12:18 GMT+00:00 Alistair McMillan <notifications@github.com>:

**Comment by alistairmcmillan** [comment] 2016-04-06 02:46
@JohnCoates @Chaser53 @iStuffs @Ryukashy I think I just figured out the problem.

This is what I think is happening.

When you open System Preferences and select a screen saver written in Swift, I think it caches the Swift libraries that are bundled inside the screen saver. Then when you select another Swift screen saver it tries to use those same libraries again. However if the screen saver was compiled against a different version of the libraries you get the error. If it is compiled against the same version, no error.

To prove this. Download and install https://github.com/soffes/clock-saver/releases/tag/v0.5.0 and https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5 and try to switch between them in System Preferences. I always get the error. They are compiled against different versions of Swift.

Then download and compile the source for both. Because you are compiling them yourself they'll be compiled against the same version of Swift (and have the same version bundled inside). Install the resulting saver files and try switching between them. It works reliably for me.

I've logged a bug with Apple as rdar://25569037 and you can see it here https://openradar.appspot.com/radar?id=5023195543371776. Hopefully it makes sense. I should have been asleep hours ago.

BTW @Chaser53 The problem doesn't seem to be with your version of the iOS Screensaver (the Quartz Composer file version). The problem @iStuffs seems to be having is with Christian's original Swift version. Note in @iStuffs screencast the screensaver says "iOS Saver" whereas when I try yours it is listed as "iOS Lockscree...". :)

**Comment by alistairmcmillan** [comment] 2016-05-06 10:41
Wrote this up here. http://alistairmcmillan.github.io/2016/04/25/OSX-Swift-screensaver-bug.html

**Comment by alistairmcmillan** [comment] 2016-06-17 10:00
Duplicate of #4

**Closed by alistairmcmillan** 2016-06-17 10:00 UTC
