### ISSUE TITLE
idea - time based ariel views

### ISSUE THREAD

**Issue by shawnt90** [JohnCoates/Aerial#263] opened 2016-10-08 03:00 UTC
First of all, I love the project. I think it's a great screensaver. This isn't a complaint but an idea for a feature. It would be cool if the ariel views synced with our local time. So if it's day time, a day view would play and if it's night time, a night view would play. There are even a few ariels that seem to be morning or dusk that could fit in those times. The reason why I think it would good is so our eyes won't be strained from the sudden change in brightness (mostly at night). I use Flux to change the screen color as it gets later into the night and sometimes it can be jarring when a bright webpage/window pops up. Either way, it's a great screensaver and I look forward to using it more and more.

**Comment by alistairmcmillan** [comment] 2016-10-08 17:51
Duplicate of #11 .

**Closed by alistairmcmillan** 2016-10-08 17:51 UTC
