### ISSUE TITLE
It'd be nice to know the location of the video being played

### ISSUE THREAD

**Issue by jimjonah** [JohnCoates/Aerial#303] opened 2017-01-05 18:14 UTC
A black bar across the bottom subtly displaying the location of the video would be very cool!

**Comment by alistairmcmillan** [comment] 2017-01-05 18:38
A few people have already suggested this. So closing this as a duplicate of #58 .

Good news is that someone has already submitted an implementation of this idea. #285

**Closed by alistairmcmillan** 2017-01-05 18:38 UTC
