### ISSUE TITLE
Aerial hangs when activated from Hot Corner 

### ISSUE THREAD

**Issue by mac1user** [JohnCoates/Aerial#329] opened 2017-03-02 20:07 UTC
Set one of the Hot Corner to activate Screen Saver. Change Screen Saver to Aerial and activate the screen saver. It starts loading but immediately hangs. I also have the lock enabled after sleep or screen saver begins.I'm running 10.12.3

**Comment by alistairmcmillan** [comment] 2017-03-02 20:31
Closing as duplicate of #20

**Closed by alistairmcmillan** 2017-03-02 20:31 UTC
Labels: duplicate
