### ISSUE TITLE
config: check all night videos

### ISSUE THREAD

**Issue by xenDE** [JohnCoates/Aerial#380] opened 2017-09-14 16:36 UTC
hi,

in the config are only "uncheck all" and "check all".

I need "check all day videos" and "check all night videos".

that would be great :)

thanks for the nice prog!

**Comment by hroland** [comment] 2017-09-14 16:53
+1 👍

**Comment by alistairmcmillan** [comment] 2017-09-14 18:57
Duplicate of #11

**Closed by alistairmcmillan** 2017-09-14 18:57 UTC

**Comment by xenDE** [comment] 2017-09-14 23:38
No, #11 is auto at local time.

I want manual select the videos!
