### ISSUE TITLE
Doesn't work on 10.13.3 Beta (17D25b)

### ISSUE THREAD

**Issue by drekka** [JohnCoates/Aerial#433] opened 2017-12-27 06:33 UTC
The screen looks like some sort of sync issues is occurring, but I'm not sure. The screen save flashes up for a second, then the image is cut into lots of horizontal strips of the image.

**Comment by alistairmcmillan** [comment] 2017-12-27 16:53
@drekka Did this work okay for you in 10.13.2?

**Comment by alexeyst** [comment] 2017-12-29 08:49
It doesn't work for me on 10.13.2 — same thing with issues. It does work on Discrete video card though.

**Comment by alexeyst** [comment] 2017-12-29 08:54
Show with clock resolves it!

**Comment by alistairmcmillan** [comment] 2017-12-29 10:13
Closing as duplicate of #377

**Closed by alistairmcmillan** 2017-12-29 10:13 UTC
