### ISSUE TITLE
Aerial not working with MacBook 2017 using High Sierra

### ISSUE THREAD

**Issue by MikaelMahid** [JohnCoates/Aerial#405] opened 2017-10-22 12:32 UTC
I have a MacBook (Retina, 12-inch, 2017) running MacOS 10.3.1 and Aerial 1.2 just downloaded from you page in GitHub.

Aerial starts normally and in seconds fills the screen with horizontal lines.

Please see video attached.

Thanks

[IMG_1401 480.zip](https://github.com/JohnCoates/Aerial/files/1404871/IMG_1401.480.zip)

**Comment by alistairmcmillan** [comment] 2017-10-22 23:28
@MikaelMahid It's a known issue with High Sierra and certain models of Macs. Seems to be a problem with the Intel drivers. As a workaround for the moment, if you tick the "Show with clock" option the corruption should go away.

Closing as duplicate of #377

**Closed by alistairmcmillan** 2017-10-22 23:28 UTC

**Comment by MikaelMahid** [comment] 2017-10-23 09:13
Thank you very much for your answer with the workaround, it worked.

I apologize for duplicating the issue.

Congratulations for your software, best screensaver ever, very elegant, excellent implementation


On Oct 22, 2017 at 6:29 PM, <Alistair McMillan<mailto:notifications@github.com>> wrote:


@MikaelMahid<https://github.com/mikaelmahid> It's a known issue with High Sierra and certain models of Macs. Seems to be a problem with the Intel drivers. As a workaround for the moment, if you tick the "Show with clock" option the corruption should go away.

Closing as duplicate of #377<https://github.com/JohnCoates/Aerial/issues/377>
