### ISSUE TITLE
macOS 10.14 Support

### ISSUE THREAD

**Issue by fcs132** [JohnCoates/Aerial#470] opened 2018-06-10 22:59 UTC
I tried using the fix below, and it did not work. I'm still getting the "You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver." message

**Comment by tempusthales** [comment] 2018-06-19 13:09
Wanted to chime in...

I did two experiments... On macOS 10.13.5 and 10.13.4 I had aerial installed already, all videos cached, I was able to upgrade to Mojave and Aerial was working great... It even runs the screen saver from the login screen and looks pretty neat...

The second experiment was imaging a Mac from scratch into Mojave and then installing Aerial, here, the SS didn't run and gave me the above error...

**Comment by InDeNickOfTime** [comment] 2018-06-27 01:03
I upgraded to Mojave and had it on High Sierra working but not its not...

**Comment by aplittlecub** [comment] 2018-06-27 09:06
Installed after upgrading to Mojave, getting the above error - even after following the steps provided

**Comment by Civrock1** [comment] 2018-06-27 16:00
Just installed on the Public Beta on Mojave. Workaround for the system preference does not appear to work. 

Aerial works as a screensaver when selected, however there is a black bar of about an inch on the left while it's running. It's working fine during the lock screen but if cancelled the black bar reappears.

**Comment by alexriveraz** [comment] 2018-06-28 17:10
I just installed Mojave 10.14 Beta (18A314h) and Aerial works just fine for me, even the visual glitches (bars and scale problems) I was experiencing under High Sierra 10.13 disappeared!

**Comment by TheRealTremes** [comment] 2018-07-03 21:54
not works for me on Mojave 10.14 Beta - please update :-)

**Comment by JonoHaysom** [comment] 2018-07-05 04:28
still dead in b3

**Comment by HeminWon** [comment] 2018-07-05 06:59
me too

**Comment by regrob2** [comment] 2018-07-05 22:11
Upgraded from High Sierra to 10.14 public beta and I have this error now. The workaround did not work for me.

**Comment by bloemkool001** [comment] 2018-07-06 06:38
On High Sierra 10.13.6 it's not working :( Also the Clock option, Closing System Prev's...nothing.

The same error message appears and no screensaver showing :-/

**Comment by alistairmcmillan** [comment] 2018-07-06 10:15
Closing as duplicate of #464

**Closed by alistairmcmillan** 2018-07-06 10:15 UTC
