### ISSUE TITLE
Integrate the 21 newly released screen savers

### ISSUE THREAD

**Issue by abhsc** [JohnCoates/Aerial#277] opened 2016-12-16 20:57 UTC
Apple has released 21 new screen savers for the Apple TV, it'd be great to see these flow into a new version of Arial.

Thanks for all the hard work! Most of our office has this screen saver running and we all find it very soothing.

[http://www.macrumors.com/2016/12/16/apple-tv-new-aerial-screen-savers/](url)

**Comment by grahamj** [comment] 2016-12-16 20:59
Ha, just came here to say same:

https://9to5mac.com/2016/12/16/apple-updates-apple-tv-aerial-screensaver-with-new-hd-videos-featuring-dubai-greenland-los-angeles-and-more/

**Comment by alistairmcmillan** [comment] 2016-12-16 20:59
John designed the screen saver to automatically pick up new aerial movies. There isn't anything to do.

**Comment by abodnar** [comment] 2016-12-16 21:30
I don't know what triggers it to pull the new ones. But I still only have China, Hawaii, London, New York City, and San Francisco.

**Comment by alistairmcmillan** [comment] 2016-12-16 21:38
@abodnar If I'm reading the code right each time you launch the screen saver it should check the JSON file on Apple's server. If it can't it'll fall back to a saved copy.

If you aren't seeing the new locations make sure you have the latest version. https://github.com/JohnCoates/Aerial/releases/tag/v1.2beta5

If that doesn't help try rebooting (basically to make sure there isn't a copy of the screen saver process running). Instead of rebooting you could check Activity Monitor to make sure there are no System Preferences or Screen Saver Engine processes running.

If that doesn't help you might have something that is blocking access to Apple's servers. For example Little Snitch, or a corporate proxy, or something similar.

**Comment by holman** [comment] 2016-12-16 21:40
fwiw, I have the new ones listed:

<img width="620" alt="screen shot 2016-12-16 at 1 38 43 pm" src="https://cloud.githubusercontent.com/assets/2723/21279419/f98e21ac-c394-11e6-95e2-261adac41d51.png">

I didn't do anything other than open up the screen saver preferences (although they were already there waiting for me). If you don't have them yet, I'm assuming it's probably a caching thing, and you'll get them as Apple's CDN updates over the next few hours.

**Comment by abodnar** [comment] 2016-12-16 21:40
@alistairmcmillan Thanks. Looks like I didn't have the newest version.

**Comment by peterklijn** [comment] 2016-12-17 11:05
Mine we're in the list but not working. Reinstalling the screensaver worked though (via brew)

**Comment by alistairmcmillan** [comment] 2016-12-18 09:46
Closing as duplicate of #276.

**Closed by alistairmcmillan** 2016-12-18 09:46 UTC

**Comment by moooooooo** [comment] 2016-12-18 11:58
i didn't have to do anything - the new screensavers just displayed :-)
