### ISSUE TITLE
L.A. Airport Static

### ISSUE THREAD

**Issue by the-saint** [JohnCoates/Aerial#311] opened 2017-01-20 06:13 UTC
When I go to my Mac, sometimes the L.A. Airport screensaver is on but it's just a static image. It doesn't move. My Mac isn't frozen, and moving the cursor returns me to the desktop. I have only observed this behavior with this one scene.

**Comment by alistairmcmillan** [comment] 2017-01-21 22:35
Closing as duplicate of #278

**Closed by alistairmcmillan** 2017-01-21 22:35 UTC
