### ISSUE TITLE
Weather not displaying

### ISSUE THREAD

**Issue by mbierman** [JohnCoates/Aerial#1169] opened 2021-04-23 06:00 UTC
#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:  Mac mini (Late 2012)
- [ ] macOS version: 10.15.7 (19H524)
- [ ] Monitor setup: 1 monitor
- [ ] Ariel  2.3.0 

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

the new Weather isn't working. Nothing appears in Screen Saver and this error shows after "test". 
![image](https://user-images.githubusercontent.com/1205471/115825440-4d3eb100-a3be-11eb-80bc-6c4dd147a660.png)

Also, (https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md). still mentions yahoo! weather. that is no longer correct.

**Comment by mbierman** [comment] 2021-04-23 06:08
So I found the issue. 

"Santa Clara, California" works. So the error above is when OpenWeather doesn't find the location. It would be nice if the error provided was more specific.

**Comment by glouel** [comment] 2021-04-23 09:45
Interesting thanks for the report, I'll try to reproduce with that same string and see what happens ad let you know.

**Comment by glouel** [comment] 2021-04-27 15:39
@mbierman FYI, this will be fixed in 2.3.2, I've added a better error message when something goes wrong : 

![Capture d’écran 2021-04-27 à 17 35 57](https://user-images.githubusercontent.com/37544189/116270091-15998580-a77f-11eb-927d-29cf5da6a924.jpg)

Interestingly, while "City,abbreviatedUSstate" doesn't work, "Santa Clara" would return a "Santa Clara" in Cuba ;)

**Comment by mbierman** [comment] 2021-04-27 18:41
That looks perfect! Yeah, my limited experience with OpenWeather is similar. A little picky about things like that. This should steer most people in the right direction. Thanks for taking the time and effort to work around their issue.

**Comment by glouel** [comment] 2021-04-29 16:24
This is up in 2.3.2, thanks for the report again!

**Closed by glouel** 2021-04-29 16:24 UTC

**Comment by Erik262** [comment] 2021-05-13 21:40
Sorry for opening this up again, but since I updated to macOS 11.3.1 I always get the message "The operation couldn't be completed (Aerial.NetworkError error 2.)" when I want to test the weather overlay.

I also switched everything off which could interfere with Aerial, like lulu Adblock, etc. nothing helped so far.

**Comment by glouel** [comment] 2021-05-13 21:47
@Erik262 no worries, can you get me a debug log of you pressing the test button, so I can narrow it down ? I'll try to have a look tomorrow. Thanks !

**Comment by Erik262** [comment] 2021-05-14 10:45
> @Erik262 no worries, can you get me a debug log of you pressing the test button, so I can narrow it down ? I'll try to have a look tomorrow. Thanks !

Thanks for your response, I restarted my computer and installed Aerial again, now it works!
