### ISSUE TITLE
1.4.8: Chrome deems zip file unsafe

### ISSUE THREAD

**Issue by cryptochrome** [JohnCoates/Aerial#759] opened 2019-04-30 22:47 UTC
When downloading the new 1.4.8 release using Chrome, Chrome stops the download with a warning that the file is not safe, indicating Chrome's built in malware scanner detected something fishy. It could be a false positive, but please double-check your package and run a malware scan.

**Comment by Kavakuo** [comment] 2019-04-30 22:59
VirusTotal didn't detect anything malicious, seems to be safe and a false positive by Chrome. I got the same warning. [VirusTotal report](https://www.virustotal.com/gui/file/b0e120a3743d4e139c0a68bf800cd10803331f379dbf526bd5bfeeab4532414c/detection)

**Comment by cryptochrome** [comment] 2019-04-30 23:04
While VirusTotal is nice, it's not 100%, especially when it comes to macOS. I am saying this as someone who is an IT security engineer by profession. I would definitely be alarmed by this and do a deeper analysis. Mac malware is on the rise.

**Comment by glouel** [comment] 2019-04-30 23:04
Hi @cryptochrome & @Kavakuo

Do you have the same issue getting a beta, for example this one : https://github.com/JohnCoates/Aerial/releases/download/v1.4.7beta9/Aerial.saver.zip

?

Looks like their heuristics flagged us, the new version includes Sparkle, this open source project : https://github.com/sparkle-project/Sparkle , which shouldn't be an issue although that may trigger their heuristics for some unknown reason. 

I personally built the package (I do so for all the builds) and the .saver is signed with my personal Apple Developper ID. That's pretty much all the assurance I can give you.

**Comment by cryptochrome** [comment] 2019-04-30 23:09
Not getting a warning for the 1.4.7beta9 file. I'd still be extra cautious. Go get Eset for Mac. They have a 30 day trial version. It has one of the industry's best malware detection engines.

**Comment by Kavakuo** [comment] 2019-04-30 23:14
@glouel Betas download without warning, even the last one b12.

@cryptochrome Yeah, thought the same about VirusTotal and Mac software. But it detected that a Mach-O binary is included, scanned every file inside the bundle and even did a runtime analysis inside a sandbox. No detections should be at least an indicator for a false positive by Chrome.

**Comment by glouel** [comment] 2019-04-30 23:16
@Kavakuo thanks for the confirmation, I was going to ask ! b12 and 1.4.8 are identical featurewise for what it's worth.

**Comment by cryptochrome** [comment] 2019-04-30 23:20
I just downloaded the file from my computer in the office at work, which is protected by an enterprise firewall that decrypts SSL traffic and scans for malware using two different engines (Sophos and Avira). The file passed the firewall without being blocked, so those two engines didn't detect anything either.

**Comment by Kavakuo** [comment] 2019-04-30 23:22
@glouel But the builds are different? At least the hashes of `Aerial.saver/Contents/MacOS/Aerial` and the frameworks aren't the same between b12 and the final release.

**Comment by glouel** [comment] 2019-04-30 23:25
Yes different builds, sorry I wasn't clear. I meant just in terms of features they are identical, if one truly doesn't want to use the 1.4.8. We talked about the changes in this post https://github.com/JohnCoates/Aerial/issues/710#issuecomment-488137286 if you are interested, they are mostly cosmetic.

**Comment by Kavakuo** [comment] 2019-04-30 23:43
@glouel I guess the commits between b12 and final release shouldn't be really a problem. Do you still have the copy of the uploaded zip file locally on your Mac? Maybe you can compare the hash value of your local copy with a freshly downloaded zip file from GitHub. Just to be sure that nobody tampered the upload.

**Comment by glouel** [comment] 2019-04-30 23:59
@Kavakuo I can confirm they are identical, just redownloaded with Firefox and same as my build archive. MD5 (Aerial.saver.zip) = d32f7da0d110bf00afa15492a663faee FYI. 

The zip is also signed for Sparkle so if it was tampered with, other users would have reported an issue with the Sparkle updater. You can see the signature generated on my Mac in the appcast here : https://raw.githubusercontent.com/JohnCoates/Aerial/master/appcast.xml

**Comment by glouel** [comment] 2019-05-01 12:09
@cryptochrome & @Kavakuo 
Quick update, 1.4.8 actually had a crashing bug in case you launched the screensaver without opening the control panel (typical case for homebrew users). I don't know if this is what tripped Google but I did release 1.4.9 in any case.

I installed Chrome in a VM and Chrome complained that 1.4.9 was uncommon (duh), but not malicious. Same for 1.4.8 by the way (maybe it was fixed on their end ?). Can any of you confirm that 1.4.9 downloads as you expect with Chrome ? Thanks !

https://github.com/JohnCoates/Aerial/releases/tag/v1.4.9

**Comment by Kavakuo** [comment] 2019-05-01 13:46
Here it says "Aerial.saver.zip is an uncommon download and could be malicious" (translated from a german Chrome). Chrome links to this article [https://support.google.com/chrome/answer/6261569](https://support.google.com/chrome/answer/6261569). 

I think there are multiple categories for a warning as you can see in the article. Malicious, Unwanted and Uncommon. Aerial seems to be flagged with the latter one. Maybe this gets resolved as more people are downloading the file or the Google Crawler downloads the zip file and flags it as non malicious/uncommon. I have no idea what you could do on your end to fix this.

**Comment by glouel** [comment] 2019-05-01 13:50
@Kavakuo can you clarify for me, was it the same message you had yesterday, or did it explicitly said malicious ? That's what was implied yesterday, certainly not uncommon. 

I did see that article too here when I installed Chrome, and their 3 categorization. It makes sense it's seen as uncommon since it's just released.

**Comment by Kavakuo** [comment] 2019-05-01 13:56
@glouel I think so, but I'm not completely sure about this. Maybe @cryptochrome is. Nonetheless the warning says that it COULD be malicious. In addition with the only directly available dismiss button, this is alarming to the user.

**Comment by glouel** [comment] 2019-05-01 14:13
I tried to follow their website to issue a report but the link actually points to something else. Considering the beta builds don't give out the message (they were downloaded more) this may be transient until it gets downloaded more. If you can point me to a link to report the issue I'll gladly do so.

**Comment by glouel** [comment] 2019-05-06 13:15
So after a few days Chrome no longer give the "Uncommon download" warning. 1.4.8, 1.4.9 and even 1.4.10beta1 downloads normally, but the minute old 1.4.10beta2 does throw the warning. 

This is Google and with no clear way to fix this on their end, I'll close this. If you know how to fix this for a github repo, please let me know.

**Closed by glouel** 2019-05-06 13:15 UTC
