### ISSUE TITLE
Ignore Energy Saver Display Sleep

### ISSUE THREAD

**Issue by cucocreative** [JohnCoates/Aerial#138] opened 2015-11-04 18:27 UTC
When I am running the screen saver it seems to ignore the Energy Saver Display Sleep setting, I have the screen saver turn on after 5min and the display to go to sleep after 15min, but the display never goes to sleep.

**Comment by scsskid** [comment] 2015-11-06 13:18
I can confirm this

**Comment by vinceangeloni** [comment] 2015-11-07 00:14
Same here, have had it go for hours not realizing it.

**Comment by alistairmcmillan** [comment] 2015-11-07 12:19
@cucocreative @scsskid @vinceangeloni Which versions are you running?

**Comment by cucocreative** [comment] 2015-11-09 09:10
@alistairmcmillan  v1.1 on Yosemite

**Comment by alistairmcmillan** [comment] 2015-11-09 11:13
@cucocreative Try the latest beta. John made a change in one of the betas to resolve this issue.

**Comment by cucocreative** [comment] 2015-11-13 19:25
Yes, that has fixed it

**Comment by leo** [comment] 2015-11-17 22:03
Can confirm that this has been fixed! => Close this issue.

**Comment by alistairmcmillan** [comment] 2015-11-17 23:20
@cucocreative You can close this issue if you are happy that the problem is resolved.

**Closed** 2015-11-18 09:22 UTC

**Comment by Markyt1977** [comment] 2015-11-18 19:17
mark tegeda

**Comment by Markyt1977** [comment] 2015-11-18 19:17
mark tegeda
