### ISSUE TITLE
High Definition

### ISSUE THREAD

**Issue by nikhiljay** [JohnCoates/Aerial#156] opened 2015-11-10 05:16 UTC
Please make this high-definition (like on the Apple TV)! Right now it looks blurry and not as appealing on the retina MacBook Pro. Other than that, everthing is awesome. Keep up the good work!

**Comment by Markyt1977** [comment] 2015-11-10 08:44
mark tegeda

**Comment by trustypelletgun** [comment] 2015-11-10 18:03
These videos have been encoded by Apple at 1920 x 1080 resolution, 30 frames per second, at constant single digit bitrate (each video is between 3 to almost 8 Mbit/s). That _**is**_ high-definition and is close to the best quality that the Apple TV can display.

Upscaling these videos to fit the native resolution of your MacBook would not provide the same perceived quality as viewing them on a television through Apple TV, so there's nothing that can be done on this end to improve your experience.

Given:

1. Providing these videos at larger resolution provides no added value to Apple TV owners because they would have to be downscaled to fit the television's resolution.

2. Providing these videos at higher bitrates would result in larger file sizes (and hence increased bandwidth usage) with very little, if any, perceivable increase in image quality to Apple TV owners.

Therefore:
I wouldn't expect Apple to distribute higher quality versions of these videos anytime soon unless they decide to include these videos in a new screensaver for OS X (which would render this project unnecessary).

You get what you pay for.

**Comment by alistairmcmillan** [comment] 2016-01-29 10:48
Closing as duplicate of #15

**Closed by alistairmcmillan** 2016-01-29 10:48 UTC
Labels: duplicate
