### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by adymitruk** [JohnCoates/Aerial#201] opened 2016-01-23 20:50 UTC
I would love to see if this exists for Linux desktop environments. Or have this ported. It would show great support for the open-source community.

**Comment by adymitruk** [comment] 2016-01-23 20:50
It would complement beautiful environments like the latest plasma really well!

**Comment by alistairmcmillan** [comment] 2016-01-24 02:06
Duplicate of #137

**Comment by alistairmcmillan** [comment] 2016-01-28 21:11
Closing as duplicate of #137

**Closed by alistairmcmillan** 2016-01-28 21:11 UTC
Labels: duplicate
