### ISSUE TITLE
Screen goes black but videos don't start

### ISSUE THREAD

**Issue by bluestarstudios** [JohnCoates/Aerial#814] opened 2019-06-17 10:59 UTC
Hi!

First off: thanks for your incredible work! Really wonderful! Loving all the updates.

I'm having an issue where when the screensaver turns on, the monitors go black but the video never comes on. Using the mouse or any keys (including esc, left arrow, right arrow,...) to try to escape out of the screensaver only generates the MacOS alert sound as if the action wasn't allowed. Which means I'm stuck in the black screen. I've found two ways to work around this issue:

- **Hit the spacebar.** This triggers the actual screensaver videos to play. At this point, using mouse, esc key, or any other keys exits out of the screensaver as expected.
- **Click the power button on the back of my iMac**. This brings MacOS back to life.

All videos are fully cached, so I'm not sure why this is happening.

#### Required information
- [ ] Mac model: iMac (iMac14,2. 27-inch, Late 2013) 
- [ ] macOS version: High Sierra 10.13.6
- [ ] Monitor setup: 27" iMac + 27" Dell U2713HM
- [ ] Aerial 1.5.0

Replicated the bug in the logs. Especially that last time, including all the different keystrokes. Ended on Spacebar which triggered the video to play.
 
[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3296526/AerialLog.txt)

**Comment by glouel** [comment] 2019-06-17 11:11
Hi @bluestarstudios 

Sorry about that bug, just so I get it clearly, this does not happen all the time, but only some of the times ? Any hint about frequency ? From a quick look, you picked the mirrored mode for the video playback ?

I'll try to get back to you later today. But I had a quick look at your log but didn't find anything wrong. 

However your description makes me think that there's something stealing focus considering pressing the Esc key makes you hear the alert sound. Someone had a similar issue a while back with a 3rd party tool that customized keyboards (replacing keys), any chance you are using something like this ?

Another quick idea (if you see the bug say, once a day), if you enabled the check for updates when Aerial is active, maybe disable that ? It does seem super weird to me that it would be that but just shooting some ideas. 

Let me know if you have any keyboard specific utilities installed and we'll try to figure this one out.

**Comment by bluestarstudios** [comment] 2019-06-17 22:27
Hi Guillaume!

Thanks for the super quick reply! You’re a rockstar.

Great thoughts on all of the above. I do have Keyboard Maestro installed, which does let me override various keyboard actions, so who knows if that’s connected. I’ll disable it today and see if it has any effect on Aerial.

As for the frequency, I’d say it’s about 90% of the time. It’s become pretty consistent. I have run a bunch of tests, thinking that maybe the “Enable Right Arrow” function was affecting it, but that’s not it either. I’ve reset various caches and tried various troubleshooting steps on my end to see if by any chance something else was causing the issue, but no luck so far in any of the steps to be able to replicate the issue 100% of the time. Curiously enough, there have been a handful of seemingly random times when Aerial performed without a hiccup, so who knows, maybe the issue is in fact connected with Keyboard Maestro, which may have not been running during those moments. Let’s see. I’ll test and report back soon.

Thanks!
David

**Comment by glouel** [comment] 2019-06-17 23:02
> Hi Guillaume! Thanks for the super quick reply! You’re a rockstar. 

Hehe, I wish ;)

> Great thoughts on all of the above. I do have Keyboard Maestro installed, which does let me override various keyboard actions, so who knows if that’s connected. I’ll disable it today and see if it has any effect on Aerial. 

Ok let me know, see below for some more thoughts on this. 

> As for the frequency, I’d say it’s about 90% of the time. It’s become pretty consistent. I have run a bunch of tests, thinking that maybe the “Enable Right Arrow” function was affecting it, but that’s not it either. 

Ok so that rules out my auto update theory. 

> I’ve reset various caches and tried various troubleshooting steps on my end to see if by any chance something else was causing the issue, but no luck so far in any of the steps to be able to replicate the issue 100% of the time. Curiously enough, there have been a handful of seemingly random times when Aerial performed without a hiccup, so who knows, maybe the issue is in fact connected with Keyboard Maestro, which may have not been running during those moments. Let’s see. I’ll test and report back soon. Thanks! David
> […](#)

So it took me a while to remember, but the user who found an issue with some keyboard software (it was unrelated to yours) wrote a nice python script that tells you which app has focus, I highly recommend you give it a shot : 

https://gist.github.com/luckman212/91cdd9a08e98a9f01214bdfde3057e85

This will tell you who has the focus before Aerial starts and should help you debug. If you are curious about the issue we tried fixing back then, it was this one (you'll see outputs from the script there, the issue was about quitting the screensaver not entering) : https://github.com/JohnCoates/Aerial/issues/768

It includes in the end some info on mission control configuration and multiple monitors, since your issue is different this may not be related but who knows !

In any case, try the pyhon script, it should tell us quickly if someone steals focus from Aerial.

**Comment by bluestarstudios** [comment] 2019-06-18 05:08
Very interesting! Ok, so I ran the python script and /System/Library/CoreServices/ScreenSaverEngine.app (ScreenSaverEngine) activates properly every time and nothing else gets in its way. I tested with Keyboard Maestro Engine active, as well as without, and nothing was taking focus away. So that rules that out.

HOWEVER, as luck would have it, every single time I ran the test the screens would go black, stay there for about 10 seconds and finally the videos would load. It's like when you go to the doctor and everything is fine. In all of these tests I also never had any issues with keys or the mouse not being able to trigger an exit from the screensaver. So I am yet to have a full test that's able to replicate the problem when the videos don't load (as they have so many times in the past). VERY strange and peculiar. I will keep testing to see if I can replicate the bug and isolate what's going on. Let me know if you get any other ideas...

**Comment by glouel** [comment] 2019-06-18 09:20
Ha, I hate when that happens ! 

Some random morning thoughts:
- The fact that observing the events makes the problem (kinda) disappear is interesting in a way. I would guess it kinda suggest something was trying to steal the event but maybe it can't with the script, in some way ?
- So, just to be clear, did you also try without the script AND without keyboard maestro ? To rule out the observer effect which can go both ways.
- You mention a 10 second delay which is not something I saw in your logs. I'm wondering if either Aerial hangs for 10 seconds, or macOS doesn't call us for 10 seconds. Here's an idea, in notification center, you can add a watch. So, with the script running, do that and note the second (approximately) when you trigger the hot corner for the screen saver. Then paste me the log after that time you noted above. This should tell us if Aerial is started properly and hangs, or if system hangs then init Aerial.
- Can you maybe try another third party screensaver (Electric Sheep for example) to see if you have the same 10 sec hang issue there (with observer script and without) ?

One last thought, when checking your log again to make sure you didn't store your cache in a network drive or something that may be unrelaiably connected, I saw that your screens are 2048x1152. My guess is you are running some scaling mode for your screens ? Very much a long shot, but, maybe disable scaling just to see ? I think we have plenty of users with scaling, but I rarely see that on iMac logs so for some reasons that made me wonder.

That's a bit random but hopefully there's something in there that gives us a clue !

**Comment by glouel** [comment] 2019-06-18 09:30
Another late morning thought, maybe give a shot to latest beta. This is a verrry long shot but, one of the major changes I did is that those builds are now properly signed and notarized (so no more unknown developper id warning), which may make a change in how system initialize them. I assume if that was an issue in 10.14.5, loads of people would have complained already but who knows !

**Comment by bluestarstudios** [comment] 2019-06-18 20:52
Ok, so here are a few observations based on all of the above:
Python script shows that Screensaver process gets focus the moment the screens go black (2019-06-18 13:38:44). There's a 9-second delay from the moment the screens go black till the moment the video comes on and when the logs show the first log entry:
`2019-06-18 13:38:53 : avInit1 (0.0, 0.0, 2048.0, 1152.0)`

And yes, I'd also tried the tests without the script or Keyboard Maestro running.

I am noticing an interesting thing, which is that the preview in System Preferences also takes about 3-4 seconds to load. Can't even get into the Settings page before that.

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3303353/AerialLog.txt)

**Comment by glouel** [comment] 2019-06-18 21:03
Ok great, let me give you some quick feedback. 

To give you an idea, that log line you quoted is the first piece of code that Aerial actually runs. So it comes before eeeeverything else and is literally when our screensaver is finally initialized by the system. So the issue seems to come before that. 

So let's throw out anything specific to Aerial's internal functionning, like video playback or anything, the problem seems to happen prior to that system side.

I would highly suggest a couple of ideas : 

- give a try to latest beta here https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta4/Aerial.saver.zip , it's signed and notarized (unlike 1.5.0), maybe that could help if it's really some sort of weird initialization/gatekeeper issue you are having ?
- give electric sheep a try, and see if you have the same lag 

This might help narrow it down a bit further. Please let me know what both things do !

**Comment by tbnv** [comment] 2019-06-19 06:04
Hello,

I would like to add some more information, as I encounter the same issue.

- macOS Mojave 10.14.5 (18F132)
- iMac (Retina 5K, 27-inch, Late 2014)
- Aerial 1.5.0

I think the 2 main differences with @bluestarstudios' configuration is that I have the latest macOS version and no external display.

AFAICT it started with 1.5.0 that I upgraded just a few days ago.

I will definitely try the beta, and my log is attached.

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3304599/AerialLog.txt)

**Comment by tbnv** [comment] 2019-06-19 07:13
I still have the issue with v1.5.1beta4, sadly. 😞
New log attached.

[AerialLog.txt](https://github.com/JohnCoates/Aerial/files/3304818/AerialLog.txt)

**Comment by glouel** [comment] 2019-06-19 09:00
Bonjour @tbnv !

Sorry for that. Let me try to understand, can you confirm you are seeing *this*:

>Using the mouse or any keys (including esc, left arrow, right arrow,...) to try to escape out of the screensaver only generates the MacOS alert sound as if the action wasn't allowed. Which means I'm stuck in the black screen. 

>Hit the spacebar. This triggers the actual screensaver videos to play. At this point, using mouse, esc key, or any other keys exits out of the screensaver as expected.

Correct ?

Thanks for confirming that 1.5.1beta4 does not fix. And also for the info that you think it happened when you upgraded to 1.5.0.

I'm trying to see what you and @bluestarstudios may have in common, apart from the same generation of CPU (Haswell) that's about it. I'm currently running both macOS 10.14.5 and Aerial 1.5.1beta4 on a 2011 Macbook Air without your issue, so I'm not sure it's a generation thing. 

I'll try to make a list of ideas for both of you to try, feel free to pick the ones you want. Really sorry about this, but if you don't mind doing some testing, we'll figure this out!

**Comment by glouel** [comment] 2019-06-19 10:22
@tbnv and @bluestarstudios 

Here's a list of ideas, feel free to pick one (in bold) and try and report so we can try to narrow it down:

###  About needing to press space 

This does sound to me like a confirmation dialog for something, that is hanging you on. Pressing Esc won't dismiss (possible for some), Esc, left and right will ring the bell, spacebar is equivalent to clicking the default value of the confirmation dialog. 

- **Can you launch screensaver and try pressing Return instead of space bar and see if that works too ? If that does, that would probably give us a hint it's a dialog thing. Next, try again, press Tab. Does it ring ? If not, after pressing tab once, press space. Then quit screensaver/relaunch, still stuck or not ?**

- **When stuck, can you try pressing Cmd + Shift + 3. You should hear a shutter sound, it's a shortcut to make a full screen capture (it will appear on your desktop). It probably will be all black but maybe not ?**

### Looking into console

- **Start console.app, on the left you have a list with System Reports and User reports. Open each, and look for a file in the column that appears with a name that starts with something like System Preferences, screenSaverEngine, or Aerial (or anything that sounds screensavery !). Attach those**
- **Capturing all system logs to see what's wrong : In console.app, at the top of the list you'll see your computer name, click that. On the right you'll see scrolling tons of system messages. Press "Clear" to clear the list, then launch the screensaver (through a hot corner) and use the space bar thing (maybe wait 5 seconds ?). Then quit screensaver, go back to console, press cmd+A to select all, cmd+c to copy all and paste that into a text editor and attach it**

(logs are anonymized but if you are unconfortable having them online I can give you an email)

### Finding which version messed things up

If it's a regression in 1.5.0, we might be able to pinpoint where it happened through the betas. 

First, can you first go into Updates tab of Aerial and make sure that these three are **UNCHECKED**
- Automatically check for updates
- Auto install updates while the screen saver runs
- Look for beta updates

(You may want to see if that fixes the bug, though I doubt it)

Then:
- **Try 1.4.9 (it's the same as 1.4.8)** https://github.com/JohnCoates/Aerial/releases/download/v1.4.9/Aerial.saver.zip

Is the bug gone ?

If not: 
- **Try 1.4.6** https://github.com/JohnCoates/Aerial/releases/download/v1.4.6/Aerial.saver.zip

**If 1.4.9 works fine, and you feel patient (I'm sorry for asking this!), here's a list of the betas (in chronological order)** : 

https://github.com/JohnCoates/Aerial/releases/download/v1.4.10beta1/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.10beta2/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.10beta3/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.99beta1/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.99beta2/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.99beta3/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.99beta4/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.99beta6/Aerial.saver.zip
https://github.com/JohnCoates/Aerial/releases/download/v1.4.99beta7/Aerial.saver.zip

I'd suggest you cut the list in half by starting in the middle, then keep cutting the remaining in the middle. This is a bit of a pain to do, really so try that one last.

Ok that's about all I can think of right now. Hopefully we can narrow it down and fix the issue!

**Comment by tbnv** [comment] 2019-06-19 16:03
I should have told it, on my side I must press `Enter`.

**Comment by glouel** [comment] 2019-06-19 17:04
> I should have told it, on my side I must press `Enter`.

Ok... This is a weird bug, I have to say 🤔 Let me know if you can check some of the other stuff I suggested !

**Comment by tbnv** [comment] 2019-06-20 12:03
This morning after I powered the iMac the problem occurred the 1st time the screensaver launched. I didn't read your message above at that time, so I didn't gather more info.

I wasn't able to replicate the bug after that, by manually launching Aerial (with Alfred.app, then with an active corner). I must have tried 40 times. Even after logout+login.

Now after lunch, I want to wake up the computer but the screen remains black. I took a screenshot. It's attached (downscaled a bit, 'cause Githut limits file size). Result: he screen is black, though the screenshot captures the beginning of the video + description text + a bunch of Mail.app notifications.

I disabled updates options, let's see.

<img width="1280" alt="capture" src="https://user-images.githubusercontent.com/1021579/59847913-20558900-9364-11e9-997e-b5f4d548ffcc.png">

**Comment by glouel** [comment] 2019-06-21 11:49
> This morning after I powered the iMac the problem occurred the 1st time the screensaver launched. I didn't read your message above at that time, so I didn't gather more info.

Ok hopefully you can try and capture then. Note that you could also try Cmd+shift+5 to capture a window (try to click in the middle where a dialog box would be). Not sure that would work though with  

> I wasn't able to replicate the bug after that, by manually launching Aerial (with Alfred.app, then with an active corner). I must have tried 40 times. Even after logout+login.

That's super weird, I'm wondering if it's not a sparkle dialog (did you ignore by any chance the prompt you get the first time asking you if you want to enable auto updates or not ? and keep ignoring it ?). That could be consistant with once a day but that seems a bit weird. Other that that Sparkle should not fire any dialog if there's no update (and even then it kill the screensaver). 

> Now after lunch, I want to wake up the computer but the screen remains black. I took a screenshot. It's attached (downscaled a bit, 'cause Githut limits file size). Result: he screen is black, though the screenshot captures the beginning of the video + description text + a bunch of Mail.app notifications.

This is interesting. Unlike the logs both of you pasted previously, Aerial was running this time. So I guess Aerial ran normally, computer went to sleep, and when waking it up whatever dialog box popped messed up everything and there you go with a black screen "on top" of a properly running aerial behind. 

> I disabled updates options, let's see.

Ok let me know...

**Comment by bluestarstudios** [comment] 2019-06-24 00:18
Hi all!

Just want to let you know that I’m traveling for the next week, so I’ll be able to resume any testing on my end as soon as I’m back. Though hopefully you manage to even figure it out before then.

Thanks!
Chat soon!

David


Sent by magic!

**Comment by tbnv** [comment] 2019-06-27 12:18
Hi there,

Just to let you know that I didn't encounter the problem anymore, since I disabled the options to check for updates.

**Comment by glouel** [comment] 2019-06-27 21:35
Hi @tbnv 

I guess that's good, in a sense, so it's the update when screensaver is running that's the culprit. Do you remember if you installed Aerial for all users, or just your user ? Trying to think of what could be behind it...

**Comment by tbnv** [comment] 2019-07-04 07:20
@glouel I don't remember that. Is there a way to tell this without creating a new user account on the Mac just to test th? (I like to keep things tidy).

**Comment by glouel** [comment] 2019-07-04 08:27
@tbnv no need to create an account, just look into 

`/Library/Screen Savers/`
and
`~/Library/Sceen Savers/`

First one, all users, second one, just your user. 

As for your testing, may I suggest you try to only enable "Automatically check for updates" and **NOT** "Auto install updates while screen saver runs". 

My guess is the second one is the culprit from what you described. If it looks good with the first one, then you might want to try the second one and confirm it's indeed that one.

Thanks !

**Comment by tbnv** [comment] 2019-07-04 09:50
Thanks for the tip; I confirm it's installed only for me.

**Comment by tbnv** [comment] 2019-07-09 09:21
Having only "Automatically check for updates" enabled for a few days didn't block the screensaver. However, now that I turned "Auto install updates while screen saver runs" on, I got the problematic behavior again.

**Comment by glouel** [comment] 2019-07-09 09:23
Awesome, that narrows it down then. 

I'll have to rethink that feature I guess, that's slightly less awesome !

**Comment by glouel** [comment] 2019-07-09 09:35
@tbnv one last thing, can you clarify if you are running an administrator account on your mac, or any chance this is some sort of company/managed account that may have some sort of restricted privileges or default settings/management applied ?

**Comment by tbnv** [comment] 2019-07-09 09:36
I'm using an administrator (and the only) account on this iMac.

**Comment by bluestarstudios** [comment] 2019-07-12 22:22
@glouel Finally back from all my travel and read all the comments on things you guys tried. The suggestion that @tbnv had around the auto-update led me down a research path and looks like I found our culprit! So I run Little Snitch to control outgoing connections. Turns out that Little Snitch had automatically blocked "outgoing TCP connections to raw.githubusercontent.com" made by the ScreenSaverEngine. When I went in altered the rule to allow, suddenly the screensaver started behaving correctly again. So looks like if the Sparkle updater doesn't connect to the server to check for updates, the screensaver never actually loads. Does this sound like it could be it?

**Comment by glouel** [comment] 2019-07-12 22:35
> @glouel Finally back from all my travel and read all the comments on things you guys tried. The suggestion that @tbnv had around the auto-update led me down a research path and looks like I found our culprit! So I run Little Snitch to control outgoing connections. Turns out that Little Snitch had automatically blocked "outgoing TCP connections to raw.githubusercontent.com" made by the ScreenSaverEngine. When I went in altered the rule to allow, suddenly the screensaver started behaving correctly again. 

Oh, wow. First, great bit of investigating! 

> So looks like if the Sparkle updater doesn't connect to the server to check for updates, the screensaver never actually loads. Does this sound like it could be it?

That could totally be it. That special weird update check is the very first thing that Aerial does on startup. I'm unclear whether Sparkle should block if the connection failed (which should be what happen with a firewall) but apparently that's what you saw so it could make complete sense indeed. In order to make the silent update work, I had to use some less used code path by Sparkle (they clearly don't recommend it, but that was the only way I found to make it work without having a companion app). So it's very possible that in this mode, it's blocking. 

Can you please monitor it in the next few days and let me know if it looks fully fixed ? In any case, many many thanks for giving a more thourough look to this. Considering how few people so far were hit, Little Snitch could definitely be behind this. 

@tbnv any chance you were running Little Snitch or another firewall?

**Comment by tbnv** [comment] 2019-07-13 05:16
Yep, I'm using Little Snitch as well! I'm on vacation right now so I'll check its rules when I go back home to see if there is a similar one on my side.

**Comment by glouel** [comment] 2019-07-13 07:58
Thanks for answering @tbnv , enjoy your vacations !

**Comment by tbnv** [comment] 2019-07-23 14:39
@glouel I don't have a Little Snitch rule preventing `ScreenSaverEngine` from fetching content from `raw.githubusercontent.com`.

**Comment by duecedriver** [comment] 2019-08-30 06:05
yeah.. this is confirmed.. a different way..

looks like when it goes active it goes straight to the lock screen and its frozen.

I have 2 monitors so I set prefrences for it to only start on my second monitor

as soon as I pressed test.. both screens went to lock screen but where frozen, has to SSH into the machine and killall loginwindow to regain control

is there a script or do you have a comprehensive uninstall to remove everything I will try and revert to a previous version that I had working

**Comment by glouel** [comment] 2019-08-30 09:54
> yeah.. this is confirmed.. a different way..
> 
> looks like when it goes active it goes straight to the lock screen and its frozen.
> 
> I have 2 monitors so I set prefrences for it to only start on my second monitor
> 
> as soon as I pressed test.. both screens went to lock screen but where frozen, has to SSH into the machine and killall loginwindow to regain control
> 
> is there a script or do you have a comprehensive uninstall to remove everything I will try and revert to a previous version that I had working

Hey @duecedriver 

Sorry about that, I think that 1.5.0 has some issues with some setups it seems, which vesrion of macOS are you running ? To uninstall, you only need to remove Aerial.saver, you can find instructions here : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Installation.md#uninstallation 

You only need to delete the .saver. 

If you're willing, I'd suggest you give latest beta a shot : https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta11/Aerial.saver.zip

Let me know if this fixes things for you.

**Comment by duecedriver** [comment] 2019-08-30 14:38
ok... I deleted most of what I could find  running mojave by the way

re-installed 1.4.9 I think.. last non beta prior to 1.5

selected h264 and tested.. worked

upgraded to 1.5 again
same thing jammed up
killall loginwindow from remote machine gets me back in
went in selected single screen and h264.. worked
selected single screen h265, worked
selected 4k hevc.. now working..  but not reliably 

some hook between the screensaver and loginwindow process is likely not syncing up

**Comment by glouel** [comment] 2019-08-30 14:44
- Which version of macOS are you running ?
- Did you try 1.5.1beta11 : https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta11/Aerial.saver.zip

**Comment by glouel** [comment] 2019-10-01 17:03
Closing this as the original issue was Little Snitch. Version 1.6.1 fixes an important crash/hang bug that was introduced in 1.5.0 :  https://github.com/JohnCoates/Aerial/releases/download/v1.6.1/Aerial.saver.zip

**Closed by glouel** 2019-10-01 17:03 UTC
Labels: third party
