### ISSUE TITLE
Crashing

### ISSUE THREAD

**Issue by butchb** [JohnCoates/Aerial#394] opened 2017-10-03 18:11 UTC
It crashes with High Sierra, Thanks

**Comment by alistairmcmillan** [comment] 2017-10-03 20:01
@butchb Could you expand a little on this? What model of Mac are you running it on? When you say it crashes, do you get an error message? Does it show graphic glitches? What actually happens?

**Comment by chrsjhnsn** [comment] 2017-10-04 15:17
Here with the same issue. Happens on my 2017 iMac and my 2012 rMBP. Aerial ran fine on Sierra but crashes on High Sierra. There's no error message and no graphic glitch. When the screensaver starts (naturally on the timer or forced by hot corners) the screen goes black and then kicks back to the desktop after 2-3 seconds.

If the security preferences are set to lock the computer immediately after a screensaver begins, then instead of kicking the user back to the desktop they're presented with the unlock screen.

**Comment by alistairmcmillan** [comment] 2017-10-04 15:19
@chrsjhnsn Do you have the [latest version installed](https://github.com/JohnCoates/Aerial/releases/tag/v1.2)? Do you have the videos cached?

**Comment by chrsjhnsn** [comment] 2017-10-04 15:20
Latest version installed, all videos cached.

**Comment by alistairmcmillan** [comment] 2017-10-04 15:25
@chrsjhnsn Just for the sake of testing, could you try deleting the Aerial.saver file from your Macs and installing the [latest version](https://github.com/JohnCoates/Aerial/releases/tag/v1.2) again? You don't need to touch the folder with the cached videos. Make sure to check both install locations. `/Library/Screen Savers` and `/Users/YOURUSERNAME/Library/Screen Savers/`

There have been weird problems in the past where the Aerial.saver file (which is actual a bundle with a bunch of files inside) has somehow become corrupt. Never quite sure how it happens, but deleting and re-installing is a quick fix.

Let us know if it helps.

**Comment by chrsjhnsn** [comment] 2017-10-04 15:28
Unfortunately, that didn't fix it on the iMac. I can try it out on the MBP tonight.

**Comment by chrsjhnsn** [comment] 2017-10-04 15:30
Just tried deleting the cached videos too, for good measure. Still the same crashing problem though.

**Comment by alistairmcmillan** [comment] 2017-10-04 15:31
@chrsjhnsn Are you behind a corporate firewall or proxy? Aerial could be crashing because instead of sending back the expected JSON file, your proxy might be sending back something else like an authentication request or an access denied message.

**Comment by chrsjhnsn** [comment] 2017-10-04 15:39
Hmmm. Ok, currently I am behind a firewall. I'll test it from a clean connection as soon as I'm able.

Why would this start happening after the upgrade to High Sierra though? Could that just be a coincidence?

**Comment by chrsjhnsn** [comment] 2017-10-04 17:45
Worth noting - hitting "Preview" in the screensaver page in System Settings loads the Aerial just fine. It's only when called through hot corners or timing that the crash occurs.

**Comment by sschadwick** [comment] 2017-10-05 20:22
I had the same issue (on multiple computers). Initially thought it was a LittleSnitch issue, but I was able to resolve the issue by re-caching the video files.

**Comment by remydb** [comment] 2017-10-07 12:13
Same problem that it crashes on High Sierra here.
A workaround that seems to work for me is to tick the "show with clock" box. Only downside is that you'll have a clock on the screensaver...

**Comment by jin1234533** [comment] 2017-10-07 15:19
Same thing happened here, redownloaded the latest issues and recaching all the videos. Remydb's solution works, show with clock works

**Comment by RoyHP** [comment] 2017-10-07 16:18
I have the graphical glitch, even after deleting and re-downloading. Show with clock resolves it, but has the clock.

**Comment by mluisbrown** [comment] 2017-10-11 12:24
I have the issue on my work 2017 MBP 15" but it's fine on my 2016 MBP 13" with TouchBar. Both with High Sierra. Could be a GPU issue? My 13" MBP doesn't have a discrete GPU, the 15s do.
Show with clock also resolves, but it's ugly.

Previewing the screen saver also glitches on my 15" unless I have the clock enabled.

**Comment by lfuller** [comment] 2017-10-12 21:16
After trying to uninstall, reinstall, delete from Library, etc. I found that disabling the Automatic graphics switching (Energy prefs) fixes the issue.  I am using a 2016 MacBook Pro 15" with TouchBar with the Intel HD Graphics 530 chipset and running MacOS High Sierra.

**Comment by alistairmcmillan** [comment] 2017-10-13 10:04
No reply from OP. And aside from that this is just turning into a duplicate of #377 .

**Closed by alistairmcmillan** 2017-10-13 10:04 UTC
