### ISSUE TITLE
"You cannot use the Aerial screen saver with this version of OS X." message

### ISSUE THREAD

**Issue by arsradu** [JohnCoates/Aerial#466] opened 2018-06-06 20:42 UTC
> ### "You cannot use the Aerial screen saver with this version of OS X." message
> 
> If you get a message saying `You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver.` that is a known bug with macOS that was reported to Apple in April 2016 as [rdar://25569037](http://openradar.appspot.com/25569037). As of November 2017 the bug is still not fixed. To work around the bug:
> * select the Aerial screensaver in System Preferences
> * close System Preferences with Aerial selected
> * reopen System Preferences and the preview should work now

Any chance you can get this working in MacOS 10.14? The workaround suggested above doesn't work here anymore (could also be a bug of the OS, but never experienced it with Sierra and High Sierra).

**Comment by arsradu** [comment] 2018-06-07 12:10
Does it work in System Preferences preview, as well? Cause...that one doesn't work for me.

**Comment by innrwrld** [comment] 2018-06-07 12:27
No, in System Preferences preview it shows the alert for me.  It works normally as it seems like the service is still running properly, just having some issues stopping as you authenticate.  I imagine the project owner could pull a new copy of the service from the upcoming tvOS & do this the same way.

**Comment by arsradu** [comment] 2018-06-07 12:31
Yep. So it's just the preview (and I suppose the actual screensaver settings) that don't work. But if you apply it, it will work. It's just that it won't stop properly when you try to authenticate.

And yeah, I hope the owner can fix this. Cause, at least to me, it's by far the best screensaver I've used so far.

**Comment by alistairmcmillan** [comment] 2018-07-06 10:35
Closing as duplicate of #464

**Closed by alistairmcmillan** 2018-07-06 10:35 UTC
