### ISSUE TITLE
Weather temp. for "Use current" location not the same as my local Yahoo temperature info at their site

### ISSUE THREAD

**Issue by Pcar17** [JohnCoates/Aerial#1150] opened 2021-01-27 16:29 UTC
The local temperature displayed when Arial is running is not the same temp as the local Yahoo temperature being reported at their site.  I have checked to ensure that the location being used is my current location and the same location that I'm getting Yahoo info for directly. Thx! 

HW:  MacOS 11.1 -- M1 MacBook Air -- No external monitor.

#### General troubleshooting tips

Before logging an issue please check that:
- [ ] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [ ] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [ ] Your problem isn't mentioned in the [troubleshooting page](https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model:
- [ ] macOS version: 
- [ ] Monitor setup:

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Replace this}}

**Comment by glouel** [comment] 2021-01-27 16:37
Hey @Pcar17 

Is it a big difference ? When you use your current location, it uses the location from the coordinates, so that can vary a tiny bit if you live in a large city for example. If you check the debug log you should get something called woeid (Where on Earth ID) which is what it uses to check your location. There might be a small variation between that and the API.

**Comment by Pcar17** [comment] 2021-01-27 17:06
Hi @glouel -

My bad for not providing that info above!  

So Yahoo is reporting 32° vs Arial reporting 23° (9 degrees difference) for my current location.  The actual location in the pop-up when clicking "Test" when configuring the weather setting is accurate and what I plugged into Yahoo.  

Also, when I hard code the location in Arial, and try a handful of other cities, it is still different from that same named location at Yahoo--by 5-9°.  Arial is always higher.  Also, the current condition icon in Arial is not accurate...it seems to be out of date by 12-24 hours?

**Comment by glouel** [comment] 2021-01-27 17:53
I'll double check that tomorrow and get back to you. It's quite possible I4m showing yesterday's weather and never noticed...

**Comment by Pcar17** [comment] 2021-01-27 18:29
@glouel -
Great and thanks for checking on this!  Just let me know here if you would like me to test anything or provide more info including screen shots.

**Comment by glouel** [comment] 2021-02-02 17:35
@Pcar17 sorry for the lag...

I started looking into it and can confirm the discrepency : 

<img width="769" alt="Capture d’écran 2021-02-02 à 18 23 42" src="https://user-images.githubusercontent.com/37544189/106639577-65542080-6585-11eb-953a-81809c2320a0.png">

Not sure what's happening, I'm investigating right now and will let you know !

**Comment by Pcar17** [comment] 2021-02-02 17:55
Hi,
Thanks for the update.  Let me know if you want me to try anything.

**Comment by glouel** [comment] 2021-02-02 18:05
Ok so, I've investigated it a bit more with Postman, making sure my requests were correct, and as best as I can tell, the API sometimes returns wrong/outdated data. Right now it does return the correct stuff for me but I guess the data was outdated for a few hours or just plain wrong. But that's not the worse part, I just saw this checking Yahoo!'s documentation : 

> As of Monday, March 1, 2021, the free Yahoo Weather API will be retired.

So that may explain the discrepencies we're seeing. To be honest this is depressing... I don't think there's an API out there with a free plan that would work, without me proxying to some server. I'll need to have another look at this but this is sad.

**Comment by Pcar17** [comment] 2021-02-02 18:10
@glouel,
Wow...that's a disappointment. Having the weather overlay is such a nice touch!

**Comment by Pcar17** [comment] 2021-02-06 18:02
Hi @glouel,
Over the last few days, it looks like the API is returning accurate temps.  Here is the Weather widget and Aerial right now (and, ye!, it is freezing cold here in the Midwestern USA---the wind chill temps this weekend are forecast to be as low as -30 degrees F!):

<img width="329" alt="Screen Shot 2021-02-06 at 11 58 37 AM" src="https://user-images.githubusercontent.com/44177062/107125981-ad6b8f80-6872-11eb-8d9c-dec24b8e8244.png">

<img width="329" alt="Screen Shot 2021-02-06 at 11 57 25 AM" src="https://user-images.githubusercontent.com/44177062/107125985-b0668000-6872-11eb-95e1-9aba1244d426.png">

Any luck on a simple (and free!) replacement?  Does Apple have an exposed API available that they use to grab the weather for their own macOS Weather widget?

**Comment by glouel** [comment] 2021-02-08 13:17
> Hi @glouel,
> Over the last few days, it looks like the API is returning accurate temps. Here is the Weather widget and Aerial right now (and, ye!, it is freezing cold here in the Midwestern USA---the wind chill temps this weekend are forecast to be as low as -30 degrees F!)

And wow, -that's 34°C, I can't even imagine. The current coldwave means we have +1°C by day (so +34ish and that's really cold for where I live ;) 

> Any luck on a simple (and free!) replacement? Does Apple have an exposed API available that they use to grab the weather for their own macOS Weather widget?

Sadly nope for Apple. They bought Dark Sky and I want to believe they'll add an API at some point, I'd posit free just to get current user's weather directly from macOS (using the location that the system knows), and a paid tier for accessing more locations or something. But for now, nothing of the sort.

So simple solution, none so far but I'm still looking !

**Comment by Pcar17** [comment] 2021-02-08 14:35
@glouel .... thx & good luck. Let this group know if/when you would like us to test anything. 🥶

**Comment by glouel** [comment] 2021-03-01 15:49
@Pcar17 very quick update, just to say I may have some good news soonish on that front, I'm waiting to hear from OpenWeather which may lift limits on a FOSS project account (and thus make  the implementation simple for me, plus possibly much better data than just what I had currently). Crossing fingers.

Also, right now the Yahoo API is still responding, but it's giving me outdated data (says 2°C while it's 14°C).

**Comment by Pcar17** [comment] 2021-03-01 18:30
Wow, that is fantastic news!  

FWIW, Yahoo Weather is pretty good for me today so far.....Aerial within 1 degree F of Yahoo dot com. Very interestingly, Arial was not initiating for me earlier today for whatever reason even after a reboot (I'm running the lastest macOS beta on an M1 Mac). But now it's working fine. I was going to reach out an ask if you had heard of others having a similar issue. I wonder if Yahoo pulled the plug on the API and then decided to temporarily put it back after they broke some of their own stuff?

Cheers! 
 
👌☀️🌡
 
<img width="382" alt="Screen Shot 2021-03-01 at 12 27 05 PM" src="https://user-images.githubusercontent.com/44177062/109541489-7b240b00-7a89-11eb-8977-2795ec8634c7.png">

**Comment by glouel** [comment] 2021-03-01 18:54
> Very interestingly, Arial was not initiating for me earlier today for whatever reason even after a reboot (I'm running the lastest macOS beta on an M1 Mac). But now it's working fine. 

Weird. So like everything would hang at startup ?  

> Note: I'm not sure though what Arial does if the Weather API isn't working or not even "there"? I did try to turn it "off" when looking at the issue earlier but it was still didn't initiate. But after an hour or so, it's now fine.

Well it should start playing independently, the weather fetch is supposed to be asyncroneous (unless I'm very mistaken which is possible, been a while), and Aerial will actually keep waiting for the API to reply if needed but still start the video playback (earlier versions as far as I recall would just never display weather if Yahoo replied too slowly). 

Glad to hear it's okish for you right now with Yahoo, it's quite possible they shut it down, broke stuff and put it back again (interestingly I never even received an email from them ! I found out checking their website...) and crossing fingers for openweather but if all goes right, we'll have a ton more data too on top of it (various forecasts and maybe even pollution).

**Comment by Pcar17** [comment] 2021-03-01 19:03
@glouel,
Not "hanging"....I just got a blank (all black) screen both in Preview mode as well as my Hot Corner "switch" to start it up.  But I could easily interrupt and login.  And still working ok now on my 11.3 Beta (20E5186d) returning good weather info. Thx!

**Comment by glouel** [comment] 2021-03-01 20:11
Intriguing, thanks for the info, it could be weather I guess, black screens were, as far as I know (for other reasons), wiped out of the latest builds !

**Comment by glouel** [comment] 2021-03-03 16:00
@Pcar17 still waiting to hear from openweather but after a couple of days where temperature was stuck at 2°, things are working again here today. 

Did a double check on Yahoo and they pushed it back to may 1st which might explain things !

**Comment by Pcar17** [comment] 2021-03-03 17:59
Hi @glouel,

Thanks for the update. I'm seeing correct weather data for me from Yahoo in your screen saver. 😀

<img width="319" alt="Screen Shot 2021-03-03 at 11 35 41 AM" src="https://user-images.githubusercontent.com/44177062/109847382-be5eb500-7c14-11eb-9118-52e696775dc7.png">

Also, I am already running 11.3 Beta 3 that was released yesterday and things are working well.  I had location services issues in earlier versions of Big Sur but I they seem to have been resolved (I believe that they were only related to the M1's).

**Comment by glouel** [comment] 2021-03-04 19:40
@Pcar17 thanks for the info on the location services ! I didn't see that issue here on my Intel mac so you are probably right wit it being a M1 issue. 

I did release the very first version with support for OpenWeather, still a bit raw, may not work for everyone, but the data is better. And no more logo ;)

<img width="245" alt="Capture d’écran 2021-03-04 à 19 24 05" src="https://user-images.githubusercontent.com/37544189/110020376-c3f9ef00-7d29-11eb-9e69-2cd506928de3.png">

There's the feels like info which is pretty important (at least here). Some rounding will be needed, I'll keep working on it. If you are curious check beta2 that I just posted.

**Comment by Pcar17** [comment] 2021-03-04 20:03
Just installed.  Wow...and it's accurate!

See the screen shot.  Is there a way to expand the "mask"?  I'm using the default 40 point font and you can see it's cutting off part of the temp.  Or just convert the temp to a whole number?


![IMG_1644](https://user-images.githubusercontent.com/44177062/110022947-2afbb180-7cf2-11eb-87b2-6308bf9beecb.jpeg)

**Comment by glouel** [comment] 2021-03-04 20:19
Yep I need to rethink the whole font size thing here ! It's a bit of a mess and it's messing with the picture size and what I can do. I'm considering not allowing font size, but just scaling the whole thing, because there's more data in the feed that could be interesting to add. I'll probably give the option between a few levels of details (do you want wind or not, visibility, etc). 

I'm not a farenheit perso so I'm not sure if rounding to 1 digit (33.9) or just rounding (34) is the way to go ? 

For celsius I'll do one decimal I think (so 17.5) because that's the usage here.

**Comment by Pcar17** [comment] 2021-03-04 21:02
Yw! All sounds good!  

I would say that using a rounding function to convert to a whole number for Farenheit would be convention here in the US.  Unless you want to put in a drop-down widget to adjust to 0, 1 or 2 places?  I say not necessary  but you're the author! :-)

**Comment by glouel** [comment] 2021-03-05 18:04
Love that scene, really looks great with that overlay arrangement too ! 

Beta 3 is up, I tweaked a few things visually, added rounding to whole for farenheit and 1 decimal for celcius, and have added wind direction, here's how it looks now : 

<img width="207" alt="Capture_decran_2021-03-05_a_18 21 26" src="https://user-images.githubusercontent.com/37544189/110155136-7642bc80-7de5-11eb-874a-3cfc1cd2add9.png">
(farenheit with the super weird colors icons... I'm not a fan quite frankly but that's what they give)

<img width="210" alt="Capture d’écran 2021-03-05 à 18 24 30" src="https://user-images.githubusercontent.com/37544189/110155174-8a86b980-7de5-11eb-83dd-e4f3e2621ea8.png">
(celcius with flat icons)

I may make the wind direction optional (or just wait to hear back from them, still waiting, to see if we get access to forecasts which would mean I'd make several versions of this).

**Comment by Pcar17** [comment] 2021-03-05 18:25
😀 Looking great!  But what is the second data item in ()'s?

![IMG_1648](https://user-images.githubusercontent.com/44177062/110157054-5ee7dd00-7dad-11eb-98e1-6f0fd6d73235.jpeg)

**Comment by glouel** [comment] 2021-03-05 18:27
Oh yeah that's the "feels like" temperature ! Not sure what's the convention to display it in a compact form ? It's certainly not self explanatory here...

**Comment by Pcar17** [comment] 2021-03-05 18:29
Got it.  Glad that you are using MPH with F (and km with C....but shouldn't it be km/h?).

**Comment by glouel** [comment] 2021-03-05 18:31
Woops, it's actually m/s ! Good catch, guess I got confused with their units. Thanks !

**Comment by Pcar17** [comment] 2021-03-05 18:32
Okay...yw!

**Comment by sugarquay** [comment] 2021-03-06 08:58
Unfortunately with beta 3 it's quite a mess here. Font sizes used are fairly large as Aerial is running on a Mac mini attached to a TV, so is being viewed from across the room.

I've never known temperature displays to include decimal places, and would rather not see them.

At the current font sizes, neither wind speed nor "feels like" can be read from across the room — so options to remove both would be fantastic. 

![Screenshot 2021-03-06 at 10 40 42](https://user-images.githubusercontent.com/37441096/110201059-d1b68e00-7e69-11eb-8cd3-0c537920f76d.png)

**Comment by glouel** [comment] 2021-03-06 12:26
Yes per what I wrote above @nicacy, this is still very much a WIP and only looks correct around default font size. It's always been a problem to a degree as symbols were always fixed size, while the font size was not. Proportionate scaling of symbols to your font setting (so everything looks "right" and can be scaled any way) is coming. 

Decimal is not classic for forecast but fairly common on current observations, my Netatmo gives me 1 decimal for example :
<img width="670" alt="Capture d’écran   2021-03-06 à 13 21 26" src="https://user-images.githubusercontent.com/37544189/110206600-fc5f1180-7e7e-11eb-9d4b-b24cb3a853e9.png">
 
The api doesn't provide this precision for every location (they don't for mine), so whether I keep it rounded for everyone on celsius or make it optional is still up in the air, we'll see, as we may change api soonish anyway ! Same goes for the other values optionality.

**Comment by nicacy** [comment] 2021-03-07 09:36
> Yes per what I wrote above @nicacy, this is still very much a WIP and only looks correct around default font size. It's always been a problem to a degree as symbols were always fixed size, while the font size was not. Proportionate scaling of symbols to your font setting (so everything looks "right" and can be scaled any way) is coming.

Thanks, @glouel. No layout issues with the previous Yahoo! weather display, it's just since the additional info was added that it's all gone a bit crowded. Symbols are inessential since I can look out of the window for the same information. I'm only interested in the current temperature.

> Decimal is not classic for forecast but fairly common on current observations, my Netatmo gives me 1 decimal for example :
> 
> The api doesn't provide this precision for every location (they don't for mine), so whether I keep it rounded for everyone on celsius or make it optional is still up in the air, we'll see, as we may change api soonish anyway ! Same goes for the other values optionality.

I'm sure those running their own weather station are very interested in such precision, more so in locations where single-digit or freezing temperatures are the norm. None of the weather apps or services I regularly use include decimals in their current observations or forecasts, and it isn't expected. Here in Cyprus, tenths of a degree are irrelevant when we have 35-50˚C during the summer months.

And of course, per my earlier screenshot, it seems that if the decimals and real feel were not there right now, the current temperature display would not be cut off 😉.

**Comment by glouel** [comment] 2021-03-07 12:30
@nicacy again, either keep beta 3 and switch weather font size to 40px, or revert to release/wait for beta 4.

**Comment by nicacy** [comment] 2021-03-10 13:44
> @nicacy again, either keep beta 3 and switch weather font size to 40px, or revert to release/wait for beta 4.

No problem, we're using 40px for the time being. Turns out, the decimal readouts are quite amusing, and we just have to walk over to the TV to read them 😀.

**Comment by glouel** [comment] 2021-03-10 18:17
@nicacy still work in progress but the scaling now works as intended : 

![Capture d’écran 2021-03-10 à 19 14 59](https://user-images.githubusercontent.com/37544189/110677238-3577e880-81d5-11eb-8e2c-caff14bfa0c8.jpg)

Beta is still not ready as I'm still working on adding those new color variants of the flat icons. Maybe tomorrow.

**Comment by r8ders2k** [comment] 2021-03-10 19:01
@glouel Looks good!

**Comment by nicacy** [comment] 2021-03-11 14:10
> @nicacy still work in progress but the scaling now works as intended :
> 
> Beta is still not ready as I'm still working on adding those new color variants of the flat icons. Maybe tomorrow.

Looking very good, @glouel!

**Comment by glouel** [comment] 2021-03-11 17:09
Beta4 is up, things will now scale correctly based on the font size you select. 

<img width="526" alt="Capture d’écran 2021-03-11 à 18 07 42" src="https://user-images.githubusercontent.com/37544189/110825775-b0540880-8294-11eb-9816-b56664515a76.png">

If you want to use the new color icons, you'll need to pick them here. They require Big Sur. Rendering of the icons on Big Sur, whether monochrome or color is now using the native version of SF Symbols which gives a much higher quality at higher resolution. The icons are slightly thicker, though I could change that in a further beta.

**Comment by Pcar17** [comment] 2021-03-11 17:35
> Beta4 is up, things will now scale correctly based on the font size you select.

Hi @glouel, great update! It's working great & looking fantastic on an M1 MBA running the latest 11.3 Beta (20E5196f).

![IMG_1661](https://user-images.githubusercontent.com/44177062/110829420-b67ac280-825d-11eb-9094-081b8324ff4d.jpeg)

**Comment by glouel** [comment] 2021-03-18 16:08
@Pcar17 great and yep for companion, I reaaaally need to release that as a stable version, I need to finish adding auto updates there but haven't got time yet. 

Massive good news though, openweather approved my application for Aerial, so we get access to their good API for forecasts and more data. I'll try to work on that tomorrow, will update when I get a beta working with the new api and the various new display modes I'll be adding.

**Comment by Pcar17** [comment] 2021-03-18 16:37
> @Pcar17 great and yep for companion, I reaaaally need to release that as a stable version, I need to finish adding auto updates there but haven't got time yet.
> 
> Massive good news though, openweather approved my application for Aerial, so we get access to their good API for forecasts and more data. I'll try to work on that tomorrow, will update when I get a beta working with the new api and the various new display modes I'll be adding.

Hi @glouel, excellent news about being able to use the Open Weather data. It's working great! You did a great job with this and got it done quickly!  "RIP Yahoo Weather!" 😀

**Comment by Pcar17** [comment] 2021-03-19 14:57
Hi @glouel, with me being the author of this issue, am I responsible to close it out? 

It would seem to me that now that you have made the conversion to Open Weather that it can be closed once you release it into production? Or will you decide when to close and handle the formal close out of this thread?

**Comment by glouel** [comment] 2021-03-19 15:23
Yeah sorry I ended up hijacking the thread a bit ;) It's really up to you, I can open a new one for Open Weather if you'd rather, or we just keep this one up. 

I'll close it down when I release the stable version in any case, no worries :)

**Comment by Pcar17** [comment] 2021-03-19 16:02
I say let's use this thread until you release a stable version.  I think the data from Open Weather seems to be spot on.

**Comment by glouel** [comment] 2021-04-21 17:36
Been a while but just to let everyone know, beta5 is out and includes new forecast options for weather using the new API : 

![Capture d’écran 2021-04-21 à 19 32 32](https://user-images.githubusercontent.com/37544189/115596671-a8967380-a2d8-11eb-8d91-8c560a739790.jpg)

Forecast for the next 6 hours : 
![Capture d’écran 2021-04-21 à 19 33 36](https://user-images.githubusercontent.com/37544189/115596695-b0561800-a2d8-11eb-9242-3632a0ddc832.jpg)

Forecast for the next 3 days : 
![Capture d’écran 2021-04-21 à 19 34 09](https://user-images.githubusercontent.com/37544189/115596770-c8c63280-a2d8-11eb-942d-078df40ebed6.jpg)

Forecast for the next 7 days : 
![Capture d’écran 2021-04-21 à 19 34 35](https://user-images.githubusercontent.com/37544189/115596792-cebc1380-a2d8-11eb-9921-1c7f5edca549.jpg)

Things should be translated in your locale languages (except the legend column on the right that's in english for the time being), and you can play with the font size in the settings to make the whole thing larger or more compact.

**Comment by Pcar17** [comment] 2021-04-21 18:22
Hi @glouel,
Great work on this! The new weather functionality is really nice. It’s running fine for me on yesterday’s macOS 11.3 RC! 😎👌🏻

P.S. Apple just released the first 11.4 macOS beta! 😜

**Comment by glouel** [comment] 2021-04-21 18:23
Good to hear everything is working fine ! 

> P.S. Apple just released the first 11.4 macOS beta! 😜

I just upgraded and things look ok so far, at least Aerial works :)

**Comment by Pcar17** [comment] 2021-04-21 21:13
_Off-topic!_ 

"Screensaver" tip of the day....I had to post this! 

🖥🖥🖥🖥🖥

https://9to5mac.com/2021/04/21/hands-on-apples-new-hello-screen-saver-for-m1-macs-running-macos-11-3-video/

**Comment by glouel** [comment] 2021-04-22 11:52
Yeah it was a bit of a shock to see them release... a screensaver of all things ! Considering how dated the bundled ones are, it's certainly intriguing to think if it's a one off or if they just might refresh more. They did rewrite some of their old ones in Swift I believe using the new `.appex` API in Big Sur, but most are still using the old API. I'm wondering if they will transition them all or not. 

I'm still hoping that we'll get the new screen saver API (that this screensaver likely uses) in june at WWDC... 🤞

**Comment by Pcar17** [comment] 2021-04-22 15:20
> Yeah it was a bit of a shock to see them release... a screensaver of all things ! Considering how dated the bundled ones are, it's certainly intriguing to think if it's a one off or if they just might refresh more. They did rewrite some of their old ones in Swift I believe using the new `.appex` API in Big Sur, but most are still using the old API. I'm wondering if they will transition them all or not.
> 
> I'm still hoping that we'll get the new screen saver API (that this screensaver likely uses) in june at WWDC... 🤞

Hi @glouel, here is an updated "how to" article on enabling their new screensaver: 

https://www.macrumors.com/2021/04/21/hello-screen-saver-macos-big-sur-11-3/

**Comment by glouel** [comment] 2021-04-22 18:25
@Pcar17 I'm completely shocked to see they made a .saver and not a .appex... Maybe I shouldn't hope too much for WWDC, that was a surprise.

In any case, closing this as 2.3.0 with the new weather API is finally out ;)

**Closed by glouel** 2021-04-22 18:25 UTC
Labels: external api, information

**Comment by Pcar17** [comment] 2021-04-22 18:28
> In any case, closing this as 2.3.0 with the new weather API is finally out ;)

I have v2.3.0 and it's working great. 

Thx! 👌
