### ISSUE TITLE
Add location name to screen

### ISSUE THREAD

**Issue by Jason-Fitzpatrick** [JohnCoates/Aerial#322] opened 2017-02-17 15:17 UTC
Hi John,

First, I love this screen saver for my Mac, it catches everyones' eye and I pass it on to them. It would be cool to see the name, in some nondistractive way, of the location on the screen when the screen saver is on. So when viewing a screen from China it would display "China" in one of the corners either the entire time or just for several seconds once it starts.

Thanks for creating this package!

Cheers,
Jason

**Comment by alistairmcmillan** [comment] 2017-02-20 08:27
Closing as duplicate of #58 .

There is a potential implementation waiting to be merged.  PR #285

**Closed by alistairmcmillan** 2017-02-20 08:27 UTC
