### ISSUE TITLE
Mirroring in spanning mode

### ISSUE THREAD

**Issue by Kamik423** [JohnCoates/Aerial#819] opened 2019-06-24 18:16 UTC
Sometimes the screensaver (though set to span) instead mirrors to the second display.

<img width="698" alt="Screen Shot 2019-06-24 at 20 14 37" src="https://user-images.githubusercontent.com/16278233/60041892-b79c4280-96bc-11e9-9a66-57e2ffa74ef3.png">
<img width="698" alt="Screen Shot 2019-06-24 at 20 14 39" src="https://user-images.githubusercontent.com/16278233/60041893-b79c4280-96bc-11e9-9b5d-f295a50e4d79.png">
<img width="780" alt="Screen Shot 2019-06-24 at 20 15 13" src="https://user-images.githubusercontent.com/16278233/60041922-c71b8b80-96bc-11e9-8366-68a06290cba1.png">
<img width="780" alt="Screen Shot 2019-06-24 at 20 15 42" src="https://user-images.githubusercontent.com/16278233/60041963-d995c500-96bc-11e9-8f52-be4195d28d50.png">

**Comment by glouel** [comment] 2019-06-24 18:18
Hi @Kamik423 

A debug log with the time where you see this happen would be super helpful. Can you give me that ? Thanks !

**Comment by glouel** [comment] 2019-06-24 18:21
Also, there was a bug with display detection and spanned mode which may just be your issue, it's fixed in latest betas. I'd suggest you try this one:
https://github.com/JohnCoates/Aerial/releases/download/v1.5.1beta4/Aerial.saver.zip

**Comment by Kamik423** [comment] 2019-06-24 18:22
Ok. The latest beta had a warning for non-catalina users, so I was careful with that. I'll try it out. Thanks!

**Comment by glouel** [comment] 2019-06-24 18:23
Yep that's why I picked beta4, it should be safe for you, I highly suggest you avoid 5 and (coming in a minute) 6 for now on!

**Comment by Kamik423** [comment] 2019-06-24 18:25
ok. I cannot currently cause the issue to occur by calling the screensaver again and again. Maybe it only gets corrupted after runnings some while. I have logging enabled and will post if it happens again.

**Comment by glouel** [comment] 2019-06-24 18:28
No worries. Let me know if that happen!

**Comment by crampus** [comment] 2019-06-26 11:11
If it helps, I was encountering a similar-sounding issue on a late 2018 MBP 15" connected to an external display via HDMI.

`macOS 10.15 Catalina public beta 3 (19A487m)`

I can't recall if I checked every mode, but I have a feeling I did, and each time the screensaver started - both on clicking Preview from Preferences and letting screensaver start after timeout, it would only display on the external monitor, never on the Internal screen; and would not engage spanning mode.

Logs showed correct multi-monitor detection. I do not have any custom videos added, so that explains a warning for a missing `customvideos.json`, however I am unsure of the purpose of `TVIdleScreenStrings.bundle`.

[aerial-log.txt](https://github.com/JohnCoates/Aerial/files/3329685/aerial-log.txt) is a log for a run which rendered only on the secondary screen ( id 458669855), beginning at Display Detection, and ending at the successful completion of playing the second video file.

To my untrained eye, I can't see any particular error messages that might relate to this specific issue under Catalina - if it's the same root cause I do not know.

**Comment by glouel** [comment] 2019-06-26 11:32
Hi @crampus !

> `macOS 10.15 Catalina public beta 3 (19A487m)`

Ha !

> it would only display on the external monitor, never on the Internal screen; and would not engage spanning mode.

So, this is actually a Catalina bug with all 3rd party screensavers, including Aerial. They only work on the (last?) monitor in a multi monitor setup. I reported this to Apple and waiting for a fix. 

> however I am unsure of the purpose of `TVIdleScreenStrings.bundle`.

This was a bug in beta6 (this is some of the text stuff displayed on screen, that was missing in that version). This is fixed in beta7.  

> To my untrained eye, I can't see any particular error messages that might relate to this specific issue under Catalina - and honestly I don't even know if it's the same root cause...

Yeah this is a different issue. I would highly suggest you have a look to the Catalina thread (read the top post) to see the various issues related to Catalina ! Check it out here (includes link to beta7 which you should upgrade to, expect a few more betas as we're working around bugs with Catalina !) : https://github.com/JohnCoates/Aerial/issues/801#issue-451690608

**Comment by crampus** [comment] 2019-06-26 11:42
Thanks @glouel, extra brave, this is my daily driver and I use it for work every day as a support tech 😅
I have been keeping an eye on the main post, but didn't dive in too deep to see what else is hidden in there. Figured I'd see if I could be helpful with this one at least.

I rarely use external monitors (All the monitors that look nice next to MBP Retina are too expensive and don't come with stands... 😬)

**Comment by glouel** [comment] 2019-06-26 11:44
> Thanks @glouel, extra brave, this is my daily driver and I use it for work every day as a support tech 😅

Indeed ! Hopefully next beta will fix the multi monitor issue !

> I rarely use external monitors (All the monitors that look nice next to MBP Retina are too expensive and don't come with stands... 😬)

🤣

**Comment by glouel** [comment] 2019-07-07 10:18
Closing this, reopen if you have an issue again but pretty sure it's fixed.

**Closed by glouel** 2019-07-07 10:18 UTC

**Comment by Kamik423** [comment] 2019-07-16 10:59
Just chiming in to let you know that this has not happened again on my machine either.
