### ISSUE TITLE
Feature Request: Popup on unsupported/buggy OS detected

### ISSUE THREAD

**Issue by dVIAN13** [JohnCoates/Aerial#615] opened 2018-10-31 20:08 UTC
@glouel wanted to know yours/community thoughts on adding a pop-up or some kind of notification for OS versions that are either not supported or partially supported? 

This could be during installation or when they launch the options? I think this would cut down on new issues being created, especially when someone doesn't read the readme or issues list and makes a new post? just a suggestion. verbiage could point them to the standalone app to configure?

**Comment by glouel** [comment] 2018-10-31 20:16
Pretty good idea especially with the new AerialConfig.app I introduced in 1.4.5 beta2 ! 

I can't do it at installation (I can't do anything at installation !) but I can at first launch indeed ! Thanks for the idea !

**Comment by glouel** [comment] 2018-10-31 20:47
@dVIAN13 I thought I could simply pop a dialog box but those don't really exist on macos, we are already the equivalent of a dialog box (a modal sheet). So right now, maybe adding an extra tab to the panel on those older versions of macOS with a checkbox "I understand" and until you checked that, when you open preferences it will show that pane ? 

Maybe it's a bit forceful but I was very reluctant to do the AerialConfig.app thing because I knew most people won't read instructions correctly anyway (we had 2 "done" button issues in 2 days after all !)

**Comment by dVIAN13** [comment] 2018-10-31 21:05
@glouel thanks! I see the issues come in too and yeah, I completely agree.. I like the checkbox on a tab.. are you able to dynamically add a tab based on OS version? I don't think the tab with agreeable terms should be the default for users on a supported version.

**Comment by glouel** [comment] 2018-10-31 21:16
@dVIAN13 yep that's the goal, only show to people on < mojave, and only until they click the checkbox (I won't show it on upgrade, etc). I think I'll add a direct link to the config app download in the Advanced tab too. 

I'll remove the tab for mojave and once they click. Here's what I got so far : 

<img width="743" alt="capture d ecran 2018-10-31 a 22 12 53" src="https://user-images.githubusercontent.com/37544189/47819315-666cc680-dd5a-11e8-9ec5-04a98749663f.png">

(obviously it won't show on mojave but that's where I made the mockup ;)) Maybe you or @SeanMSmith has opinion about the text ?

**Comment by dVIAN13** [comment] 2018-10-31 21:22
@glouel I like the text, but I would defer to @SeanMSmith to validate it. :) or if someone else wants to offer suggestions.

Again, great work, and SUPER fast turn around. We all appreciate the continued work to improve this project.

**Comment by glouel** [comment] 2018-10-31 21:28
Is the build not signed ? I was pretty sure I did ?

**Comment by dVIAN13** [comment] 2018-10-31 21:29
when I tried to open app, it had the right-click and open

**Comment by glouel** [comment] 2018-10-31 21:40
I can confirm redownloading the app. Weird thing is, it shows as signed ! I'll look into it tommorrow, must be something I missed regarding signing, maybe needs an entitlement or something, bah !

**Comment by dVIAN13** [comment] 2018-10-31 22:01
no worries! thanks.

**Comment by esetnik** [comment] 2018-11-01 01:44
Is there no way to make it possible to type into textfields inside a screensaver preference pane on HS? If a particular feature only works on Mojave I'd suggest purely disabling the feature (with a notice) instead of having the user download a separate configuration app. Especially since it's only affecting the custom coordinates feature (which is relatively niche) and not core functionality.

**Comment by glouel** [comment] 2018-11-01 12:15
Closing this as I have another workaround coming.

**Closed by glouel** 2018-11-01 12:15 UTC
Labels: enhancement
