### ISSUE TITLE
Aerial screen saver not working on El Capitan

### ISSUE THREAD

**Issue by thefferon** [JohnCoates/Aerial#291] opened 2016-12-28 13:13 UTC
I installed the Aerial screensaver on my iMac running El Capitan by following the instructions at https://github.com/JohnCoates/Aerial. Upon activation, the screensaver displays the message, "You cannot use the Aerial screen saver with this version of OS X. Please contact the vendor to get a newer version of the screen saver."

Any advice?

Thanks

**Comment by alistairmcmillan** [comment] 2016-12-28 13:14
It's a bug in OSX/macOS.

The screensaver itself should launch and run okay.

The bug should just affect the preview in System Preferences. If you select Aerial, close System Preferences, then re-open System Preferences, you should find that the preview works okay.

Closing as a duplicate of #269 .

**Closed by alistairmcmillan** 2016-12-28 13:14 UTC

**Comment by thefferon** [comment] 2016-12-28 13:35
Bingo. Thank you!

On Dec 28, 2016, at 8:14 AM, Alistair McMillan <notifications@github.com<mailto:notifications@github.com>> wrote:


It's a bug in OSX/macOS.

The screensaver itself should launch and run okay.

The bug should just affect the preview in System Preferences. If you select Aerial, close System Preferences, then re-open System Preferences, you should find that the preview works okay.

Closing as a duplicate of #269<https://github.com/JohnCoates/Aerial/issues/269> .
