### ISSUE TITLE
High Sierra - the screen saver is not working 

### ISSUE THREAD

**Issue by macguru341** [JohnCoates/Aerial#381] opened 2017-09-20 06:22 UTC
hello
I have an 2017 Macbook pro 15 and I have install the Aerial.
I just want to report that it's not working - I can't preview the screen saver and it's not loading 

is there any fix ?

**Comment by iamsankalp** [comment] 2017-09-20 07:01
I have the same issue. It doesn't seem to work on High Sierra - I'm on GM build.

When screensaver should initiate there is a scary flicker. Have attached the image for the same.

![img_7484](https://user-images.githubusercontent.com/1756637/30630729-67ffb156-9dff-11e7-88a7-59001cd76624.JPG)

**Comment by alistairmcmillan** [comment] 2017-09-21 07:28
Duplicate of #377

**Closed by alistairmcmillan** 2017-09-21 07:28 UTC

**Comment by gb2220206** [comment] 2018-02-03 05:42
Hey guys,

Go to Energy Saver. Next, do boost your Computer Sleep or Display Sleep longer than 15 minutes. The higher you raise it. The less chance your Mac can tolerate the file. It worked for me :)

Good-Luck,
Giorgio
