### ISSUE TITLE
Impossible to enable overlay display for  Weather, date, ... with 3.1.0 version

### ISSUE THREAD

**Issue by RemyLeroy** [JohnCoates/Aerial#1256] opened 2022-08-19 07:03 UTC
Since the update 3.1.0, the overlay display doesn't work anymore for weather, date, message, countdown, Timer. 
Impossible to check the "Enable" box in overlays settings.

- [ ] Mac model: iMac 5K late 2015
- [ ] macOS version: macOS X 10.14.6
- [ ] Monitor setup:

**Comment by glouel** [comment] 2022-08-19 12:18
Hmmm. Can you make me a screenshot of what you get in 10.14.6 ?

Things work fine here in Ventura so I'm wondering what's happening on that OS.

**Comment by RemyLeroy** [comment] 2022-08-19 12:25
On the attached screenshot, impossible to tick the checkbox « Enable » 

Remy LEROY

**Comment by glouel** [comment] 2022-08-19 12:43
I see, the oldest macOS installation I have is Catalina right now and I can't seem to reproduce, so this must be specific to 10.14.x and possibly older.

If you are using Aerial Companion, does it also not let you click the enable checkbox when opening desktop settings from there ?

**Comment by RemyLeroy** [comment] 2022-08-19 14:08
Yes, I do use Aerial Companion and I generally open Aerial screensaver settings from Aerial Companion. But I can't tick the "enable" checkbox whether I open the settings from System Preferences or via Aerial Companion...

Rémy Leroy
***@***.***

**Comment by glouel** [comment] 2022-08-19 14:13
Just to be clear, I'm asking whether you still have the issue when opening using those precise buttons (not the crossed one) :

<img width="456" alt="Capture d’écran 2022-08-19 à 16 09 27" src="https://user-images.githubusercontent.com/37544189/185637275-2e69c792-799a-44bc-bf79-8bb3d6cc4919.png">
 
When you do, Companions opens Aerial settings in a Window like this : 

<img width="1144" alt="Capture d’écran 2022-08-19 à 16 10 58" src="https://user-images.githubusercontent.com/37544189/185637391-bcf87d30-ce40-4676-9eae-7c502824114b.png">

This usually avoids a lot of the weirdness with screensavers on old versions of macOS. Can you confirm that in this precise way of opening the settings, you still can't click the enable checkbox ? Can you click other checkboxes (for example in Advanced ?).

**Comment by RemyLeroy** [comment] 2022-08-19 14:21
I don't have this version of Aerial Companion... but Aerial Companion v 1.1
Here is the way it appears on my Mac:
<img width="324" alt="Capture d’écran 2022-08-19 à 16 19 57" src="https://user-images.githubusercontent.com/111560744/185639300-5e2e49ce-4639-44f5-9f17-e60a78f60ae8.png">

**Comment by glouel** [comment] 2022-08-19 14:23
At the bottom, under Companion, click "Experimental" then "Launch Aerial Settings", this will give you the window in question.

**Comment by RemyLeroy** [comment] 2022-08-19 14:26
I can't access anything in "Experimental" (still under development)... ☹

<img width="500" alt="Capture d’écran 2022-08-19 à 16 25 18" src="https://user-images.githubusercontent.com/111560744/185640266-3013240c-ad6d-4389-908b-6aacbdbb885c.png">
️

**Comment by glouel** [comment] 2022-08-19 14:28
Just grab the latest beta here, this will save us much time : https://github.com/AerialScreensaver/AerialCompanion/releases/download/v1.4.0beta2/Aerial.Companion.app.zip

**Comment by RemyLeroy** [comment] 2022-08-19 14:33
Aerial Companion 1.4b installed
I clicked on the button indicated by the arrow

<img width="411" alt="Capture d’écran 2022-08-19 à 16 29 51" src="https://user-images.githubusercontent.com/111560744/185641635-80d441a9-b40e-4599-98e2-2cb1d971d808.png">

It opens the settings in a window but I have the same issue. I can't enable the Weather overlay (by example)

<img width="1142" alt="Capture d’écran 2022-08-19 à 16 32 39" src="https://user-images.githubusercontent.com/111560744/185642005-03820b08-2feb-4b25-9333-54294eb33197.png">

.

**Comment by glouel** [comment] 2022-08-19 14:37
Understood, just to triple check my understanding, the Enable I circled below is not working. Correct ?

What about the "Wind" one I circled below too, does that checkbox work or not ? 

<img width="1142" alt="185642005-03820b08-2feb-4b25-9333-54294eb33197" src="https://user-images.githubusercontent.com/37544189/185642907-125f0bb5-ff3f-4483-99ea-d59cd5ce87bc.png">

**Comment by RemyLeroy** [comment] 2022-08-19 14:42
I can change the checkbox circled in green.
I can't change the one circled in red.

<img width="1142" alt="Capture d’écran 2022-08-19 à 16 32 39" src="https://user-images.githubusercontent.com/111560744/185644042-f2843d2d-74d8-48ca-b118-eece8ac3b387.png">

**Comment by glouel** [comment] 2022-08-19 14:46
Thanks !

To be 100% clear, clicking on the left column never changed the enabled status. But the Enabled box on top that you circled in red should indeed work. 

I'll try to find a way to install 10.14 somewhere to check but this might be an issue with the latest versions of Xcode. I'll keep you posted.

**Comment by RemyLeroy** [comment] 2022-08-19 14:48
Thanks a lot.
In the meantime I will reinstall the previous version of Aerial screensaver that I will exhume from my Time Machine backup. It was working just fine.

**Comment by glouel** [comment] 2022-08-19 18:04
(quick update, I reproduced the issue, there seems to be an issue saving preferences for all the overlays, I have no idea why, but I'll keep investigating)

**Comment by RemyLeroy** [comment] 2022-08-19 18:09
Thanks for the update. 
I've reinstalled the previous version (3.0.9) and it works fine.

**Comment by NDjot** [comment] 2022-08-28 12:38
Thanks for providing an absolute amazing piece of software. Much appreciated.

Just wanted to mention, that I am experiencing the exact same problem as described above, with identical versions of macOS, Aerial Companion and Aerial Screensaver. 

Hope this gets fixed in future updates, since I need to stay on my version of the macOS due to compatibility with other software. For now, I'll revert to an older version of Aerial, since the issue appears to have been introduced with version 3.1.0.

BR from Denmark
Martin

**Comment by glouel** [comment] 2022-08-29 16:58
I believe I have a rough idea where the bug is, the good news is, I can reproduce it on my main Mac, so I should be able to fix it. I'll keep you posted, it's very likely a completely stupid bug. Stay tuned !

**Comment by glouel** [comment] 2022-08-29 17:12
Ok, again, sorry everyone, it was an absurdly stupid bug, I finally found it. I'm 99.999% this is fixed in 3.1.2 : https://github.com/JohnCoates/Aerial/releases/download/v3.1.2/Aerial.saver.zip

It should be available in Companion in a few minutes too. @RemyLeroy @NDjot @hairguitar let me know if that works for all of you.

**Comment by RemyLeroy** [comment] 2022-08-29 17:16
Yes! Yes! Yes!
it works!!!

infinite thanks for your work and the quick fix of this annoying bug on our old Mac 😊

**Comment by glouel** [comment] 2022-08-29 17:18
Awesome, thanks for confirming, and sorry it took me 10 days to figure it out ! Take care.

**Closed by glouel** 2022-08-29 17:18 UTC
Labels: fix inside

**Comment by RemyLeroy** [comment] 2022-08-29 17:22
Don't apologise !
10 days is real quick, I'm sure you have a lot other things to do than taking care of old Macs using a version of macOS X that isn't maintained anymore by Apple.

I really appreciate the way you've taken care of my bug report, reinstalled Mojave on a Mac to reproduce the bug and finally fix it.

**Comment by NDjot** [comment] 2022-08-30 06:55
Hi,

Just updated to 3.1.2. Bug is gone. Thanks a million. Much appreciated.

BR from Denmark
Martin

Den 29. aug. 2022 kl. 19.12 skrev Guillaume Louel ***@***.******@***.***>>:



Ok, again, sorry everyone, it was an absurdly stupid bug, I finally found it. I'm 99.999% this is fixed in 3.1.2 : https://github.com/JohnCoates/Aerial/releases/download/v3.1.2/Aerial.saver.zip

It should be available in Companion in a few minutes too. @RemyLeroy<https://github.com/RemyLeroy> @NDjot<https://github.com/NDjot> @hairguitar<https://github.com/hairguitar> let me know if that works for all of you.

**Comment by hairguitar** [comment] 2022-08-30 12:22
@glouel all good here. Thanks for the quick fix!
