### ISSUE TITLE
Aerial doesn't respect the Energy Saver settings

### ISSUE THREAD

**Issue by IndigoHomme** [JohnCoates/Aerial#131] opened 2015-11-03 14:00 UTC
Energy Saver settings on screen sleep and computer sleep are ignored.

**Comment by dcoeurjo** [comment] 2015-11-03 15:55
dup #129

**Comment by dcoeurjo** [comment] 2015-11-03 15:56
see #23

**Comment by alistairmcmillan** [comment] 2015-11-03 16:12
@IndigoHomme Which version are you running? Beta 4 should fix this issue.

https://github.com/JohnCoates/Aerial/releases

**Comment by alistairmcmillan** [comment] 2016-01-28 21:14
Closing as duplicate of #23

**Closed by alistairmcmillan** 2016-01-28 21:14 UTC
Labels: duplicate
