### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by bullieszus** [JohnCoates/Aerial#461] opened 2018-05-31 13:48 UTC

**Comment by bullieszus** [comment] 2018-05-31 13:49
Have an option to display the name of what is being showned.

**Comment by MarcelloNicoletti** [comment] 2018-06-04 19:28
@bullieszus Turns out you predicted an Apple Aerial feature. (I do want this in this copy of Aerial as well)

**Comment by alistairmcmillan** [comment] 2018-07-31 12:55
Closing as duplicate of #58

**Closed by alistairmcmillan** 2018-07-31 12:55 UTC
