### ISSUE TITLE
[feature] Scene title/location

### ISSUE THREAD

**Issue by alex-mohemian** [JohnCoates/Aerial#451] opened 2018-04-16 10:24 UTC
The Android [Aerial Dream](https://play.google.com/store/apps/details?id=com.codingbuffalo.aerialdream&hl=en) app has a feature that shows the title and (exact) location of the video (e.g. `LAX airport, Los Angeles, USA`) in the lower left corner as an overlay.

Would be a beautiful addition.

**Comment by alistairmcmillan** [comment] 2018-07-31 12:58
Closing as duplicate of #58

**Closed by alistairmcmillan** 2018-07-31 12:58 UTC
