### ISSUE TITLE
Screen Saver preference pane broken

### ISSUE THREAD

**Issue by bananakid** [JohnCoates/Aerial#211] opened 2016-02-06 09:35 UTC
I'm running OS X El Capitan 10.11.1 (fresh clean installation) on a 15-inch MacBook Pro with Retina display. Everything was fine with Screen Saver preference pane:
<img width="669" alt="screen shot 1" src="https://cloud.githubusercontent.com/assets/17095595/12865925/cb26fefa-ccdd-11e5-9050-200d28692ddf.png">

I've installed Aerial 1.1 and my Screen Saver preference pane got broken:
• now it has just 1 column in screen saver chooser menu
• screen saver preview area is different size
• there're some weird gaps and borders in preview area
<img width="669" alt="screen shot 3" src="https://cloud.githubusercontent.com/assets/17095595/12865927/cb5d9ff0-ccdd-11e5-8c45-ec41ee7bb373.png">

I've tried removing Aerial 1.1 – no luck, also installing Aerial 1.2β5 didn't help. Selecting any different screen saver and relaunching System Preferences, restarting Mac, changing screen resolution, deleting
~/Library/Preferences/ByHost/com.JohnCoates.Aerial.C21F8FF2-745D-5278-B4A1-89E73D0866EC.plist
~/Library/Preferences/ByHost/com.apple.screensaver.C21F8FF2-745D-5278-B4A1-89E73D0866EC.plist
didn't help.
<img width="669" alt="screen shot 2" src="https://cloud.githubusercontent.com/assets/17095595/12865926/cb5afd22-ccdd-11e5-9910-f9af8faaee97.png">

Another thing to note: when I open screen saver preference pane I get a normal 1-2 column look for like half a second. Then it switches to 1-column and preview area grows a little.

Please help me get it back to normal. I just got all my stuff back together after a huge migration so I really don't want to create a new user or do a clean OS X installation. I can provide any logs

**Comment by JohnCoates** [comment] 2016-02-06 17:35
Looks like it prompted a bug in the OS X Preferences panel by chance. I'm not able to reproduce it, and after Aerial has been uninstalled it has no possible effect on that panel. 

Sorry that your screen savers are in a single column, but do you think that would warrant a clean OS X installation?

**Comment by alistairmcmillan** [comment] 2016-02-06 17:54
I have seen this bug on one of my Macs. Same thing. Normal layout for a second and then it pops into a single column. Not sure how I triggered it and it has since gone away.

Nothing to do with Aerial IMHO. :)

I really would recommend again doing a reinstall to try to fix this. Chances are this layout error will go away all by itself.

**Comment by bananakid** [comment] 2016-02-07 06:40
Thanks for responding. I've found [another report](https://discussions.apple.com/thread/7038374?start=0&tstart=0) on the the same issue so it appears to be a System Preferences bug indeed. I'd better Google more or ask at MacRumors if anyone has a fix.

**Comment by alistairmcmillan** [comment] 2016-02-16 20:50
Closing as problem is a bug in System Preferences rather than Aerial.

**Closed by alistairmcmillan** 2016-02-16 20:50 UTC
