### ISSUE TITLE
Flickering issues in High Sierra v10.13

### ISSUE THREAD

**Issue by JonRobinsonLush** [JohnCoates/Aerial#403] opened 2017-10-18 13:20 UTC
Not sure if it's related to your screen saver, but i'm getting very odd flickering/juddering of the images

Steps..
Screen saver already installed working perfectly on Sierra
Upgrade to High Sierra v10.13
View the screen saver
Screen flickering on all images

**Comment by alistairmcmillan** [comment] 2017-10-18 13:23
This is a duplicate of #377 

For the moment as a workaround you can check the option to display the time with the screensaver. It should play without the flickering then.

**Closed by alistairmcmillan** 2017-10-18 13:23 UTC

**Comment by JonRobinsonLush** [comment] 2017-10-18 14:24
Ah thanks... sorry I missed the original
