### ISSUE TITLE
Aerial never randomizes videos

### ISSUE THREAD

**Issue by florianbohnert** [JohnCoates/Aerial#951] opened 2020-03-19 00:57 UTC
#### General troubleshooting tips

Before logging an issue please check that:
- [YES 1.8.2 Beta] You have the latest version installed (There may be a beta version that fixes your issue), see here for the latest releases and bug fixes: https://github.com/JohnCoates/Aerial/releases
- [I looked] Your issue isn't already mentioned in our [issues](https://github.com/JohnCoates/Aerial/issues). You may find a workaround there or a similar request already made.
- [I looked] Your problem isn't mentioned in the [troubleshooting section](https://github.com/JohnCoates/Aerial#troubleshooting).

If none of this fixes your issue, tell us about the problem you are experiencing or the feature you'd like to request.

#### Required information
In order to help us sort your issue, we ask that you provide the following information:
- [ ] Mac model: MacBook Pro 16 inch, 2019
- [ ] macOS version: Catalina 10.15.3
- [ ] Monitor setup: MacBook Pro internal screen

If appropriate, please enable `Debug mode` and `Log to disk` in `Advanced` tab and replicate your bug, then attach the `AerialLog.txt` file (You can access this file through the Advanced tab).

#### Description of issue / Feature request

{{Recently, Aerial started to only play one video. Although I have downloaded to cache several different videos, when it boots up it always only shows the same one video (Africa from space) and then goes onto the next in the same order every time. It used to randomize the first video played as well as each video afterwards. I'm trying uninstalling and reinstalling several times, I've tried clearing the cache and downloading the videos again. I've looked in options and cannot find any setting for randomizing and I remember it did it automatically before. The order for me is always the same 1. Africa from Space 2. Alamo Square 3. Jellyfish. I've never seen it change for the past 2 weeks or so. Thanks for your help!}}

**Comment by glouel** [comment] 2020-03-19 01:17
Hi !

Please go into advanced tab and disable time synchronization on multiple computers.

**Comment by florianbohnert** [comment] 2020-03-19 03:56
Thank you! I have unchecked the box and will try it now. Will update this thread. Thanks again!!

**Comment by florianbohnert** [comment] 2020-03-19 05:12
That seems to have solved the issue! Thank you very much!!

**Comment by glouel** [comment] 2020-03-19 13:44
No prob ! I'll keep this open just in case someone hits the bug again, I will replace that option soonish with something better, though I have no idea why it started misbehaving all of a sudden... seems to be one more Catalina thing !

**Comment by Kalthax** [comment] 2020-04-22 03:34
This does fix it for me. I just wanted to add this comment because I'm running Mojave right now, so it's probably not a Catalina-specific bug.

**Comment by glouel** [comment] 2020-04-22 12:30
> This does fix it for me. I just wanted to add this comment because I'm running Mojave right now, so it's probably not a Catalina-specific bug.

Hi @ Kalthax !

Thanks for confirming this, looks like I need to have another look at that feature, I'll probably remove it until I get the next version of this working !

**Comment by zcccccc1** [comment] 2020-04-30 02:30
My aerial also had the bug, wonder if i can see a fix in the beta versions

**Comment by glouel** [comment] 2020-04-30 02:38
> My aerial also had the bug, wonder if i can see a fix in the beta versions

No it's not fixed in the current beta, but in your current version just go into Preferences, Advanced tab, and disable "Time synchronization on multiple computers". I will force disable it in next build so that it's fixed for everyone.

**Comment by NiklasBr** [comment] 2020-04-30 08:44
I can confirm that disabling *Time synchronization on multiple computers* returns the random order, but it is not clear __why__ that option has anything to do with the order of the videos. I can understand (from a technical perspective) that perhaps it has something to do with determinism and network latency or other complexity that the randomness is disabled or the fact that they may need a common seed to guarantee ordering...

But from a user perspective it makes no sense why the option to show the same video on two computers causes the video *ordering* to always be the same. I had assumed that it would be random but the same.

**Comment by glouel** [comment] 2020-04-30 12:16
> I can confirm that disabling _Time synchronization on multiple computers_ returns the random order, but it is not clear **why** that option has anything to do with the order of the videos. I can understand (from a technical perspective) that perhaps it has something to do with determinism and network latency or other complexity that the randomness is disabled or the fact that they may need a common seed to guarantee ordering...
> 
> But from a user perspective it makes no sense why the option to show the same video on two computers causes the video _ordering_ to always be the same. I had assumed that it would be random but the same.

Well, it's bugged ? ;) 

This was an experimental feature I implemented a while ago for one user with a pretty specific setup, it uses time to seed the randomizer so that if you start Aerial on two computers around the same time, they'd generate the same random playlist, and would be synced that way. It's disabled by default.

At some point it got broken, so I'll remove it as I'll add a better version of this soonish, more info here : https://github.com/JohnCoates/Aerial/issues/857

**Comment by kindreper** [comment] 2020-05-23 18:39
Thank you, fixed my issue that I have had for months now!  Tried deleting vids then it stayed on the next vid after Africa from space.  Greatly appreciated!

**Comment by zcccccc1** [comment] 2020-05-24 14:07
fixed 😀

**Comment by glouel** [comment] 2020-05-24 14:09
Sorry about all that all, it looks like that bug hit more people than I thought, I didn't think people would manually enable that checkbox (it was quite poorly undocumented). 

FYI I have now removed the time checkbox thing in the latest betas, so this won't be an issue from now on :)

**Comment by glouel** [comment] 2020-05-25 14:16
1.9.0 is out which definitely fixes this issue, so closing this :)

**Closed by glouel** 2020-05-25 14:16 UTC
Labels: fix inside
