### ISSUE TITLE
Aerial 1.4b11 not seeing Dubai Night Two 4K

### ISSUE THREAD

**Issue by SeanMSmith** [JohnCoates/Aerial#523] opened 2018-10-06 02:04 UTC
Aerial 1.4 beta 11 (from [glouel/Aerial](https://github.com/glouel/Aerial))

With preferred video format set to 4K HEVC, Aerial 1.4b11 caches and plays the 1080p H.264 version of Dubai Night Two (http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/comp_DB_D011_D009_SIGNCMP_v15_6Mbps.mov) instead of my already cached 4K HEVC version (https://sylvan.apple.com/Aerials/2x/Videos/DB_D011_C009_4K_SDR_HEVC.mov).

I see that the 4K HEVC version does not currently appear in the .json files for tvOS 10, 11, or 12, but it must have done so at some point, since [esetnik/Aerial](https://github.com/esetnik/Aerial) v1.3 cached it on 11 January 2018.

The 4K HEVC version is still on Apple's servers at the URL above.

Based on a cursory check, this appears to be the only video for which Aerial 1.4b11 plays a 1080p version when I have a 4K version already cached.

(Apologies if I posted this issue in the wrong place, but there seems to be no place to post issues at [glouel/Aerial](https://github.com/glouel/Aerial).)

**Comment by glouel** [comment] 2018-10-06 06:29
Yeah no problem, I just post the test builds there before we merge it here so don't worry. 

Thanks for the report but this is a peculiar one I admit, because the tvos11.json file that you see in cache is the URL that @esetnik was using, which as you pointed no longer include that video. As far as I see, that's the only JSON URL that he used in his builds, unless I missed something.

So maybe Apple removed it at some point from that JSON ? Maybe there are more hidden 4K videos we don't know of in some json somewhere, or no longer linked but still up ? That's the first I hear of the JSON actually changing which is even more peculiar...

**Comment by esetnik** [comment] 2018-10-06 16:08
I can confirm that I wasn't doing anything special with my fork. Apple must have removed it from the JSON.

**Comment by glouel** [comment] 2018-10-06 16:47
Ok thanks ! Maybe we should checksum those jsons as an experiment or something :) 

If it's just one video, I can add a workaround I guess.

**Comment by oliverschmidthypoport** [comment] 2018-10-11 08:29
I'm missing the Downtown LA Video (https://appleinsider.com/articles/17/12/07/apple-puts-4k-aerial-screen-saver-of-los-angeles-skyline-into-rotation-on-apple-tv-4k). It's running on a local appleTV, but it seems to be missing from the json file.

**Comment by glouel** [comment] 2018-10-11 14:46
Closing as fixed in release 1.4

**Closed by glouel** 2018-10-11 14:46 UTC
