### ISSUE TITLE
Energy saving

### ISSUE THREAD

**Issue by akollen** [JohnCoates/Aerial#34] opened 2015-10-27 23:01 UTC
The computer does not go in sleep mode anymore when screensaver is playing .

**Comment by gillesdemey** [comment] 2015-10-27 23:22
+1

**Comment by JohnCoates** [comment] 2015-10-27 23:39
Thanks for creating this issue.
Looks like this is the default with AVPlayer, and it doesn't look like there's a way to implement this normally. Found AVEnableUserIdleDisplaySleep. More research is needed.

**Comment by alistairmcmillan** [comment] 2015-10-27 23:51
Duplicate of issue #32

**Comment by alby128** [comment] 2015-10-28 16:01
There is a possible solution proposed in the first post of issue #23 (duplicate of this one)

**Comment by JohnCoates** [comment] 2015-10-30 10:01
Thanks @alistairmcmillan for linking the original issue. I'm working on fixing this, but the solution I've found is quite complicated and will take a bit to implement.

**Closed by JohnCoates** 2015-10-30 10:01 UTC
Labels: duplicate
