### ISSUE TITLE
Labels cut off

### ISSUE THREAD

**Issue by kc2npu** [JohnCoates/Aerial#467] opened 2018-06-09 15:59 UTC
On High Sierra (10.13.5) running on a MacBook Pro, 15 inc, 2017 - the screen saver options mage has tables and text cut off. It looks like all the Day and Night labels are not being displayed completely.  Only China has no problems with the labels. 

Best, 

<img width="753" alt="screen shot 2018-06-09 at 11 52 15 am" src="https://user-images.githubusercontent.com/40122537/41193604-60e2080a-6bdc-11e8-9576-3c702b00a102.png">
<img width="674" alt="screen shot 2018-06-09 at 11 56 42 am" src="https://user-images.githubusercontent.com/40122537/41193605-60ec630e-6bdc-11e8-8969-e6fb0337de15.png">
<img width="650" alt="screen shot 2018-06-09 at 11 56 52 am" src="https://user-images.githubusercontent.com/40122537/41193606-60f7e846-6bdc-11e8-813b-78a368106ec3.png">
<img width="651" alt="screen shot 2018-06-09 at 11 57 00 am" src="https://user-images.githubusercontent.com/40122537/41193607-6103684c-6bdc-11e8-8fbc-59b9fbb96a81.png">
<img width="657" alt="screen shot 2018-06-09 at 11 57 08 am" src="https://user-images.githubusercontent.com/40122537/41193608-610e997e-6bdc-11e8-9358-321176dc5d5d.png">

**Comment by alistairmcmillan** [comment] 2018-07-31 12:50
Closing as duplicate of #413

**Closed by alistairmcmillan** 2018-07-31 12:50 UTC
