### ISSUE TITLE
Can´t open Screensaver options

### ISSUE THREAD

**Issue by MrGadget1701** [JohnCoates/Aerial#1002] opened 2020-05-28 19:13 UTC
I  can´t open the Aerial screensaver options after installation. Tried to un and install several times. MacOS is on 15.5.5. Tried several restarts. but when clicking on Aerial settings nothings happen... Taskmanager process goes up over 100%. Fan goes up... What can I do?

<img width="276" alt="Bildschirmfoto 2020-05-28 um 21 09 40" src="https://user-images.githubusercontent.com/29458454/83183416-0aca1100-a128-11ea-9bce-662564bc60f9.png">

**Comment by glouel** [comment] 2020-05-28 19:18
Hi @MrGadget1701 

That's a weird one, first time I'm seeing this. What about launching the screensaver from a hotcorner, does it work ? And the little preview above that button that you click to open Aerial's options, does it work too ?

Also, did you upgrade from Mojave or from a previous Catalina version ? Because you may need to upgrade your Aerial version to the latest (1.9.0, see here : https://github.com/JohnCoates/Aerial/releases/tag/v1.9.0)

Assuming it's the latest version, I'd suggest wiping the preferences by moving the file that's at ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist

to somewhere else (but keep it) and try again. This will reset everything to default and if your old preferences were an issue, it should work fine. If it works fine, then please send me (attach to a message here) your non working file so I can have a look.

Thanks !

**Comment by DrMORO617** [comment] 2020-05-28 20:09
I think I had a similar issue when upgrading Aerial to a newer version before. I just cannot click-open the setting options.
What I did was to restart my Mac, and all back to normal usage.
Hope this helps a bit.

**Comment by glouel** [comment] 2020-05-28 20:13
One thing to keep in mind is that before upgrading, you need to make sure you close System Preferences. Usually, closing System Preferences by clicking the red button top left, and reopening it, do the trick. Restarting your mac does the same thing !

**Comment by TechJedi51** [comment] 2020-06-02 23:08
I am seeing the same thing. The options button is greyed out.
![Screen Shot 2020-06-02 at 4 08 37 PM](https://user-images.githubusercontent.com/28914268/83578336-59dac200-a4eb-11ea-8c4e-53575187dbbc.png)

**Comment by glouel** [comment] 2020-06-03 12:01
@TechJedi51, same questions than to the original poster : 

- Did you upgrade, or first time install of Aerial ? 
- Is this on Catalina ? 
- Can you try moving away the ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.{UUID}.plist preference file and see if it helps ?

Let me know and we'll go from there

**Comment by TechJedi51** [comment] 2020-06-03 18:39
Hello,

	Also. I have tried 1.9.0 and the 1.9.1 beta.

	Here are the results:

SEAL Mac mini macOS 10.15.5 scott [/Users/scott]🔸rm ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.71AF7ECF-CA5E-5BFD-BF97-B370CEFA734B.plist 
SEAL Mac mini macOS 10.15.5 scott [/Users/scott]🔸ls ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/                                                                                                            
total 8
drwxr-xr-x  3 scott  staff  -   96B Jun  3 11:35:53 2020 ./
drwx------  7 scott  staff  -  224B Jun  2 16:03:12 2020 ../
-rw-------  1 scott  staff  -  843B Jun  2 16:11:52 2020 oedrommcarrasco.brooklyn.71AF7ECF-CA5E-5BFD-BF97-B370CEFA734B.plist
SEAL Mac mini macOS 10.15.5 scott [/Users/scott]🔸






	Scott Immerman
Tech Jedi
S.E.A.L. Systems
 Certified Support Professional 
15021 Ventura Boulevard
Suite 811
Sherman Oaks, Ca 91403
Voice: 818.888.2775 ex 10
Scheduling: 818.888.2775 ex 20

SEALsystems.net <https://sealsystems.net/>

 <https://www.facebook.com/scottaimmerman>  <https://www.twitter.com/macsupport>  <https://disposablebits.com/>  <https://www.linkedin.com/in/scottimmerman>  <https://instagram.com/macsupport/>  <https://consultants.apple.com/us/505521> 
“Stay hungry,
   stay foolish.”
       —Steve Jobs (1955-2011)

**Comment by glouel** [comment] 2020-06-03 18:43
So I get you deleted the file from your paste, are you saying it didn't work after that ? If you attached a screenshot or something, be aware that you can't attach a screenshot by mail when replying to a github issue.

If it still doesn't work, can  you launch Console.app and look if you find a crash log ? It will probably not be named Aerial, either something "prefPanel" or "ScreenSaverEngine" (maybe "legacyScreenSaver"). Thanks !

**Comment by TechJedi51** [comment] 2020-06-03 19:02
Sorry about the screenshot. Here is a link to it: https://private.sealsystems.net/Aerial-1002.png <https://private.sealsystems.net/Aerial-1002.png>

Nothing in the Crashlogs in Console. The Screensaver runs okay, just can’t click on the options button.





	Scott Immerman
Tech Jedi
S.E.A.L. Systems
 Certified Support Professional 
15021 Ventura Boulevard
Suite 811
Sherman Oaks, Ca 91403
Voice: 818.888.2775 ex 10
Scheduling: 818.888.2775 ex 20

SEALsystems.net <https://sealsystems.net/>

 <https://www.facebook.com/scottaimmerman>  <https://www.twitter.com/macsupport>  <https://disposablebits.com/>  <https://www.linkedin.com/in/scottimmerman>  <https://instagram.com/macsupport/>  <https://consultants.apple.com/us/505521> 
“Stay hungry,
   stay foolish.”
       —Steve Jobs (1955-2011)

**Comment by glouel** [comment] 2020-06-03 19:09
No worries about the screenshot. 

And thanks for confirming the screensaver, by itself, works, it narrows it down a bit. 

So there are two things I can think of. 

The first one is that Aerial crashed during the preview (the tiny preview you see above the button you can't click). If you don't see any crash log, then it's possibly not that. 


The second one is that I noticed that you have another 3rd party screensaver installed. There's a bug in macOS with Swift screensavers that prevents you from switching from one to the other if both aren't compiled with at the very least for Swift 5 (because of ABI stability). 

So just to make it clear I would suggest you do this : 
- Select Aerial in System Preferences
- Fully close System Preferences (by clicking the red button top left). It needs to be fully closed as if you keep it around you'll trigger the bug.
- Reopen System Preferences and go to Desktop & Screen Saver to see if it works (Aerial should still be selected). 

Please let me know if that works.

**Comment by TechJedi51** [comment] 2020-06-03 20:12
**You're a genius.** That was it. Once I removed the other ScreenSaver, it worked. The weather isn't showing (Flat nor Color). But that's a minor issue.

**Comment by glouel** [comment] 2020-06-03 20:21
Glad to hear it worked ! Although it's a bit concerning, usually when you hit that issue, there was a message saying "This screensaver isn't compatible with this version of macOS" or something to the effect. This is the second report I get (possibly with 10.15.5 ?) of a black preview, so they might have changed something (again). I'd be super concerned if you now can't have 2 Swift screensavers installed at the same time :(

I'll have to try Brooklyn (based on the date of the last commit, it's probably not compiled with an ABI stable version of swift), will try to give it a shot tomorrow. 

Regarding weather, is that with "Use current" or by specifying a location ? In doubt, first try specifying a location yourself (use current requires location services to be enabled). What happens when you press the Test button ? I suggest you also enable debug log in the `Advanced` tab if nothing happens, then try the test button and paste me from the log. Thanks !

**Comment by TechJedi51** [comment] 2020-06-03 20:31
Okay, I just tried that and now the Preview is Black. The Settings button is active, but when clicked, nothing displays. And the Screensaver still works when activated. Nothing in the Crash logs. macOS 10.5.5 (19F101).

**Comment by glouel** [comment] 2020-06-03 20:35
Tried what ? The test button I mentioned ? I'm a bit lost here because you had it working a bit earlier.   

Make sure you fully close System Preferences and open it again to "restart" the preference panel, because it stays in memory as long as System Preferences is open (even on another panel).

**Comment by TechJedi51** [comment] 2020-06-03 21:15
Sorry, here is a bit more detail.

1. Quit System Preferences
2. Start System Preferences
3. Select a built-in Saver
4. Quit System Preferences
5. Start System Preferences
6. Select Aerial
7. The Preview is now Black, but the Setting button is active, but doesn't display the Settings Sheet

**Comment by glouel** [comment] 2020-06-03 21:17
But you had it working after removing your other screensaver right ? Did you reinstall it or something ? What changed since then, I'm a bit puzzled. 

It looked like you had launched the panel at least once since you had enabled weather so I'm not sure what happened here. You could try wiping the preferences just in case I guess ?

**Comment by glouel** [comment] 2020-06-03 21:19
Hold on, I completely misread your post. DO NOT select a build in saver. Select Aerial, THEN close with Aerial selected. Reopen and it should work.

**Comment by TechJedi51** [comment] 2020-06-03 21:20
Correct. I just Quit System Preferences and when I re-opened it, the Preview was black.

**Comment by glouel** [comment] 2020-06-03 21:22
Please check my second message above.

**Comment by TechJedi51** [comment] 2020-06-03 21:26
Okay, I'll try it now....

**Comment by TechJedi51** [comment] 2020-06-03 22:32
No luck. I will try a restart later today and see of that solves the issue.

**Comment by glouel** [comment] 2020-06-04 02:24
Ok let me know, consider removing the preference file (the one you rm'd earlier) before restarting system prefernces to see if that helps.

**Comment by TechJedi51** [comment] 2020-06-04 20:49
You were correct again. Deleting the preferences temporarily fixes both the black preview and no settings sheet issues. But If I close or quite System Preferences, and then come back, the issues are present again. (Also no weather displayed and no pop-up window when clicking Test).
![Screen Shot 2020-06-04 at 1 47 18 PM](https://user-images.githubusercontent.com/28914268/83808766-32f6ca00-a66a-11ea-98cd-936ead4c8d60.png)

**Comment by glouel** [comment] 2020-06-04 21:08
@TechJedi51 thanks for following up on this. Looks like I have a bug parsing the preferences back, could be some setting you picked that I don't handle correctly.

Could you attach a preference file that crash ? (just drag'n drop in this editor). This way hopefully I can replicate. According to your screenshot, Aerial did manage to get the location fine so it's more about the Yahoo API call. 

So regarding the Yahoo issue, I'd be interested with the debuglog (in advanced you can enable it, it's a separate debuglog.txt file that's stored in the container, you can open it via that panel). 

With the panel working, go to advanced, enable debug mode and log to disk (and open the location in finder so you can find the file later). Then press the test button in the Info tab > Weather. When that's done, go look at the debuglog.txt file in a text editor and you should see something like : 

```
2020-06-03 22:02:37.972 : === YW: Starting locationMode
2020-06-03 22:02:38.463 : === YW: API callback success
2020-06-03 22:02:38.463 : {"location":{"city":
```
etc

That's the part I'm interested in ;) I'll try to have a look at replicating your issue tomorrow with your file and let you know. Thanks !

**Comment by TechJedi51** [comment] 2020-06-04 21:19
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>LayerBattery</key>
	<string>{
  "corner" : 2,
  "disableWhenFull" : false,
  "displays" : 2,
  "fontName" : "Helvetica Neue Medium",
  "fontSize" : 20,
  "isEnabled" : true,
  "mode" : 1
}</string>
	<key>LayerClock</key>
	<string>{
  "clockFormat" : 0,
  "corner" : 3,
  "displays" : 1,
  "fontName" : "NeonThick",
  "fontSize" : 50,
  "hideAmPm" : false,
  "isEnabled" : true,
  "showSeconds" : true
}</string>
	<key>LayerDate</key>
	<string>{
  "corner" : 4,
  "displays" : 1,
  "fontName" : "HelveticaNeue",
  "fontSize" : 36,
  "format" : 0,
  "isEnabled" : true,
  "withYear" : true
}</string>
	<key>LayerWeather</key>
	<string>{
  "corner" : 1,
  "degree" : 1,
  "displays" : 2,
  "fontName" : "Helvetica Neue Medium",
  "fontSize" : 40,
  "icons" : 0,
  "isEnabled" : true,
  "locationMode" : 0,
  "locationString" : "91344"
}</string>
	<key>SUEnableAutomaticChecks</key>
	<false/>
	<key>SUFeedURL</key>
	<string>https://raw.githubusercontent.com/JohnCoates/Aerial/master/beta-appcast.xml</string>
	<key>SUHasLaunchedBefore</key>
	<true/>
	<key>SULastCheckTime</key>
	<date>2020-06-04T02:58:46Z</date>
	<key>layers</key>
	<string>[
  "message",
  "clock",
  "date",
  "location",
  "battery",
  "weather",
  "countdown",
  "timer"
]</string>
	<key>newViewingMode</key>
	<integer>2</integer>
</dict>
</plist>
`

**Comment by TechJedi51** [comment] 2020-06-04 21:26
Log file: 
2:24:22 PM : avInit .saver (0.0, 0.0, 296.0, 184.0) p: true o: true
2:24:22 PM : <AerialView: 0x7fb37fd0a370> AerialView setup init (V1.9.1beta1) preview: true
2:24:22 PM : Time Management initialized
2:24:22 PM : Display Detection initialized
2:24:22 PM : ***Display Detection***
2:24:22 PM : 2 display(s) detected
2:24:22 PM : 1cm = 37.79527615817928 points
2:24:22 PM : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {72, 72}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1920, 1080}, __C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 188925686, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace]
2:24:22 PM :        bottomLeftFrame (0.0, 0.0, 1920.0, 1080.0)
2:24:22 PM : npass: dict [__C.NSDeviceDescriptionKey(_rawValue: NSScreenNumber): 188914420, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceResolution): NSSize: {72, 72}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceSize): NSSize: {1920, 1080}, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceBitsPerSample): 8, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceIsScreen): YES, __C.NSDeviceDescriptionKey(_rawValue: NSDeviceColorSpaceName): NSCalibratedRGBColorSpace]
2:24:22 PM :        bottomLeftFrame (1920.0, 0.0, 1920.0, 1080.0)
2:24:22 PM : src orig : (0.0, 0.0)
2:24:22 PM : left 0.0 below 0.0
2:24:22 PM : src orig : (1920.0, 0.0)
2:24:22 PM : left 1.0 below 0.0
2:24:22 PM : [id=188925686, width=1920, height=1080, bottomLeftFrame=(0.0, 0.0, 1920.0, 1080.0), topRightCorner=(1920.0, 1080.0), isMain=true, backingScaleFactor=1.0]
2:24:22 PM : [id=188914420, width=1920, height=1080, bottomLeftFrame=(1920.0, 0.0, 1920.0, 1080.0), topRightCorner=(3840.0, 1080.0), isMain=false, backingScaleFactor=1.0]
2:24:22 PM : (0.0, 0.0, 3840.0, 1080.0)
2:24:22 PM : ***Display Detection Done***
2:24:22 PM : Using : nil
2:24:22 PM : <AerialView: 0x7fb37fd0a370> setting up player layer with bounds/frame: (0.0, 0.0, 296.0, 184.0) / (0.0, 0.0, 296.0, 184.0)
2:24:22 PM : Using dot workaround for video driver corruption
2:24:22 PM : Manifest init
2:24:22 PM : app support exists
2:24:22 PM : No customvideos.json at : /Users/scott/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial/customvideos.json
2:24:22 PM : isManifestCached 10 true
2:24:22 PM : isManifestCached 11 true
2:24:22 PM : isManifestCached 12 true
2:24:22 PM : isManifestCached 13 true
2:24:22 PM : 2020-06-04
2:24:22 PM : Interval : Optional(-51862.42575097084)
2:24:22 PM : No need to check for new videos
2:24:22 PM : Manifests files were not loaded in class
2:24:22 PM : Files were not already loaded in memory
2:24:22 PM : Manifests are cached on disk, loading
2:24:22 PM : Poi Strings Provider initialized
2:24:22 PM : Preferred languages : ["en-US"]
2:24:22 PM : Best matched language : en
2:24:22 PM : Defaulting to bundle
2:24:22 PM : path : /Library/Screen Savers/Aerial.saver/Contents/Resources/en.json
2:24:22 PM : Community JSON : 99 entries
2:24:22 PM : No local or user cache exists, using ~/Library/Application Support/Aerial
2:24:22 PM : cache to be used : Optional("/Users/scott/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Application Support/Aerial")
2:24:22 PM : Total videos processed : 99 callbacks : 0
2:24:22 PM : <AerialView: 0x7fb37fd0a370> Setting player for all player layers in []
2:24:22 PM : initvideocache
2:24:22 PM : <AerialView: 0x7fb37fd0a370> streaming video (not fully available offline) : https://sylvan.apple.com/Videos/comp_LA_A006_C008_PSNK_ALL_LOGOS_v10_SDR_PS_FINAL_20180801_SDR_2K_AVC.mov
2:24:22 PM : <AerialView: 0x7fb37fd0a370> observing current item <Aerial.AerialPlayerItem: 0x6000036025a0, asset = <AVURLAsset: 0x6000036027a0, URL = streaming://sylvan.apple.com/Videos/comp_LA_A006_C008_PSNK_ALL_LOGOS_v10_SDR_PS_FINAL_20180801_SDR_2K_AVC.mov>>
2:24:22 PM : <AerialView: 0x7fb37fd0a370> observeValue Optional("readyForDisplay") false (0.0, 0.0, 296.0, 184.0)
2:24:22 PM : <AerialView: 0x7fb37fd0a370> backing change 1.0 isDisabled: false frame: (0.0, 0.0, 296.0, 184.0) preview: true
2:24:22 PM : Processsing contentInformationRequest
2:24:22 PM : expected content length: 276412459 type:com.apple.quicktime-movie
2:24:22 PM : Processsing contentInformationRequest
2:24:22 PM : expected content length: 276412459 type:com.apple.quicktime-movie
2:24:23 PM : <AerialView: 0x7fb37fd0a370> startAnimation frame (0.0, 0.0, 296.0, 184.0) bounds (0.0, 0.0, 296.0, 184.0)
2:24:23 PM : connectionDidFinishLoading
2:24:23 PM : <AerialView: 0x7fb37fd0a370> observeValue Optional("readyForDisplay") true (0.0, 0.0, 296.0, 184.0)
2:24:23 PM : start playback: (0.0, 0.0, 296.0, 184.0) (0.0, 0.0, 296.0, 184.0)
2:24:23 PM : <AerialView: 0x7fb37fd0a370> stopAnimation
2:24:23 PM : pwc init2
2:24:24 PM : Callback after manifest loading
2:24:24 PM : Looking for outdated files
2:24:24 PM : No old files found
2:24:24 PM : Aerial control panel V1.9.1beta1
2:24:24 PM : Cache size : 5.58 GB
2:24:24 PM : cvcinit2
2:24:24 PM : cvcawake
2:24:24 PM : wdl
2:24:46 PM : Location initialized
2:24:46 PM : Location services enabled
2:24:46 PM : LMauth status change : 3
2:24:46 PM : Location coordinate : CLLocationCoordinate2D(latitude: 34.26189662830706, longitude: -118.51755166602166)
2:24:46 PM : Location using cached data
2:24:46 PM : === YW: Starting locationMode
2:24:53 PM : Location using cached data
2:24:53 PM : Location using cached data
2:24:53 PM : === YW: Starting locationMode

**Comment by glouel** [comment] 2020-06-04 21:35
Thanks for the log, looks like it doesn't answer the mystery, I'll need to have a further look.

As for the plist, please drag the file directly to attach it, don't paste from it from an editor, thanks !

**Comment by TechJedi51** [comment] 2020-06-04 22:03
No MDM on this Macintosh (nothing in Profiles). But if you want, I have another Macintosh that is under MDM that I can test on.

Also, here is the attached plist. (It wouldn't upload a plist, so I zipped it.
[com.JohnCoates.Aerial..plist.zip](https://github.com/JohnCoates/Aerial/files/4732920/com.JohnCoates.Aerial.plist.zip)

**Comment by glouel** [comment] 2020-06-05 11:58
Thanks for your patience and uploading the plist, I managed to reproduce your issue using your plist so that's great, I'll update you when I understand what happens here with hopefully a quick fix. 

And ok, good to know about MDM (just trying to narrow down the possible cause of weather thing so no need to test on another machine for now but thanks for offering).

**Comment by glouel** [comment] 2020-06-05 12:21
@TechJedi51 Ok found the issue. You've put stuff in both the top and bottom middle of the screen (weather and date). That created a situation where there was no space to display the location in random mode, and an infinite loop. It's likely the issue from the top poster too. 

Long story short, Aerial tries hard not to make overlaps so if you put one thing in the middle (either top or bottom), the Location (which has longish strings) when set to random, will avoid the left/right corner of that row. But if you put something in both and had random for location, well, I didn't account for that and it crashed !

I'll think about how I can solve that one, maybe I shouldn't have added those center options 😅

Here's an illustration of your settings (with the overlap restriction disabled) : 

![Capture d’écran 2020-06-05 à 14 16 12](https://user-images.githubusercontent.com/37544189/83875617-b6322180-a737-11ea-9070-3ec5dcfd8a03.jpg)

**Comment by glouel** [comment] 2020-06-05 13:13
@TechJedi51 this should be fixed now :
 
![Capture d’écran 2020-06-05 à 14 50 51](https://user-images.githubusercontent.com/37544189/83879538-14620300-a73e-11ea-8f2e-409434fb2c60.jpg)

I did found that my margin/offset calculation (to avoid overlaps) only take one screen into account, seems I didn't fully think through the display option when I added it 🙈 So there's definitely more work there in terms of alignment for some more complex configurations, I'll have to double check that but it should not crash at least (and look decent enough). 

Please try 1.9.1 and let me know if it works. I also added some more debugging to the yahoo thing, you should see the lat: lon: info being replace with an error message, the error message will also show up in the log, so please let me know what it says. I didn't ask but are you behind a proxy possibly or something that could block access to yahoo's API ? 

Anyway, please try 1.9.1.

Also @MrGadget1701, please try 1.9.1 as I think it fixes your issue too. 

https://github.com/JohnCoates/Aerial/releases/download/v1.9.1/Aerial.saver.zip

**Comment by TechJedi51** [comment] 2020-06-05 18:14
That worked great. I was able to open and close System Preferences several times and each time the Preview worked as well as the settings button. 

Here is the log entry for the weather issue.

```
11:09:18 AM : spanned active rect (0.0, 0.0, 3840.0, 1080.0)
11:09:31 AM : Location using cached data
11:09:31 AM : Location using cached data
11:09:31 AM : === YW: Starting locationMode
11:09:31 AM : The operation couldn’t be completed. (OAuthSwiftError error -11.)
```

**Comment by TechJedi51** [comment] 2020-06-05 18:55
Bingo, the weather issue wasn't an Aerial issue at all. I checked and the URL loaded properly. But most of our systems have Little Snitch installed, so I checked and there were NO "deny" rules for that URI. But, for some reason it was not reaching out. So I created an "allow" rule and now the weather works perfectly. Below is the rule created. Thanks for all your work and creating a great screen saver. Do you have a Patreon.com or donations page?

![Screen Shot 2020-06-05 at 11 49 58 AM](https://user-images.githubusercontent.com/28914268/83912708-2a15ff00-a723-11ea-844d-9f6b9b18fbe8.png)

**Comment by glouel** [comment] 2020-06-05 19:06
> Bingo, the weather issue wasn't an Aerial issue at all. I checked and the URL loaded properly. But most of our systems have Little Snitch installed, so I checked and there were NO "deny" rules for that URI. But, for some reason it was not reaching out. So I created an "allow" rule and now the weather works perfectly. Below is the rule created. 

I swear, 95% of the issues people report are with Little Snitch 🤣 As much as I love the idea behind it, its default are really rough for everything I do and apparently their UI isn't clear enough about what gets blocked, your example is pretty interesting. 

Be aware it also tends to block the auto-update feed (although that's less of an issue with Catalina since Catalina broke those) which is here : https://raw.githubusercontent.com/JohnCoates/Aerial/master/appcast.xml

And if you want color icons instead of flat, I'm pretty sure I had a report saying they blocked that too, for example : https://s.yimg.com/zz/combo?a/i/us/nws/weather/gr/28d.png

> Thanks for all your work and creating a great screen saver. Do you have a Patreon.com or donations page?

I have a (very small) PayPal donate link on the main project page near my name at the top. Take care.

**Comment by TechJedi51** [comment] 2020-06-05 19:14
I figured as much. Little Snitch is great, except for the fact that it is complicated for the majority of users. We are Apple Consultants, and spend a lot of time configuring it for our clients. Here are the other two rules in case anyone else runs into this issue:
![Screen Shot 2020-06-05 at 12 11 52 PM](https://user-images.githubusercontent.com/28914268/83914406-056f5680-a726-11ea-905d-821ccabd0469.png)
![Screen Shot 2020-06-05 at 12 12 00 PM](https://user-images.githubusercontent.com/28914268/83914411-06a08380-a726-11ea-8f03-58400ce5a4a7.png)

**Comment by glouel** [comment] 2020-06-05 19:16
If that's ok with you, I'll use your screenshots in the troubleshooting page here : https://github.com/JohnCoates/Aerial/edit/master/Documentation/Troubleshooting.md

This should be helpful to other users !

**Comment by TechJedi51** [comment] 2020-06-05 19:18
Absolutely! FYI, found the link. Thanks again!

**Comment by glouel** [comment] 2020-06-05 19:23
> Absolutely! FYI, found the link. Thanks again!

Many thanks for both things, really appreciated ! 

(updated page here with your screenshot : https://github.com/JohnCoates/Aerial/blob/master/Documentation/Troubleshooting.md)

**Comment by TechJedi51** [comment] 2020-06-05 19:25
This may make it easier for users. Attached is a Rule Group that they can subscribe to, you just need to provide a link to it. (See "Providing a URL" on https://help.obdev.at/littlesnitch/lsc-rule-group-subscriptions). If you need any help with it, let me know. I would be happy to return the favor.

[AerialScreenSaver-LittleSnitch.lsrules.zip](https://github.com/JohnCoates/Aerial/files/4738063/AerialScreenSaver-LittleSnitch.lsrules.zip)

**Comment by glouel** [comment] 2020-06-05 19:30
Ha, this looks awesome ! I'll have a look tomorrow and set it up this indeed should make it much easier. Thanks !

**Closed** 2020-11-22 16:24 UTC

**Comment by sbay** [comment] 2021-02-24 19:37
I cannot open "Screen Save Options..." from "Desktop & Screen Saver" screen. Clicking the button does not do anything. Tried restarting, updated to latest Big Sur, removed plist file and still nothing...
