### ISSUE TITLE
Does not work with proxy

### ISSUE THREAD

**Issue by Curtisjk** [JohnCoates/Aerial#9] opened 2015-10-27 12:37 UTC
I am attempting to use this screensaver at work, where we use a proxy. I have installed but the images do not load. After a period of time, a play button with a line through it appears - indicating the content could not be played.

Proxy has been set in network settings and inside terminal profile.

**Comment by Gatewayy** [comment] 2015-10-27 13:31
I have the same issue as well, the screensaver does work fine at my home though.  Our proxy is network based and does not have any settings on our computers that I can find.

**Comment by Stephanvs** [comment] 2015-10-27 13:38
I have the same issue as @Gatewayy and cannot influence the settings

**Comment by alistairmcmillan** [comment] 2016-01-29 01:35
Duplicate of #5

**Closed by alistairmcmillan** 2016-01-29 01:35 UTC
Labels: duplicate
