### ISSUE TITLE
Prevents El Capitan Sleep

### ISSUE THREAD

**Issue by tiagratim** [JohnCoates/Aerial#133] opened 2015-11-03 15:30 UTC
Running the screen saver seems to keep El Capitan 10.11.1 from sleeping. (At least on my MacBook Pro 13 Early 2015). If I have the "put display to sleep" slider set to 1 min, everything works. But even sliding up to 3min seems to disallow sleep. My assumption is that the video files are more than 1 min but less than 3 min in length, so the OS considers it a new operation when the new video starts. (Just my guess)
I really love this screen saver but it's expensive for the monitor to run all night as happened last night.

**Comment by dcoeurjo** [comment] 2015-11-03 15:54
+1

**Comment by dcoeurjo** [comment] 2015-11-03 15:54
duplicate of #129

**Comment by dcoeurjo** [comment] 2015-11-03 15:56
dup of #23 BTW

**Comment by alistairmcmillan** [comment] 2015-11-03 16:12
@tiagratim Which version are you running? Beta 4 should fix this issue.

https://github.com/JohnCoates/Aerial/releases

**Comment by tiagratim** [comment] 2015-11-03 16:30
Is beta 4 new today? I didn't actually notice a beta designation when I downloaded Monday afternoon. Sorry if this duplicated another thread, I'm new to Github.

**Comment by tiagratim** [comment] 2015-11-03 17:05
Didn't fix the issue so I posted on that thread as well.

**Comment by MattRiddell** [comment] 2015-12-03 12:56
+1 running latest beta as of the 2nd of December - woke in the middle of the night and my screen was still on

**Comment by fletch247** [comment] 2015-12-03 13:53
macbook pro 15" mid 2014 el capitan 10.11.2 beta (15c48a) aerial 1.2 beta 5
NO problems! screensaver works well and macbook goes to sleep as it should.

**Comment by MattRiddell** [comment] 2015-12-03 14:19
Mine is the same model, but with a release version of el capitan and is connected to a 27 inch cinema display.  The macbook's lid is always closed.

**Comment by alistairmcmillan** [comment] 2016-01-28 21:14
Closing as duplicate of #23

**Closed by alistairmcmillan** 2016-01-28 21:14 UTC
Labels: duplicate
