### ISSUE TITLE
New aerials on my appletv

### ISSUE THREAD

**Issue by alextd** [JohnCoates/Aerial#223] opened 2016-03-27 15:48 UTC
I'm noticing new aerial videos on my appletv. But they are not listed where I expect them to be : http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

I guess http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json is outdated?

I say this as if I use this screensaver, but actually I have my own script to get videos. I assume both our tools work the same but the list is just not updated. Maybe a new list file with the recent update? Basically I'm wondering if you have any idea where the new videos are coming from.

-Alex TD

**Comment by broderik** [comment] 2016-04-09 06:22
I just noticed some of the new videos as well, glad to see someone has posted about it already.

**Comment by JohnCoates** [comment] 2016-04-09 06:42
No idea what the new URL is. I actually used the Apple TV simulator to get
the first one. I don't have an ATV 4😕

**Comment by broderik** [comment] 2016-04-09 07:17
I don't know any programming but I do have an ATV4 and I'm pretty good at following instructions. Would it be a relatively simple process for me to somehow find out where my ATV is getting the new videos? Some kind of network monitoring utility?

**Comment by Bensge** [comment] 2016-04-12 17:50
@broderik You are correct, one could observe network connections of the Apple TV and look for the screensaver downloads.
 I've used [Charles](http://www.charlesproxy.com) in the past, it should work for this use-case too (it offers a free trial). You basically have to tunnel the TV's networking through your computer by configuring your computer as an HTTP proxy. Keep in mind it might not be very straightforward to do - I'm happy to help, but I don't have an Apple TV. The Apple TV also caches the videos, so you might have to force your Apple TV to redownload them by forcing a low disk space scenario or by restoring the Apple TV to factory settings. And once you've found the movie downloads, they should be easy to recognize, assuming they are hosted on [a1.phobos.apple.com](a1.phobos.apple.com) just like the screensaver directory. Make sure you take a couple of screenshots of the request metadata etc, the problem might just be a new parameter. Would be great someone with an Apple TV could do it 😊

**Comment by broderik** [comment] 2016-04-13 03:10
I would certainly love to help try to capture that info, but I do have a few questions after doing a bit of research on this. The networking settings on the ATV only allow me to change the IP or the DNS (by default they are both “automatic”). I can probably add a HTTP proxy by creating an Apple Configurator profile and loading it on there. Will that be necessary if I use Charles? I’ve never used that program before so I’m not sure of it’s capabilities.

**Comment by lukehamburg** [comment] 2016-04-13 18:54
Might be easiest to simply sniff the traffic from a mirrored switch port or (if you have a sufficiently capable router) using tcpdump directly from the router.

I have an ATV4 and I can try this later when I get home.

The only problem is if the ATV downloads via HTTPS then it would be more difficult to intercept.

**Comment by Bensge** [comment] 2016-05-02 15:33
@lukehamburg Did you have any time to look at this? Unfortunately I couldn't find any new aerials using the simulator. The same link from above is still embedded in some executables, sadly the simulator doesn't show the aerials, so it's not possible to record the traffic this way.

**Comment by lukehamburg** [comment] 2016-05-02 16:31
I just ran Wireshark on my router and booted up my ATV4.  The only URL I saw containing references to Aerials was that same one: http://a1.phobos.apple.com/us/r1000/000/Features/atv/AutumnResources/videos/entries.json

I will keep investigating.  Not sure where else they could be coming from.

**Comment by Bensge** [comment] 2016-05-02 18:41
Maybe the new aerials came included in a software update? Would this be a possibility?

**Comment by alistairmcmillan** [comment] 2016-05-06 21:25
@alextd Are you certain there are new aerials? Could you describe one of the new ones, or could you grab a photo of one for us?

**Comment by alistairmcmillan** [comment] 2016-06-24 17:27
@alextd @broderik @JohnCoates @Bensge @lukehamburg I've had a new AppleTV for a couple of months now and I've not noticed any new videos. Can anyone confirm there are new videos or should this Issue just be closed?

**Comment by lukehamburg** [comment] 2016-06-24 19:11
Can't speak for everyone but I've noticed some new ones appearing at the "old" feed.  So I think that's still being updated.  And I ran some packet captures on my network trying to find an alternate address but could not detect one. Thanks @alistairmcmillan

**Comment by alistairmcmillan** [comment] 2016-06-24 19:19
@lukehamburg I think if new ones appear in the old feed John's code will automatically pick them up. I'm sure I noticed new ones appearing in the cache folder a while ago. Haven't noticed any recently though.

Could you describe the new ones? How long ago did you notice them appear?

**Comment by clintmilner** [comment] 2016-08-09 15:19
I've been following this thread, and I've found a youtube video with the new videos 
https://www.youtube.com/watch?v=jz_QaSnlN6Q

In the mean time, I'll keep trying the suggestions above to find where the new videos are coming from.

**Comment by simonhowes** [comment] 2016-09-18 18:21
tvOS 10 has even more new videos. Be good if we can get these included also.

**Comment by alistairmcmillan** [comment] 2016-09-18 18:25
@simonhowes Can you grab photos of these new videos? People keep saying there are new ones, but every time I think I see a new one on my Apple TV it turns out to be one that has already been there for a while.

**Comment by alistairmcmillan** [comment] 2016-12-18 21:58
Closing as new aerials have been released and John's screensaver is picking them up as designed.

**Closed by alistairmcmillan** 2016-12-18 21:58 UTC
