### ISSUE TITLE
add version number to screen saver options

### ISSUE THREAD

**Issue by meesteridle** [JohnCoates/Aerial#162] opened 2015-11-16 13:13 UTC
could you add the version number in the screen saver options? Doesn't necessarily have to be another tab. could be like a footer at the bottom of the options page.

not a have-to-have kind of thing. just nice to have for sanity checking.

![screenshot_2015-11-16_07_10_23](https://cloud.githubusercontent.com/assets/10524893/11182584/6be2a8c8-8c31-11e5-9f71-c860039a6f48.jpg)

**Comment by alistairmcmillan** [comment] 2015-11-16 13:31
Duplicate of #144 and pull request available #128

**Comment by geo4orce** [comment] 2016-01-22 15:43
agreed on this one! (can I just +1 somehow here on GitHub?)

**Comment by alistairmcmillan** [comment] 2016-01-28 21:26
Closing as duplicate of #144

**Closed by alistairmcmillan** 2016-01-28 21:26 UTC
Labels: duplicate
