### ISSUE TITLE
Not working in my version of El Capitan

### ISSUE THREAD

**Issue by RobertoRubio** [JohnCoates/Aerial#25] opened 2015-10-27 17:46 UTC
10.11.1 (15B42)
<img width="318" alt="screen shot 2015-10-27 at 12 45 37 pm" src="https://cloud.githubusercontent.com/assets/8176328/10767115/ac5d6138-7ca8-11e5-939a-e68357c90aee.png">

**Comment by elliottregan** [comment] 2015-10-27 17:51
It works fine for me, and I have the same build as you (was on the beta releases, but dropped out at 11.1). 

Try reinstalling either just for your account, or for all accounts and report back with an update.

**Comment by macbookandrew** [comment] 2015-10-27 17:51
Try this suggestion too: https://github.com/JohnCoates/Aerial/issues/4#issuecomment-151557047

**Comment by alistairmcmillan** [comment] 2016-01-28 22:21
Closing as duplicate of #4

**Closed by alistairmcmillan** 2016-01-28 22:21 UTC
Labels: duplicate
