### ISSUE TITLE
4K quality videos?

### ISSUE THREAD

**Issue by Joshyangg** [JohnCoates/Aerial#384] opened 2017-09-24 07:59 UTC
As I'm using and loving Aerial on the 5K iMac. the FHD video quality is really lacking compared to the new 4K Apple TV offers. It's a huge difference now, since I can actually see both version in real time. Is it possible to upgrade the videos to 4K standards?

**Comment by alistairmcmillan** [comment] 2017-09-24 09:55
John is working on it. Closing as duplicate of #378 .

**Closed by alistairmcmillan** 2017-09-24 09:55 UTC
