### ISSUE TITLE
Feature Request: Update function

### ISSUE THREAD

**Issue by heutger** [JohnCoates/Aerial#549] opened 2018-10-18 07:09 UTC
Hi,

I would welcome an update function. Are there any plans?

Regards,
Christian

**Comment by glouel** [comment] 2018-10-18 09:00
Hi, see my comment here for more details : https://github.com/JohnCoates/Aerial/issues/545#issuecomment-430401262

The issue is, Aerial is a plugin to System Preferences from a technical point of view, not a proper app, so I don't think that the plugin can update itself. I'm looking at version checks for upcoming version as a workaround.

The best way to get auto updates right now, as mentionned in the project readme, is to use brew cask ! See : 
https://github.com/JohnCoates/Aerial#brew-cask-support---updated-for-version-141

**Comment by alxndrsbrwn** [comment] 2018-10-18 22:37
If you installed Brew Cask, is there a way to run the 'brew cask reinstall aerial' command from Automator? I can't seem to get it to work.

**Comment by glouel** [comment] 2018-10-18 22:55
> If you installed Brew Cask, is there a way to run the 'brew cask reinstall aerial' command from Automator? I can't seem to get it to work.

You should run `brew cask upgrade` to update Aerial (and other outdated apps). You can look for "shell script" in automator I think (I don't use automator much sorry, maybe someone else can help).

**Comment by NightRaider73** [comment] 2018-10-20 21:43
@alxndrsbrwn I have created a Automator file, I don't use Brew Cask, so I don't know if this works. Thanks
[Update Aerial.app.zip](https://github.com/JohnCoates/Aerial/files/2498571/Update.Aerial.app.zip)

**Comment by NightRaider73** [comment] 2018-10-20 21:47
@glouel Read this up above.

**Comment by glouel** [comment] 2018-10-22 18:19
Awesome thanks !

Linking.

**Comment by NightRaider73** [comment] 2018-10-22 19:53
@glouel Time to close

**Comment by esetnik** [comment] 2018-12-01 22:30
I did a cursory review and it looked pretty straight forward. The most complicated part is probably setting up and running the free-tier heroku instance in order to monitor the github releases page. There might be an easier way to do this by just manually creating the feed file and committing it to the project.

**Comment by glouel** [comment] 2018-12-13 14:52
I'm reopening this, this will be the main focus for me for 1.4.7.

**Comment by glouel** [comment] 2018-12-13 15:37
So far so good with Sparkle and the Heroku instance, but it has a pretty big drawback in that it generates the appcast for your own repos and not the ones you manage with the same name. So my current setup works only for my fork. 

It's good enough for testing and I'll be doing my implementation/testing there, but that won't do for the public release. I'll try getting in touch with @JohnCoates to find a solution.

**Comment by esetnik** [comment] 2018-12-13 18:07
Maybe we could just create a custom appcast and version it with this project. Then point it at the master branch like this https://raw.githubusercontent.com/JohnCoates/Aerial/master/appcast.xml. Then when you do a new release just include an updated appcast.xml file in the final merge to master.

**Comment by esetnik** [comment] 2018-12-13 18:07
Then you wouldn't need to deal with all the heroku stuff and everything would be self-contained in the project on github.

**Comment by glouel** [comment] 2018-12-13 18:56
Yep I'm looking at that as a plan B, one other issue with the heroku is that it doesn't handle the EdDSA signing that was added to Sparkle "recently" so that's an issue too that prevents updates. Otherwise sparkle integration looks ok (I did it with cocoapods which brings some issues by not copying frameworks into the .saver, but I worked around that).

**Comment by esetnik** [comment] 2018-12-16 20:00
Very cool!

**Comment by glouel** [comment] 2019-04-30 19:59
Closing this, available in 1.4.8.

**Closed by glouel** 2019-04-30 19:59 UTC
