### ISSUE TITLE
Enhancement: fade in/out

### ISSUE THREAD

**Issue by steve1412** [JohnCoates/Aerial#197] opened 2016-01-12 14:21 UTC
Hi John,

I'm posting here too just in case if the email doesn't work. As i was saying in the emails. I was hoping you could bring the following features to the future update if possible! 

-Fade-in & fade-out between videos
-Videos played based on time (using GPS for accuracy e.g. sunset moment or night time moment)

I believe the above features would surely bring the experience to another level. Let me know your thoughts.

Many thanks,

Steven Chen

**Comment by alistairmcmillan** [comment] 2016-01-13 10:26
At least partially a duplicate of #11

**Comment by glouel** [comment] 2018-10-11 18:09
Both implemented in 1.4, check if out if you can !

**Closed by glouel** 2018-10-11 18:09 UTC
Labels: enhancement
