### ISSUE TITLE
Location Details

### ISSUE THREAD

**Issue by woodwardc** [JohnCoates/Aerial#457] opened 2018-05-03 13:24 UTC
##Location 

Hello, I would like to make a feature request to have some text as to where the locations are of the videos. There has been some great scenery and frustrating not knowing what location that is from. 

I feel that this would benefit all you use this application.

**Comment by alistairmcmillan** [comment] 2018-06-06 17:23
Closing as duplicate of #58.

**Closed by alistairmcmillan** 2018-06-06 17:23 UTC
