### ISSUE TITLE
Add location name at corner when displaying screen saver

### ISSUE THREAD

**Issue by asafm** [JohnCoates/Aerial#318] opened 2017-02-07 13:56 UTC
You see this amazing aerial movies in screen saver but you don't know where they are. An option to display the location this movie was filmed will be most beneficial.

**Comment by vit0rg** [comment] 2017-02-07 14:03
Would be nice to have such option, missing it too.

**Comment by alistairmcmillan** [comment] 2017-02-07 14:52
Duplicate of #58 .

**Closed** 2017-02-20 08:25 UTC
Labels: duplicate, enhancement
