### ISSUE TITLE
Location name overlay

### ISSUE THREAD

**Issue by darkoddio** [JohnCoates/Aerial#424] opened 2017-11-24 15:11 UTC
may I suggest to add the location name during the playback?
maybe text very small on one bottom corner

**Comment by alistairmcmillan** [comment] 2017-11-24 18:26
Closing as duplicate of #389

**Closed by alistairmcmillan** 2017-11-24 18:26 UTC

**Comment by darkoddio** [comment] 2017-11-25 09:50
unfortunately that fork doesn't work with High Sierra
