### ISSUE TITLE
Ariel does not install--unregistered developer

### ISSUE THREAD

**Issue by duanes712** [JohnCoates/Aerial#57] opened 2015-10-28 19:33 UTC
Cannot install the developer unregistered error message is given. Latest Safari and system from Apple.

**Comment by trustypelletgun** [comment] 2015-10-28 19:47
You have to manually allow the installation. Go to the Security & Privacy section in System Preferences and click the "Open Anyway" button and provide admin credentials.

A faster (but less explicit and informative) way avoid this warning is to contol+click on the Aerial.saver file and click "Open" in the context menu. See this support document https://support.apple.com/kb/PH21769?locale=en_US for more information.

**Comment by duanes712** [comment] 2015-10-28 20:25
Excellent answer. It works as advertised using the methods suggested trustypelletgun.

**Comment by fwartner** [comment] 2015-10-29 01:12
I have signed a release: https://github.com/fwartner/Aerial/releases/tag/v1.1%40signed

**Comment by alistairmcmillan** [comment] 2016-01-28 22:27
Closing as duplicate of #10

**Closed by alistairmcmillan** 2016-01-28 22:27 UTC
