### ISSUE TITLE
"You cannot run Aerial with this version of OS X"

### ISSUE THREAD

**Issue by RauCreativity** [JohnCoates/Aerial#30] opened 2015-10-27 20:20 UTC
I am running Yosemite, version 10.10.5. System preferences gives me the above error when I try to set it as the default.

**Comment by stevenlordiam** [comment] 2015-10-27 23:43
Change the system setting in Security & Privacy to "allow apps downloaded from" to "anywhere", then it can be opened.

**Comment by jamieatadobe** [comment] 2015-10-28 03:06
I'm getting this as well, running 10.11.1 and I have my Security and Privacy settings set to anywhere

**Comment by jbrooksuk** [comment] 2015-10-28 08:46
Same here, 10.11.1

**Comment by alistairmcmillan** [comment] 2016-01-28 22:42
Duplicate of #4 . @RauCreativity @jamieatadobe @jbrooksuk Leave a comment on #4 if you still need help getting this to run.

**Closed by alistairmcmillan** 2016-01-28 22:42 UTC
Labels: duplicate
