### ISSUE TITLE
4K content

### ISSUE THREAD

**Issue by niogyn** [JohnCoates/Aerial#391] opened 2017-09-29 19:44 UTC
First of all - 

I LOVE your work with this, I was only curious if you were planning on updating to support 4K content now they all the screensavers have been updated with the release of the 4K Apple TV?

**Comment by gabemunro** [comment] 2017-09-29 20:32
This is already discussed heavily in #378

**Comment by alistairmcmillan** [comment] 2017-09-29 21:56
Closing as duplicate of #378 .

**Closed by alistairmcmillan** 2017-09-29 21:56 UTC
