### ISSUE TITLE
Big Sur 11.2.3 + Aerial 1.2 (Screensaver 2.3.0) + 2019 MBA 13 = Can't access preferences, blank screensaver

### ISSUE THREAD

**Issue by Apollostowel** [JohnCoates/Aerial#1172] opened 2021-04-27 12:36 UTC
As the subject says, it seems there's no more screensaver suddenly. It's a night and day issue, yesterday it worked, today, it no longer works. I just noticed when I left my screen that the screen was blank. I launched the Aerial app, accessed the screensaver preferences from that, but when I click on aerial's preferences, nothing happens, they won't launch. I tried a simple restart, but that didn't solve it.

I tried looking for the screensaver plugin to delete it, but it also doesn't seem to exist. I tried deleting and reinstalling through the app, but that didn't help either. Looking at the logs, it's like absolutely nothing is happening, is the application still around, or did it die somehow?

I know these are basic questions for GitHub types, but I'm at a loss as to what to do. I enabled debug mode, but I can't get as far as the advanced tab in the preferences, and no log is being generated.

**Comment by glouel** [comment] 2021-04-27 12:41
Hey @Apollostowel 

This is weird. There were a couple of people having some similar issues like this here not long ago with 11.2.3. One fixed it by reinstalling, the other didn't. The thread is here https://github.com/JohnCoates/Aerial/issues/1167

I would suggest trying to uninstall the plugin and reinstall. You will find all the paths and everything here for the plugin location etc : https://aerialscreensaver.github.io/installation.html

If you still have the issue, and don't mind helping a bit, I'd love to dig into what happens exactly, using Console and looking for any crash log etc. Let me know how reinstalling goes first. 

Thanks

**Comment by Apollostowel** [comment] 2021-04-27 15:32
Thanks for getting back to me so fast! I was so hopeful that it was an 11.2.3 thing, and that 11.3 would solve it, but no such luck. I went ahead and followed the uninstallation instructions and deleted the caches that existed, but the last one mentioned in the uninstallation instructions didn't exist for some reason.

I went ahead and reinstalled the newest companion app, and the 2.3.1 beta, and it still doesn't work, it's a blank screen, and no access to preferences, on Big Sur 11.3 now. I couldn't figure out which part of the logs might be helpful, but I think maybe there's a mention here:

Apr 27 18:22:49 Kimberlys-Air diagnosticd[2310]: Posting empty stream filter
Apr 27 18:22:49 Kimberlys-Air diagnosticd[2310]: no EOS device present
Apr 27 18:22:49 Kimberlys-Air diagnosticd[2310]: allowing Console (2309) access to stream due to admin status
Apr 27 18:22:49 Kimberlys-Air diagnosticd[2310]: Posting stream filter: "{
	    global = 47245099008;
	}"
Apr 27 18:22:49 Kimberlys-Air diagnosticd[2310]: System mode client started - Console (2309) - mode: 0xb, filter: "<empty>"
Apr 27 18:23:16 Kimberlys-Air ScreenSaverEngine[2311]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Apr 27 18:23:16 Kimberlys-Air ScreenSaverEngine[2311]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Apr 27 18:23:18 Kimberlys-Air com.apple.xpc.launchd[1] (com.apple.xpc.launchd.domain.user.501): Service "com.apple.xpc.launchd.unmanaged.loginwindow.128" tried to register for endpoint "com.apple.tsm.uiserver" already registered by owner: com.apple.TextInputMenuAgent
Apr 27 18:23:18 --- last message repeated 1 time ---
Apr 27 18:23:18 Kimberlys-Air legacyScreenSaver[2313]: getattrlist failed for /System/Library/Extensions/AppleIntelKBLGraphicsGLDriver.bundle/Contents/MacOS/AppleIntelKBLGraphicsGLDriver: #2: No such file or directory
Apr 27 18:23:18 Kimberlys-Air legacyScreenSaver[2313]: getattrlist failed for /System/Library/Frameworks/OpenGL.framework/Resources//GLRendererFloat.bundle/GLRendererFloat: #2: No such file or directory
Apr 27 18:23:27 Kimberlys-Air com.apple.xpc.launchd[1] (com.apple.ScreenSaver.iLife-Slideshow-Extension[2312]): Service exited due to SIGKILL | sent by iLifeSlideshows[2312]
Apr 27 18:23:27 Kimberlys-Air com.apple.xpc.launchd[1] (com.apple.ScreenSaver.Computer-Name[2314]): Service exited due to SIGKILL | sent by Computer Name[2314]
Apr 27 18:23:27 Kimberlys-Air com.apple.xpc.launchd[1] (com.apple.ScreenSaver.Engine.legacyScreenSaver[2318]): Service exited due to SIGTERM | sent by launchd[1]
Apr 27 18:23:56 Kimberlys-Air com.apple.xpc.launchd[1] (com.apple.mdworker.shared.0D000000-0000-0000-0000-000000000000[2315]): Service exited due to SIGKILL | sent by mds[83]
Apr 27 18:24:24 Kimberlys-Air com.apple.xpc.launchd[1] (com.apple.mdworker.shared.08000000-0000-0000-0000-000000000000[2307]): Service exited due to SIGKILL | sent by mds[83]
Apr 27 18:25:59 Kimberlys-Air Console[2309]: BUG in libdispatch client: vnode, monitored resource vanished before the source cancel handler was invoked { 0x6000077de180[source], ident: 17 / 0x11, handler: 0x7fff6fa6afbc }

I have no idea how all this went wrong even, but thanks for having a look into it!

**Comment by glouel** [comment] 2021-04-27 15:48
No worries, it's certainly puzzling to me, and the log doesn't tell me much but thanks for providing it.

Couple of ideas, please launch console and look for a crash report : 

![Capture d’écran 2021-04-20 à 13 28 03](https://user-images.githubusercontent.com/37544189/115388849-a6e78580-a1dc-11eb-9d5a-a3c8fa15abec.jpg)

If you see something with Aerial, legacyScreenSaver, ScreenSaverEngine, or maybe System Preferences, that would be interesting. 

If you don't, in Console, filter by error/warning, start the monitoring, and launch System Preferences panel that doesn't work, and paste whatever came there. 

Thanks !

**Comment by glouel** [comment] 2021-04-27 16:46
Many thanks for the detailed response... It kinda look like Aerial does throw an error at some point at startup which is very weird. 

One thing I'm thinking is maybe something with settings. Here's an idea, in terminal, try this: 

```
defaults read ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist > oldsettings.plist
```

This will save your current settings just in case. 

Then : 

```
defaults delete ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist
```

This will wipe your settings. I'll try to think of other things but this may solve the issue. Should that solve it, please attach the oldsettings.plist file, so I can try and reproduce it here. Thanks !

**Comment by Apollostowel** [comment] 2021-04-27 17:55
Okiedokie, progress! I got the preferences back, the preferences are all working, but now the screensaver itself doesn't work, and is all black, I gotta figure out what changed and why video won't play anymore, but the preferences are back at least! 
[oldsettings.txt](https://github.com/JohnCoates/Aerial/files/6386594/oldsettings.txt)

The plist wouldn't upload, had to rename.

**Comment by Apollostowel** [comment] 2021-04-27 17:58
I spoke too soon, the preferences no longer work, just worked 5 minutes ago, now is dead as a doornail again. I think I gotta give up for now, this just ain't working. Thank you though, for working so hard on it. :(

**Comment by glouel** [comment] 2021-04-27 18:24
> I spoke too soon, the preferences no longer work, just worked 5 minutes ago, now is dead as a doornail again. I think I gotta give up for now, this just ain't working. Thank you though, for working so hard on it. :(

Hmm, did you change anything in preferences ? I will try your settings here, see if I can manage to reproduce the issue. I'd suggest deleting the plist again, and trying to launch the screensaver, this should work in the meantime while I figure things out... 

Thanks for following up on this

**Comment by glouel** [comment] 2021-04-27 18:52
Sorry, maybe I'm tired but looks like I can't import your plist. It's readable by me (and looks fine) but for some reason I can't seem to import readable style plists (so called "old style"). 

So, if it still doesn't work, could you run this instead : 

```
defaults export ~/Library/Containers/com.apple.ScreenSaver.Engine.legacyScreenSaver/Data/Library/Preferences/ByHost/com.JohnCoates.Aerial.plist old2.plist
```

Then rename that to .txt and I should be able to import it (it exports to binary, which imports fine). If it works again though and you already did the delete again, I'm wondering if changing some option got it to crash, which is very weird. 

There may be some regional setting or something I didn't take into account somewhere. 

Thanks again, I'll try to get back to you tomorrow.

**Comment by Apollostowel** [comment] 2021-04-29 10:12
I don't know how much help it'll be, because I deleted the plist again, and for the present, preferences are working, but the screensaver itself is blank. I've tried every video setting, and I've downloaded the videos, and it doesn't matter, they just don't play. I'm sure once the preferences stop opening, I can get another plist to you.

[old2.txt](https://github.com/JohnCoates/Aerial/files/6397818/old2.txt)

**Comment by glouel** [comment] 2021-04-29 10:24
I think I'm narrowing down on the issue, thanks for the plist I'll have a look. 

If I may ask, what are your regional settings in macOS ? I think I made a mistake somewhere that may cause a problem with some locales.  Thanks !

**Comment by Apollostowel** [comment] 2021-04-29 10:35
English is the primary language, but the region is set to Finland. The preferences stopped opening again, so here's an old2.plist part deux! Thanks for helping so much!

[old3.txt](https://github.com/JohnCoates/Aerial/files/6397934/old3.txt)

**Comment by glouel** [comment] 2021-04-29 11:01
Thanks again for the plist, I think I'm closing in on the issue, there must be some issue with the way I cache coordinates and some mismatch with locales. I did try to replicate by setting English (US) and Region Finland and using you plist here but haven't managed yet, does that look similar to what you have ? 

![Screen Shot 2021-04-29 at 12 58 43](https://user-images.githubusercontent.com/37544189/116540769-e2740500-a8ea-11eb-8314-8158835c5164.png)

Specifically, I'm interested in the circled parts, whether you picked English US or some other English, and the "," or "." in the numbers at the bottom. I'll keep you posted as I double check stuff here but I think the issue is with weather indeed (and more precisely location caching) as you had gathered above.

**Comment by Apollostowel** [comment] 2021-04-29 11:21
For me, it's English (there's no choice for English US, just English or UK English, and I edit for some UK English authors, so need that!), and the time zone is EEST (Eastern European Time), but otherwise, yeah! Should I just uninstall and wait for a new version? Thanks again for having a look, in either case.
![Uploading Screenshot 2021-04-29 at 14.18.42.png…]()

**Comment by glouel** [comment] 2021-04-29 11:33
Wondering why I can't get that regular english here, hmm! 

In any case, if you still don't mind fiddling a tiny bit more, would you try wiping settings if they are bad again, and setup weather this way : 

![Screenshot 2021-04-29 at 13 28 57](https://user-images.githubusercontent.com/37544189/116544124-06d1e080-a8ef-11eb-8b33-b47c8f2375ea.png)

Make sure you pick Manually Specify and type your city. Then press the Test button. Let's see if that works in the meantime.  I'll get back to you asap as I do more digging on this today. Again sorry about this, I'm having a hard time seeing the issue but I'm sure it will come soon.

**Comment by glouel** [comment] 2021-04-29 11:52
Wow... I think I finally found the issue. It looks like you don't have an astronomical sunrise/sunset right now up north, in this part of the year, and I didn't properly account for that somewhere in the code ! 

Couple of examples : 
https://www.timeanddate.com/sun/norway/trondheim
https://www.timeanddate.com/sun/finland/helsinki

Working on a fix, I'll keep you posted.

**Comment by glouel** [comment] 2021-04-29 12:58
@Apollostowel just posted the fix, which is available here or directly through Companion if you use it : 

https://github.com/JohnCoates/Aerial/releases/tag/v2.3.2

The issue happened with that setting in cases where your coordinates retuned no astronomical sunrise/sunset for that day. Aerial should now work correctly including weather (which was indirectly the culprit, it shares the same location source). 

Anyway, many thanks for your patience on this, really happy to have finally figured this out !

**Comment by Apollostowel** [comment] 2021-04-29 14:42
It's back, baby! OMG who'd a thunk that the entire program would just nope right on outta there for one little setting. I definitely oh many coffees now. Thank you so much!

**Comment by glouel** [comment] 2021-04-29 14:52
You're welcome, the bug was here since last august so there are probably other people who experienced the same crash...  so thankfully it's fixed now 😅

**Closed by glouel** 2021-04-29 14:52 UTC
