### ISSUE TITLE
Night Shift Incompatibility

### ISSUE THREAD

**Issue by JTOwden** [JohnCoates/Aerial#402] opened 2017-10-11 10:18 UTC
When night shift is on screensaver either distorts into bars or doesn't load. 
Disabling nightshift immediately fixes the issue.

Otherwise a beautiful screensaver, wish it came as standard on Macs 🙂

**Comment by benmarten** [comment] 2017-10-16 01:20
Not reproducible for me, works with NightShift enabled and macOS 10.13.

**Comment by alistairmcmillan** [comment] 2017-10-16 01:49
@JTOwden @benmarten I can reproduce on a 13" early 2015 MacBook Pro. As a workaround try enabling the "Show with clock" option.

This just seems to be more of the same Intel driver issue that Apple introduced with High Sierra. More discussion here #377

**Comment by alistairmcmillan** [comment] 2017-10-16 22:32
Closing as duplicate of #377

**Closed by alistairmcmillan** 2017-10-16 22:32 UTC
