### ISSUE TITLE
New Screensavers from Apple TV

### ISSUE THREAD

**Issue by googlercolin** [JohnCoates/Aerial#282] opened 2016-12-19 10:01 UTC
Hi John,
May I know if the new screen savers from the Apple TV which debuted a fews days ago will be included in Aerial real soon? 😄
Thanks!

**Comment by alistairmcmillan** [comment] 2016-12-19 10:22
John designed the screen saver to pick up new aerials as Apple add them. If they're not appearing for you make sure you're on the latest version.

https://github.com/JohnCoates/Aerial/releases/tag/v1.2

**Comment by alistairmcmillan** [comment] 2016-12-19 10:24
Closing as duplicate of #276

**Closed by alistairmcmillan** 2016-12-19 10:24 UTC
