### ISSUE TITLE
Weather Overlay still shows wind/humidity even if turned off

### ISSUE THREAD

**Issue by ewregister** [JohnCoates/Aerial#1186] opened 2021-07-06 17:36 UTC
- [x] Mac model: M1 Macbook Pro
- [x] macOS version: Big Sur 11.4
- [x] Monitor setup: External Display

I have deselected for wind and humidity for the weather overlay - set to Current Weather and those two still show underneath the temperature

Thank you!

**Comment by glouel** [comment] 2021-07-06 21:14
Hey @ewregister 

You are correct, actually the humidity doesn't show on Current Weather, just Wind, but those options only work with the forecasts. I'll try to fix that for next build, thanks for the heads up! I also need to check if humidity is available on current weather...

**Comment by ewregister** [comment] 2021-07-06 23:01
Cool! Really like the clean look but where I am, its just the temperature that is important. There's no wind or much humidity!
Cheers!

**Comment by glouel** [comment] 2021-07-07 08:18
Yep, everyone has different needs so I try to cover it all. The wind is fixed for next beta, which should probably be out later today, still looking at humidity there : 

![Capture d’écran 2021-07-07 à 10 15 26](https://user-images.githubusercontent.com/37544189/124724851-a70a3e00-df0c-11eb-9ba5-9ae358e39f6d.jpg)

**Comment by glouel** [comment] 2021-07-08 13:32
Hey again @ewregister 

Sorry for the delay, I finished adding humidity yesterday but wanted to fix another bug with Apple Music integration before releasing, then I got into a rabbit hole adding per video playback speed controls 🤣

Anyway, here it is will all the fixes, disabling wind and humidity now works as intended (and you can have humidity too which wasn't the case before) :  

![Capture d’écran 2021-07-08 à 15 13 21](https://user-images.githubusercontent.com/37544189/124930520-b1f2ca80-e001-11eb-93c1-db9878ae8579.jpg)

It's in 2.3.4beta4 which you can get from Companion.

**Comment by glouel** [comment] 2022-01-17 21:31
Fixed in 3.0

**Closed by glouel** 2022-01-17 21:31 UTC
Labels: bug, enhancement, fix inside
