### ISSUE TITLE
Use day/night aerials depending if it's really day or night

### ISSUE THREAD

**Issue by chreriksen** [JohnCoates/Aerial#366] opened 2017-07-12 18:13 UTC
It would be so much more awesome if Aerial could decide, based on user's local time, to either play day or night videos.

**Comment by lhandel** [comment] 2017-08-02 00:02
this branch has that feature https://github.com/lhandel/Aerial

**Comment by alistairmcmillan** [comment] 2017-09-14 18:57
Duplicate of #11

**Closed by alistairmcmillan** 2017-09-14 18:57 UTC
Labels: enhancement
